package afirme.afirmenet.model.pagos.impuestos;

import org.junit.Test;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import com.afirme.afirmenet.model.pagos.impuestos.Derechos;
import com.afirme.afirmenet.utils.xml.ParseXMLToPojoFactory;


public class DerechosTest {
	static final Logger LOG = LoggerFactory
			.getLogger(DerechosTest.class);
	@Test
	public void test(){
		String xml = "<?xml version=\"1.0\" ?><DERECHOS><IDENTIFICACION><CONCEPTO><CLAVE>10001</CLAVE><DESCRIPCION>RFC</DESCRIPCION><VALOR>WEB081026AC7</VALOR><VALORIMPRESION>WEB081026AC7</VALORIMPRESION></CONCEPTO><CONCEPTO><CLAVE>10006</CLAVE><DESCRIPCION>Denominaci&#xf3;n o raz&#xf3;n social</DESCRIPCION><VALOR>WEBCOMUNIC&#x40;CION S.A. DE C.V.</VALOR><VALORIMPRESION>WEBCOMUNIC&#x40;CION S.A. DE C.V.</VALORIMPRESION></CONCEPTO><CONCEPTO><CLAVE>10017</CLAVE><DESCRIPCION>Total efectivamente pagado</DESCRIPCION><VALOR>3200</VALOR><VALORIMPRESION>&#x24;3,200.00</VALORIMPRESION></CONCEPTO><CONCEPTO><CLAVE>30005</CLAVE><DESCRIPCION>Dependencia</DESCRIPCION><VALOR>15</VALOR><VALORIMPRESION>15 Secretar&#xed;a de Salud</VALORIMPRESION></CONCEPTO></IDENTIFICACION><CONCEPTOS><CONCEPTO><CLAVE>14701</CLAVE><DESCRIPCION>Nombre del Concepto</DESCRIPCION><VALOR>Derechos, Productos y Aprovechamientos</VALOR><VALORIMPRESION>Derechos, Productos y Aprovechamientos</VALORIMPRESION></CONCEPTO><CONCEPTO><CLAVE>14702</CLAVE><DESCRIPCION>Per&#xed;odo</DESCRIPCION><VALOR>5</VALOR><VALORIMPRESION>Mayo</VALORIMPRESION></CONCEPTO><CONCEPTO><CLAVE>14727</CLAVE><DESCRIPCION>Ejercicio</DESCRIPCION><VALOR>2013</VALOR><VALORIMPRESION>2013</VALORIMPRESION></CONCEPTO><CONCEPTO><CLAVE>14704</CLAVE><DESCRIPCION>Importe</DESCRIPCION><VALOR>3200</VALOR><VALORIMPRESION>&#x24;3,200.00</VALORIMPRESION></CONCEPTO><CONCEPTO><CLAVE>14708</CLAVE><DESCRIPCION>Total de Contribuciones</DESCRIPCION><VALOR>3200</VALOR><VALORIMPRESION>&#x24;3,200.00</VALORIMPRESION></CONCEPTO><CONCEPTO><CLAVE>14720</CLAVE><DESCRIPCION>Cantidad Pagada</DESCRIPCION><VALOR>3200</VALOR><VALORIMPRESION>&#x24;3,200.00</VALORIMPRESION></CONCEPTO><CONCEPTO><CLAVE>14733</CLAVE><DESCRIPCION>Clave de Referencia del DPA</DESCRIPCION><VALOR>156000134</VALOR><VALORIMPRESION>156000134</VALORIMPRESION></CONCEPTO><CONCEPTO><CLAVE>14734</CLAVE><DESCRIPCION>Cadena de la dependencia</DESCRIPCION><VALOR>SSA20130500001</VALOR><VALORIMPRESION>SSA20130500001</VALORIMPRESION></CONCEPTO></CONCEPTOS></DERECHOS>";
		Derechos derechos = ParseXMLToPojoFactory.transform(xml, Derechos.class);
		LOG.info("Pojo Generado ====>" + derechos.toString());
	}
}
