/**
 *  This Class was created By Luis Velando
 *  Copyright Datapro Inc. 1999
 **/

package com.afirme.afirmenet.ibs.messages;

import java.math.BigDecimal;

import com.datapro.sockets.CharacterField;
import com.datapro.sockets.DecimalField;
import com.datapro.sockets.MessageField;
import com.datapro.sockets.MessageRecord;

/**
 * Class generated by AS/400 CRTCLASS command from ALCDSJV physical file
 * definition.
 * 
 * File level identifier is 1000802211753. Record format level identifier is
 * 5A71A46C8130C.
 */

public class ALCDSJVMessage extends MessageRecord {
	final int FIELDCOUNT = 30;
	private CharacterField fieldALCUSER = null;
	private CharacterField fieldALCTYP = null;
	private CharacterField fieldALCPLN = null;
	private DecimalField fieldALCAMT = null;
	private CharacterField fieldALCLNP = null;
	private DecimalField fieldALCACC = null;
	private CharacterField fieldALCAD1 = null;
	private CharacterField fieldALCAD2 = null;
	private CharacterField fieldALCAD3 = null;
	private CharacterField fieldALCAEML = null;
	private DecimalField fieldALCLVY = null;
	private CharacterField fieldALCOWP = null;
	private DecimalField fieldALCMPY = null;
	private DecimalField fieldALCRPY = null;
	private DecimalField fieldALCUPY = null;
	private DecimalField fieldALCHPN = null;
	private DecimalField fieldALCPHN = null;
	private CharacterField fieldALCEMP = null;
	private DecimalField fieldALCHDT1 = null;
	private DecimalField fieldALCHDT2 = null;
	private DecimalField fieldALCHDT3 = null;
	private CharacterField fieldALCJBT = null;
	private CharacterField fieldALCBKR = null;
	private DecimalField fieldALCCAC = null;
	private CharacterField fieldALCCAD1 = null;
	private CharacterField fieldALCCAD2 = null;
	private CharacterField fieldALCCAD3 = null;
	private CharacterField fieldALCCEML = null;
	private DecimalField fieldALCSSN = null;
	private CharacterField fieldALCMMN = null;

	/**
	 * Constructor for ALCDSJVMessage.
	 */
	public ALCDSJVMessage() {
		createFields();
		initialize();
	}

	/**
	 * Create fields for this message. This method implements the abstract
	 * method in the MessageRecord superclass.
	 */
	protected void createFields() {
		recordsize = 484;
		fileid = "1000802211753";
		recordid = "5A71A46C8130C";
		message = new byte[getByteLength()];
		formatname = "ALCDSJV";
		fieldnames = new String[FIELDCOUNT];
		tagnames = new String[FIELDCOUNT];
		fields = new MessageField[FIELDCOUNT];

		fieldnames[0] = "ALCUSER";
		tagnames[0] = "ALCUSER";
		fields[0] = fieldALCUSER = new CharacterField(message, HEADERSIZE + 0,
				10, "ALCUSER");
		fieldnames[1] = "ALCTYP";
		tagnames[1] = "ALCTYP";
		fields[1] = fieldALCTYP = new CharacterField(message, HEADERSIZE + 10,
				1, "ALCTYP");
		fieldnames[2] = "ALCPLN";
		tagnames[2] = "ALCPLN";
		fields[2] = fieldALCPLN = new CharacterField(message, HEADERSIZE + 11,
				25, "ALCPLN");
		fieldnames[3] = "ALCAMT";
		tagnames[3] = "ALCAMT";
		fields[3] = fieldALCAMT = new DecimalField(message, HEADERSIZE + 36,
				15, 2, "ALCAMT");
		fieldnames[4] = "ALCLNP";
		tagnames[4] = "ALCLNP";
		fields[4] = fieldALCLNP = new CharacterField(message, HEADERSIZE + 51,
				1, "ALCLNP");
		fieldnames[5] = "ALCACC";
		tagnames[5] = "ALCACC";
		fields[5] = fieldALCACC = new DecimalField(message, HEADERSIZE + 52,
				13, 0, "ALCACC");
		fieldnames[6] = "ALCAD1";
		tagnames[6] = "ALCAD1";
		fields[6] = fieldALCAD1 = new CharacterField(message, HEADERSIZE + 65,
				30, "ALCAD1");
		fieldnames[7] = "ALCAD2";
		tagnames[7] = "ALCAD2";
		fields[7] = fieldALCAD2 = new CharacterField(message, HEADERSIZE + 95,
				30, "ALCAD2");
		fieldnames[8] = "ALCAD3";
		tagnames[8] = "ALCAD3";
		fields[8] = fieldALCAD3 = new CharacterField(message, HEADERSIZE + 125,
				30, "ALCAD3");
		fieldnames[9] = "ALCAEML";
		tagnames[9] = "ALCAEML";
		fields[9] = fieldALCAEML = new CharacterField(message,
				HEADERSIZE + 155, 25, "ALCAEML");
		fieldnames[10] = "ALCLVY";
		tagnames[10] = "ALCLVY";
		fields[10] = fieldALCLVY = new DecimalField(message, HEADERSIZE + 180,
				4, 0, "ALCLVY");
		fieldnames[11] = "ALCOWP";
		tagnames[11] = "ALCOWP";
		fields[11] = fieldALCOWP = new CharacterField(message,
				HEADERSIZE + 184, 1, "ALCOWP");
		fieldnames[12] = "ALCMPY";
		tagnames[12] = "ALCMPY";
		fields[12] = fieldALCMPY = new DecimalField(message, HEADERSIZE + 185,
				15, 2, "ALCMPY");
		fieldnames[13] = "ALCRPY";
		tagnames[13] = "ALCRPY";
		fields[13] = fieldALCRPY = new DecimalField(message, HEADERSIZE + 200,
				15, 2, "ALCRPY");
		fieldnames[14] = "ALCUPY";
		tagnames[14] = "ALCUPY";
		fields[14] = fieldALCUPY = new DecimalField(message, HEADERSIZE + 215,
				15, 2, "ALCUPY");
		fieldnames[15] = "ALCHPN";
		tagnames[15] = "ALCHPN";
		fields[15] = fieldALCHPN = new DecimalField(message, HEADERSIZE + 230,
				12, 0, "ALCHPN");
		fieldnames[16] = "ALCPHN";
		tagnames[16] = "ALCPHN";
		fields[16] = fieldALCPHN = new DecimalField(message, HEADERSIZE + 242,
				12, 0, "ALCPHN");
		fieldnames[17] = "ALCEMP";
		tagnames[17] = "ALCEMP";
		fields[17] = fieldALCEMP = new CharacterField(message,
				HEADERSIZE + 254, 25, "ALCEMP");
		fieldnames[18] = "ALCHDT1";
		tagnames[18] = "ALCHDT1";
		fields[18] = fieldALCHDT1 = new DecimalField(message, HEADERSIZE + 279,
				3, 0, "ALCHDT1");
		fieldnames[19] = "ALCHDT2";
		tagnames[19] = "ALCHDT2";
		fields[19] = fieldALCHDT2 = new DecimalField(message, HEADERSIZE + 282,
				3, 0, "ALCHDT2");
		fieldnames[20] = "ALCHDT3";
		tagnames[20] = "ALCHDT3";
		fields[20] = fieldALCHDT3 = new DecimalField(message, HEADERSIZE + 285,
				5, 0, "ALCHDT3");
		fieldnames[21] = "ALCJBT";
		tagnames[21] = "ALCJBT";
		fields[21] = fieldALCJBT = new CharacterField(message,
				HEADERSIZE + 290, 25, "ALCJBT");
		fieldnames[22] = "ALCBKR";
		tagnames[22] = "ALCBKR";
		fields[22] = fieldALCBKR = new CharacterField(message,
				HEADERSIZE + 315, 1, "ALCBKR");
		fieldnames[23] = "ALCCAC";
		tagnames[23] = "ALCCAC";
		fields[23] = fieldALCCAC = new DecimalField(message, HEADERSIZE + 316,
				13, 0, "ALCCAC");
		fieldnames[24] = "ALCCAD1";
		tagnames[24] = "ALCCAD1";
		fields[24] = fieldALCCAD1 = new CharacterField(message,
				HEADERSIZE + 329, 30, "ALCCAD1");
		fieldnames[25] = "ALCCAD2";
		tagnames[25] = "ALCCAD2";
		fields[25] = fieldALCCAD2 = new CharacterField(message,
				HEADERSIZE + 359, 30, "ALCCAD2");
		fieldnames[26] = "ALCCAD3";
		tagnames[26] = "ALCCAD3";
		fields[26] = fieldALCCAD3 = new CharacterField(message,
				HEADERSIZE + 389, 30, "ALCCAD3");
		fieldnames[27] = "ALCCEML";
		tagnames[27] = "ALCCEML";
		fields[27] = fieldALCCEML = new CharacterField(message,
				HEADERSIZE + 419, 25, "ALCCEML");
		fieldnames[28] = "ALCSSN";
		tagnames[28] = "ALCSSN";
		fields[28] = fieldALCSSN = new DecimalField(message, HEADERSIZE + 444,
				10, 0, "ALCSSN");
		fieldnames[29] = "ALCMMN";
		tagnames[29] = "ALCMMN";
		fields[29] = fieldALCMMN = new CharacterField(message,
				HEADERSIZE + 454, 30, "ALCMMN");
	}

	/**
	 * Get value of field ALCACC as a String.
	 */
	public String getALCACC() {
		return fieldALCACC.getString();
	}

	/**
	 * Get value of field ALCAD1 as a String.
	 */
	public String getALCAD1() {
		return fieldALCAD1.getString();
	}

	/**
	 * Get value of field ALCAD2 as a String.
	 */
	public String getALCAD2() {
		return fieldALCAD2.getString();
	}

	/**
	 * Get value of field ALCAD3 as a String.
	 */
	public String getALCAD3() {
		return fieldALCAD3.getString();
	}

	/**
	 * Get value of field ALCAEML as a String.
	 */
	public String getALCAEML() {
		return fieldALCAEML.getString();
	}

	/**
	 * Get value of field ALCAMT as a String.
	 */
	public String getALCAMT() {
		return fieldALCAMT.getString();
	}

	/**
	 * Get value of field ALCBKR as a String.
	 */
	public String getALCBKR() {
		return fieldALCBKR.getString();
	}

	/**
	 * Get value of field ALCCAC as a String.
	 */
	public String getALCCAC() {
		return fieldALCCAC.getString();
	}

	/**
	 * Get value of field ALCCAD1 as a String.
	 */
	public String getALCCAD1() {
		return fieldALCCAD1.getString();
	}

	/**
	 * Get value of field ALCCAD2 as a String.
	 */
	public String getALCCAD2() {
		return fieldALCCAD2.getString();
	}

	/**
	 * Get value of field ALCCAD3 as a String.
	 */
	public String getALCCAD3() {
		return fieldALCCAD3.getString();
	}

	/**
	 * Get value of field ALCCEML as a String.
	 */
	public String getALCCEML() {
		return fieldALCCEML.getString();
	}

	/**
	 * Get value of field ALCEMP as a String.
	 */
	public String getALCEMP() {
		return fieldALCEMP.getString();
	}

	/**
	 * Get value of field ALCHDT1 as a String.
	 */
	public String getALCHDT1() {
		return fieldALCHDT1.getString();
	}

	/**
	 * Get value of field ALCHDT2 as a String.
	 */
	public String getALCHDT2() {
		return fieldALCHDT2.getString();
	}

	/**
	 * Get value of field ALCHDT3 as a String.
	 */
	public String getALCHDT3() {
		return fieldALCHDT3.getString();
	}

	/**
	 * Get value of field ALCHPN as a String.
	 */
	public String getALCHPN() {
		return fieldALCHPN.getString();
	}

	/**
	 * Get value of field ALCJBT as a String.
	 */
	public String getALCJBT() {
		return fieldALCJBT.getString();
	}

	/**
	 * Get value of field ALCLNP as a String.
	 */
	public String getALCLNP() {
		return fieldALCLNP.getString();
	}

	/**
	 * Get value of field ALCLVY as a String.
	 */
	public String getALCLVY() {
		return fieldALCLVY.getString();
	}

	/**
	 * Get value of field ALCMMN as a String.
	 */
	public String getALCMMN() {
		return fieldALCMMN.getString();
	}

	/**
	 * Get value of field ALCMPY as a String.
	 */
	public String getALCMPY() {
		return fieldALCMPY.getString();
	}

	/**
	 * Get value of field ALCOWP as a String.
	 */
	public String getALCOWP() {
		return fieldALCOWP.getString();
	}

	/**
	 * Get value of field ALCPHN as a String.
	 */
	public String getALCPHN() {
		return fieldALCPHN.getString();
	}

	/**
	 * Get value of field ALCPLN as a String.
	 */
	public String getALCPLN() {
		return fieldALCPLN.getString();
	}

	/**
	 * Get value of field ALCRPY as a String.
	 */
	public String getALCRPY() {
		return fieldALCRPY.getString();
	}

	/**
	 * Get value of field ALCSSN as a String.
	 */
	public String getALCSSN() {
		return fieldALCSSN.getString();
	}

	/**
	 * Get value of field ALCTYP as a String.
	 */
	public String getALCTYP() {
		return fieldALCTYP.getString();
	}

	/**
	 * Get value of field ALCUPY as a String.
	 */
	public String getALCUPY() {
		return fieldALCUPY.getString();
	}

	/**
	 * Get value of field ALCUSER as a String.
	 */
	public String getALCUSER() {
		return fieldALCUSER.getString();
	}

	/**
	 * Return value of numeric field ALCACC as a BigDecimal.
	 */
	public BigDecimal getBigDecimalALCACC() {
		return fieldALCACC.getBigDecimal();
	}

	/**
	 * Return value of numeric field ALCAMT as a BigDecimal.
	 */
	public BigDecimal getBigDecimalALCAMT() {
		return fieldALCAMT.getBigDecimal();
	}

	/**
	 * Return value of numeric field ALCCAC as a BigDecimal.
	 */
	public BigDecimal getBigDecimalALCCAC() {
		return fieldALCCAC.getBigDecimal();
	}

	/**
	 * Return value of numeric field ALCHDT1 as a BigDecimal.
	 */
	public BigDecimal getBigDecimalALCHDT1() {
		return fieldALCHDT1.getBigDecimal();
	}

	/**
	 * Return value of numeric field ALCHDT2 as a BigDecimal.
	 */
	public BigDecimal getBigDecimalALCHDT2() {
		return fieldALCHDT2.getBigDecimal();
	}

	/**
	 * Return value of numeric field ALCHDT3 as a BigDecimal.
	 */
	public BigDecimal getBigDecimalALCHDT3() {
		return fieldALCHDT3.getBigDecimal();
	}

	/**
	 * Return value of numeric field ALCHPN as a BigDecimal.
	 */
	public BigDecimal getBigDecimalALCHPN() {
		return fieldALCHPN.getBigDecimal();
	}

	/**
	 * Return value of numeric field ALCLVY as a BigDecimal.
	 */
	public BigDecimal getBigDecimalALCLVY() {
		return fieldALCLVY.getBigDecimal();
	}

	/**
	 * Return value of numeric field ALCMPY as a BigDecimal.
	 */
	public BigDecimal getBigDecimalALCMPY() {
		return fieldALCMPY.getBigDecimal();
	}

	/**
	 * Return value of numeric field ALCPHN as a BigDecimal.
	 */
	public BigDecimal getBigDecimalALCPHN() {
		return fieldALCPHN.getBigDecimal();
	}

	/**
	 * Return value of numeric field ALCRPY as a BigDecimal.
	 */
	public BigDecimal getBigDecimalALCRPY() {
		return fieldALCRPY.getBigDecimal();
	}

	/**
	 * Return value of numeric field ALCSSN as a BigDecimal.
	 */
	public BigDecimal getBigDecimalALCSSN() {
		return fieldALCSSN.getBigDecimal();
	}

	/**
	 * Return value of numeric field ALCUPY as a BigDecimal.
	 */
	public BigDecimal getBigDecimalALCUPY() {
		return fieldALCUPY.getBigDecimal();
	}

	/**
	 * Set field ALCACC using a String value.
	 */
	public void setALCACC(String newvalue) {
		fieldALCACC.setString(newvalue);
	}

	/**
	 * Set numeric field ALCACC using a BigDecimal value.
	 */
	public void setALCACC(BigDecimal newvalue) {
		fieldALCACC.setBigDecimal(newvalue);
	}

	/**
	 * Set field ALCAD1 using a String value.
	 */
	public void setALCAD1(String newvalue) {
		fieldALCAD1.setString(newvalue);
	}

	/**
	 * Set field ALCAD2 using a String value.
	 */
	public void setALCAD2(String newvalue) {
		fieldALCAD2.setString(newvalue);
	}

	/**
	 * Set field ALCAD3 using a String value.
	 */
	public void setALCAD3(String newvalue) {
		fieldALCAD3.setString(newvalue);
	}

	/**
	 * Set field ALCAEML using a String value.
	 */
	public void setALCAEML(String newvalue) {
		fieldALCAEML.setString(newvalue);
	}

	/**
	 * Set field ALCAMT using a String value.
	 */
	public void setALCAMT(String newvalue) {
		fieldALCAMT.setString(newvalue);
	}

	/**
	 * Set numeric field ALCAMT using a BigDecimal value.
	 */
	public void setALCAMT(BigDecimal newvalue) {
		fieldALCAMT.setBigDecimal(newvalue);
	}

	/**
	 * Set field ALCBKR using a String value.
	 */
	public void setALCBKR(String newvalue) {
		fieldALCBKR.setString(newvalue);
	}

	/**
	 * Set field ALCCAC using a String value.
	 */
	public void setALCCAC(String newvalue) {
		fieldALCCAC.setString(newvalue);
	}

	/**
	 * Set numeric field ALCCAC using a BigDecimal value.
	 */
	public void setALCCAC(BigDecimal newvalue) {
		fieldALCCAC.setBigDecimal(newvalue);
	}

	/**
	 * Set field ALCCAD1 using a String value.
	 */
	public void setALCCAD1(String newvalue) {
		fieldALCCAD1.setString(newvalue);
	}

	/**
	 * Set field ALCCAD2 using a String value.
	 */
	public void setALCCAD2(String newvalue) {
		fieldALCCAD2.setString(newvalue);
	}

	/**
	 * Set field ALCCAD3 using a String value.
	 */
	public void setALCCAD3(String newvalue) {
		fieldALCCAD3.setString(newvalue);
	}

	/**
	 * Set field ALCCEML using a String value.
	 */
	public void setALCCEML(String newvalue) {
		fieldALCCEML.setString(newvalue);
	}

	/**
	 * Set field ALCEMP using a String value.
	 */
	public void setALCEMP(String newvalue) {
		fieldALCEMP.setString(newvalue);
	}

	/**
	 * Set field ALCHDT1 using a String value.
	 */
	public void setALCHDT1(String newvalue) {
		fieldALCHDT1.setString(newvalue);
	}

	/**
	 * Set numeric field ALCHDT1 using a BigDecimal value.
	 */
	public void setALCHDT1(BigDecimal newvalue) {
		fieldALCHDT1.setBigDecimal(newvalue);
	}

	/**
	 * Set field ALCHDT2 using a String value.
	 */
	public void setALCHDT2(String newvalue) {
		fieldALCHDT2.setString(newvalue);
	}

	/**
	 * Set numeric field ALCHDT2 using a BigDecimal value.
	 */
	public void setALCHDT2(BigDecimal newvalue) {
		fieldALCHDT2.setBigDecimal(newvalue);
	}

	/**
	 * Set field ALCHDT3 using a String value.
	 */
	public void setALCHDT3(String newvalue) {
		fieldALCHDT3.setString(newvalue);
	}

	/**
	 * Set numeric field ALCHDT3 using a BigDecimal value.
	 */
	public void setALCHDT3(BigDecimal newvalue) {
		fieldALCHDT3.setBigDecimal(newvalue);
	}

	/**
	 * Set field ALCHPN using a String value.
	 */
	public void setALCHPN(String newvalue) {
		fieldALCHPN.setString(newvalue);
	}

	/**
	 * Set numeric field ALCHPN using a BigDecimal value.
	 */
	public void setALCHPN(BigDecimal newvalue) {
		fieldALCHPN.setBigDecimal(newvalue);
	}

	/**
	 * Set field ALCJBT using a String value.
	 */
	public void setALCJBT(String newvalue) {
		fieldALCJBT.setString(newvalue);
	}

	/**
	 * Set field ALCLNP using a String value.
	 */
	public void setALCLNP(String newvalue) {
		fieldALCLNP.setString(newvalue);
	}

	/**
	 * Set field ALCLVY using a String value.
	 */
	public void setALCLVY(String newvalue) {
		fieldALCLVY.setString(newvalue);
	}

	/**
	 * Set numeric field ALCLVY using a BigDecimal value.
	 */
	public void setALCLVY(BigDecimal newvalue) {
		fieldALCLVY.setBigDecimal(newvalue);
	}

	/**
	 * Set field ALCMMN using a String value.
	 */
	public void setALCMMN(String newvalue) {
		fieldALCMMN.setString(newvalue);
	}

	/**
	 * Set field ALCMPY using a String value.
	 */
	public void setALCMPY(String newvalue) {
		fieldALCMPY.setString(newvalue);
	}

	/**
	 * Set numeric field ALCMPY using a BigDecimal value.
	 */
	public void setALCMPY(BigDecimal newvalue) {
		fieldALCMPY.setBigDecimal(newvalue);
	}

	/**
	 * Set field ALCOWP using a String value.
	 */
	public void setALCOWP(String newvalue) {
		fieldALCOWP.setString(newvalue);
	}

	/**
	 * Set field ALCPHN using a String value.
	 */
	public void setALCPHN(String newvalue) {
		fieldALCPHN.setString(newvalue);
	}

	/**
	 * Set numeric field ALCPHN using a BigDecimal value.
	 */
	public void setALCPHN(BigDecimal newvalue) {
		fieldALCPHN.setBigDecimal(newvalue);
	}

	/**
	 * Set field ALCPLN using a String value.
	 */
	public void setALCPLN(String newvalue) {
		fieldALCPLN.setString(newvalue);
	}

	/**
	 * Set field ALCRPY using a String value.
	 */
	public void setALCRPY(String newvalue) {
		fieldALCRPY.setString(newvalue);
	}

	/**
	 * Set numeric field ALCRPY using a BigDecimal value.
	 */
	public void setALCRPY(BigDecimal newvalue) {
		fieldALCRPY.setBigDecimal(newvalue);
	}

	/**
	 * Set field ALCSSN using a String value.
	 */
	public void setALCSSN(String newvalue) {
		fieldALCSSN.setString(newvalue);
	}

	/**
	 * Set numeric field ALCSSN using a BigDecimal value.
	 */
	public void setALCSSN(BigDecimal newvalue) {
		fieldALCSSN.setBigDecimal(newvalue);
	}

	/**
	 * Set field ALCTYP using a String value.
	 */
	public void setALCTYP(String newvalue) {
		fieldALCTYP.setString(newvalue);
	}

	/**
	 * Set field ALCUPY using a String value.
	 */
	public void setALCUPY(String newvalue) {
		fieldALCUPY.setString(newvalue);
	}

	/**
	 * Set numeric field ALCUPY using a BigDecimal value.
	 */
	public void setALCUPY(BigDecimal newvalue) {
		fieldALCUPY.setBigDecimal(newvalue);
	}

	/**
	 * Set field ALCUSER using a String value.
	 */
	public void setALCUSER(String newvalue) {
		fieldALCUSER.setString(newvalue);
	}
}