/**
 *  This Class was created By Luis Velando
 *  Copyright Datapro Inc. 1999
 **/

package com.afirme.afirmenet.ibs.messages;

import java.math.BigDecimal;

import com.datapro.sockets.CharacterField;
import com.datapro.sockets.DecimalField;
import com.datapro.sockets.MessageField;
import com.datapro.sockets.MessageRecord;

/**
 * Class generated by AS/400 CRTCLASS command from AMDREQDSJV physical file
 * definition.
 * 
 * File level identifier is 1000802211753. Record format level identifier is
 * 4EEC502CE2B2E.
 */

public class AMDREQDSJVMessage extends MessageRecord {
	final int FIELDCOUNT = 88;
	private CharacterField fieldAMDUSER = null;
	private CharacterField fieldAMDREF = null;
	private CharacterField fieldAMDTRF = null;
	private DecimalField fieldAMDLCR = null;
	private DecimalField fieldAMDLAN = null;
	private CharacterField fieldAMDBN1 = null;
	private CharacterField fieldAMDBN2 = null;
	private CharacterField fieldAMDBN3 = null;
	private CharacterField fieldAMDBN4 = null;
	private DecimalField fieldAMDAD1 = null;
	private DecimalField fieldAMDAD2 = null;
	private DecimalField fieldAMDAD3 = null;
	private DecimalField fieldAMDED1 = null;
	private DecimalField fieldAMDED2 = null;
	private DecimalField fieldAMDED3 = null;
	private CharacterField fieldAMDIDA = null;
	private DecimalField fieldAMDAMT = null;
	private DecimalField fieldAMDSD1 = null;
	private DecimalField fieldAMDSD2 = null;
	private DecimalField fieldAMDSD3 = null;
	private CharacterField fieldAMDSHF = null;
	private CharacterField fieldAMDSHT = null;
	private CharacterField fieldAMDAC1 = null;
	private CharacterField fieldAMDAC2 = null;
	private CharacterField fieldAMDAC3 = null;
	private CharacterField fieldAMDAC4 = null;
	private CharacterField fieldLCRNR01 = null;
	private CharacterField fieldLCRNR02 = null;
	private CharacterField fieldLCRNR03 = null;
	private CharacterField fieldLCRNR04 = null;
	private CharacterField fieldLCRNR05 = null;
	private CharacterField fieldLCRNR06 = null;
	private CharacterField fieldLCRNR07 = null;
	private CharacterField fieldLCRNR08 = null;
	private CharacterField fieldLCRNR09 = null;
	private CharacterField fieldLCRNR10 = null;
	private CharacterField fieldLCRNR11 = null;
	private CharacterField fieldLCRNR12 = null;
	private CharacterField fieldLCRNR13 = null;
	private CharacterField fieldLCRNR14 = null;
	private CharacterField fieldLCRNR15 = null;
	private CharacterField fieldLCRNR16 = null;
	private CharacterField fieldLCRNR17 = null;
	private CharacterField fieldLCRNR18 = null;
	private CharacterField fieldLCRNR19 = null;
	private CharacterField fieldLCRNR20 = null;
	private CharacterField fieldLCRNR21 = null;
	private CharacterField fieldLCRNR22 = null;
	private CharacterField fieldLCRNR23 = null;
	private CharacterField fieldLCRNR24 = null;
	private CharacterField fieldLCRNR25 = null;
	private CharacterField fieldLCRNR26 = null;
	private CharacterField fieldLCRNR27 = null;
	private CharacterField fieldLCRNR28 = null;
	private CharacterField fieldLCRNR29 = null;
	private CharacterField fieldLCRNR30 = null;
	private CharacterField fieldLCRNR31 = null;
	private CharacterField fieldLCRNR32 = null;
	private CharacterField fieldLCRNR33 = null;
	private CharacterField fieldLCRNR34 = null;
	private CharacterField fieldLCRNR35 = null;
	private CharacterField fieldLCRNR36 = null;
	private CharacterField fieldLCRNR37 = null;
	private CharacterField fieldLCRNR38 = null;
	private CharacterField fieldLCRNR39 = null;
	private CharacterField fieldLCRNR40 = null;
	private CharacterField fieldLCRNR41 = null;
	private CharacterField fieldLCRNR42 = null;
	private CharacterField fieldLCRNR43 = null;
	private CharacterField fieldLCRNR44 = null;
	private CharacterField fieldLCRNR45 = null;
	private CharacterField fieldLCRNR46 = null;
	private CharacterField fieldLCRNR47 = null;
	private CharacterField fieldLCRNR48 = null;
	private CharacterField fieldLCRNR49 = null;
	private CharacterField fieldLCRNR50 = null;
	private CharacterField fieldLCRSHP1 = null;
	private CharacterField fieldLCRSHP2 = null;
	private CharacterField fieldLCRSHP3 = null;
	private CharacterField fieldLCRSHP4 = null;
	private CharacterField fieldLCRSHP5 = null;
	private CharacterField fieldLCRSHP6 = null;
	private CharacterField fieldLCRSTR1 = null;
	private CharacterField fieldLCRSTR2 = null;
	private CharacterField fieldLCRSTR3 = null;
	private CharacterField fieldLCRSTR4 = null;
	private CharacterField fieldLCRSTR5 = null;
	private CharacterField fieldLCRSTR6 = null;

	/**
	 * Constructor for AMDREQDSJVMessage.
	 */
	public AMDREQDSJVMessage() {
		createFields();
		initialize();
	}

	/**
	 * Create fields for this message. This method implements the abstract
	 * method in the MessageRecord superclass.
	 */
	protected void createFields() {
		recordsize = 2801;
		fileid = "1000802211753";
		recordid = "4EEC502CE2B2E";
		message = new byte[getByteLength()];
		formatname = "AMDREQDSJV";
		fieldnames = new String[FIELDCOUNT];
		tagnames = new String[FIELDCOUNT];
		fields = new MessageField[FIELDCOUNT];

		fieldnames[0] = "AMDUSER";
		tagnames[0] = "AMDUSER";
		fields[0] = fieldAMDUSER = new CharacterField(message, HEADERSIZE + 0,
				10, "AMDUSER");
		fieldnames[1] = "AMDREF";
		tagnames[1] = "AMDREF";
		fields[1] = fieldAMDREF = new CharacterField(message, HEADERSIZE + 10,
				16, "AMDREF");
		fieldnames[2] = "AMDTRF";
		tagnames[2] = "AMDTRF";
		fields[2] = fieldAMDTRF = new CharacterField(message, HEADERSIZE + 26,
				16, "AMDTRF");
		fieldnames[3] = "AMDLCR";
		tagnames[3] = "AMDLCR";
		fields[3] = fieldAMDLCR = new DecimalField(message, HEADERSIZE + 42,
				13, 0, "AMDLCR");
		fieldnames[4] = "AMDLAN";
		tagnames[4] = "AMDLAN";
		fields[4] = fieldAMDLAN = new DecimalField(message, HEADERSIZE + 55, 3,
				0, "AMDLAN");
		fieldnames[5] = "AMDBN1";
		tagnames[5] = "AMDBN1";
		fields[5] = fieldAMDBN1 = new CharacterField(message, HEADERSIZE + 58,
				35, "AMDBN1");
		fieldnames[6] = "AMDBN2";
		tagnames[6] = "AMDBN2";
		fields[6] = fieldAMDBN2 = new CharacterField(message, HEADERSIZE + 93,
				35, "AMDBN2");
		fieldnames[7] = "AMDBN3";
		tagnames[7] = "AMDBN3";
		fields[7] = fieldAMDBN3 = new CharacterField(message, HEADERSIZE + 128,
				35, "AMDBN3");
		fieldnames[8] = "AMDBN4";
		tagnames[8] = "AMDBN4";
		fields[8] = fieldAMDBN4 = new CharacterField(message, HEADERSIZE + 163,
				35, "AMDBN4");
		fieldnames[9] = "AMDAD1";
		tagnames[9] = "AMDAD1";
		fields[9] = fieldAMDAD1 = new DecimalField(message, HEADERSIZE + 198,
				3, 0, "AMDAD1");
		fieldnames[10] = "AMDAD2";
		tagnames[10] = "AMDAD2";
		fields[10] = fieldAMDAD2 = new DecimalField(message, HEADERSIZE + 201,
				3, 0, "AMDAD2");
		fieldnames[11] = "AMDAD3";
		tagnames[11] = "AMDAD3";
		fields[11] = fieldAMDAD3 = new DecimalField(message, HEADERSIZE + 204,
				3, 0, "AMDAD3");
		fieldnames[12] = "AMDED1";
		tagnames[12] = "AMDED1";
		fields[12] = fieldAMDED1 = new DecimalField(message, HEADERSIZE + 207,
				3, 0, "AMDED1");
		fieldnames[13] = "AMDED2";
		tagnames[13] = "AMDED2";
		fields[13] = fieldAMDED2 = new DecimalField(message, HEADERSIZE + 210,
				3, 0, "AMDED2");
		fieldnames[14] = "AMDED3";
		tagnames[14] = "AMDED3";
		fields[14] = fieldAMDED3 = new DecimalField(message, HEADERSIZE + 213,
				3, 0, "AMDED3");
		fieldnames[15] = "AMDIDA";
		tagnames[15] = "AMDIDA";
		fields[15] = fieldAMDIDA = new CharacterField(message,
				HEADERSIZE + 216, 1, "AMDIDA");
		fieldnames[16] = "AMDAMT";
		tagnames[16] = "AMDAMT";
		fields[16] = fieldAMDAMT = new DecimalField(message, HEADERSIZE + 217,
				15, 2, "AMDAMT");
		fieldnames[17] = "AMDSD1";
		tagnames[17] = "AMDSD1";
		fields[17] = fieldAMDSD1 = new DecimalField(message, HEADERSIZE + 232,
				3, 0, "AMDSD1");
		fieldnames[18] = "AMDSD2";
		tagnames[18] = "AMDSD2";
		fields[18] = fieldAMDSD2 = new DecimalField(message, HEADERSIZE + 235,
				3, 0, "AMDSD2");
		fieldnames[19] = "AMDSD3";
		tagnames[19] = "AMDSD3";
		fields[19] = fieldAMDSD3 = new DecimalField(message, HEADERSIZE + 238,
				3, 0, "AMDSD3");
		fieldnames[20] = "AMDSHF";
		tagnames[20] = "AMDSHF";
		fields[20] = fieldAMDSHF = new CharacterField(message,
				HEADERSIZE + 241, 35, "AMDSHF");
		fieldnames[21] = "AMDSHT";
		tagnames[21] = "AMDSHT";
		fields[21] = fieldAMDSHT = new CharacterField(message,
				HEADERSIZE + 276, 35, "AMDSHT");
		fieldnames[22] = "AMDAC1";
		tagnames[22] = "AMDAC1";
		fields[22] = fieldAMDAC1 = new CharacterField(message,
				HEADERSIZE + 311, 35, "AMDAC1");
		fieldnames[23] = "AMDAC2";
		tagnames[23] = "AMDAC2";
		fields[23] = fieldAMDAC2 = new CharacterField(message,
				HEADERSIZE + 346, 35, "AMDAC2");
		fieldnames[24] = "AMDAC3";
		tagnames[24] = "AMDAC3";
		fields[24] = fieldAMDAC3 = new CharacterField(message,
				HEADERSIZE + 381, 35, "AMDAC3");
		fieldnames[25] = "AMDAC4";
		tagnames[25] = "AMDAC4";
		fields[25] = fieldAMDAC4 = new CharacterField(message,
				HEADERSIZE + 416, 35, "AMDAC4");
		fieldnames[26] = "LCRNR01";
		tagnames[26] = "LCRNR01";
		fields[26] = fieldLCRNR01 = new CharacterField(message,
				HEADERSIZE + 451, 35, "LCRNR01");
		fieldnames[27] = "LCRNR02";
		tagnames[27] = "LCRNR02";
		fields[27] = fieldLCRNR02 = new CharacterField(message,
				HEADERSIZE + 486, 35, "LCRNR02");
		fieldnames[28] = "LCRNR03";
		tagnames[28] = "LCRNR03";
		fields[28] = fieldLCRNR03 = new CharacterField(message,
				HEADERSIZE + 521, 35, "LCRNR03");
		fieldnames[29] = "LCRNR04";
		tagnames[29] = "LCRNR04";
		fields[29] = fieldLCRNR04 = new CharacterField(message,
				HEADERSIZE + 556, 35, "LCRNR04");
		fieldnames[30] = "LCRNR05";
		tagnames[30] = "LCRNR05";
		fields[30] = fieldLCRNR05 = new CharacterField(message,
				HEADERSIZE + 591, 35, "LCRNR05");
		fieldnames[31] = "LCRNR06";
		tagnames[31] = "LCRNR06";
		fields[31] = fieldLCRNR06 = new CharacterField(message,
				HEADERSIZE + 626, 35, "LCRNR06");
		fieldnames[32] = "LCRNR07";
		tagnames[32] = "LCRNR07";
		fields[32] = fieldLCRNR07 = new CharacterField(message,
				HEADERSIZE + 661, 35, "LCRNR07");
		fieldnames[33] = "LCRNR08";
		tagnames[33] = "LCRNR08";
		fields[33] = fieldLCRNR08 = new CharacterField(message,
				HEADERSIZE + 696, 35, "LCRNR08");
		fieldnames[34] = "LCRNR09";
		tagnames[34] = "LCRNR09";
		fields[34] = fieldLCRNR09 = new CharacterField(message,
				HEADERSIZE + 731, 35, "LCRNR09");
		fieldnames[35] = "LCRNR10";
		tagnames[35] = "LCRNR10";
		fields[35] = fieldLCRNR10 = new CharacterField(message,
				HEADERSIZE + 766, 35, "LCRNR10");
		fieldnames[36] = "LCRNR11";
		tagnames[36] = "LCRNR11";
		fields[36] = fieldLCRNR11 = new CharacterField(message,
				HEADERSIZE + 801, 35, "LCRNR11");
		fieldnames[37] = "LCRNR12";
		tagnames[37] = "LCRNR12";
		fields[37] = fieldLCRNR12 = new CharacterField(message,
				HEADERSIZE + 836, 35, "LCRNR12");
		fieldnames[38] = "LCRNR13";
		tagnames[38] = "LCRNR13";
		fields[38] = fieldLCRNR13 = new CharacterField(message,
				HEADERSIZE + 871, 35, "LCRNR13");
		fieldnames[39] = "LCRNR14";
		tagnames[39] = "LCRNR14";
		fields[39] = fieldLCRNR14 = new CharacterField(message,
				HEADERSIZE + 906, 35, "LCRNR14");
		fieldnames[40] = "LCRNR15";
		tagnames[40] = "LCRNR15";
		fields[40] = fieldLCRNR15 = new CharacterField(message,
				HEADERSIZE + 941, 35, "LCRNR15");
		fieldnames[41] = "LCRNR16";
		tagnames[41] = "LCRNR16";
		fields[41] = fieldLCRNR16 = new CharacterField(message,
				HEADERSIZE + 976, 35, "LCRNR16");
		fieldnames[42] = "LCRNR17";
		tagnames[42] = "LCRNR17";
		fields[42] = fieldLCRNR17 = new CharacterField(message,
				HEADERSIZE + 1011, 35, "LCRNR17");
		fieldnames[43] = "LCRNR18";
		tagnames[43] = "LCRNR18";
		fields[43] = fieldLCRNR18 = new CharacterField(message,
				HEADERSIZE + 1046, 35, "LCRNR18");
		fieldnames[44] = "LCRNR19";
		tagnames[44] = "LCRNR19";
		fields[44] = fieldLCRNR19 = new CharacterField(message,
				HEADERSIZE + 1081, 35, "LCRNR19");
		fieldnames[45] = "LCRNR20";
		tagnames[45] = "LCRNR20";
		fields[45] = fieldLCRNR20 = new CharacterField(message,
				HEADERSIZE + 1116, 35, "LCRNR20");
		fieldnames[46] = "LCRNR21";
		tagnames[46] = "LCRNR21";
		fields[46] = fieldLCRNR21 = new CharacterField(message,
				HEADERSIZE + 1151, 35, "LCRNR21");
		fieldnames[47] = "LCRNR22";
		tagnames[47] = "LCRNR22";
		fields[47] = fieldLCRNR22 = new CharacterField(message,
				HEADERSIZE + 1186, 35, "LCRNR22");
		fieldnames[48] = "LCRNR23";
		tagnames[48] = "LCRNR23";
		fields[48] = fieldLCRNR23 = new CharacterField(message,
				HEADERSIZE + 1221, 35, "LCRNR23");
		fieldnames[49] = "LCRNR24";
		tagnames[49] = "LCRNR24";
		fields[49] = fieldLCRNR24 = new CharacterField(message,
				HEADERSIZE + 1256, 35, "LCRNR24");
		fieldnames[50] = "LCRNR25";
		tagnames[50] = "LCRNR25";
		fields[50] = fieldLCRNR25 = new CharacterField(message,
				HEADERSIZE + 1291, 35, "LCRNR25");
		fieldnames[51] = "LCRNR26";
		tagnames[51] = "LCRNR26";
		fields[51] = fieldLCRNR26 = new CharacterField(message,
				HEADERSIZE + 1326, 35, "LCRNR26");
		fieldnames[52] = "LCRNR27";
		tagnames[52] = "LCRNR27";
		fields[52] = fieldLCRNR27 = new CharacterField(message,
				HEADERSIZE + 1361, 35, "LCRNR27");
		fieldnames[53] = "LCRNR28";
		tagnames[53] = "LCRNR28";
		fields[53] = fieldLCRNR28 = new CharacterField(message,
				HEADERSIZE + 1396, 35, "LCRNR28");
		fieldnames[54] = "LCRNR29";
		tagnames[54] = "LCRNR29";
		fields[54] = fieldLCRNR29 = new CharacterField(message,
				HEADERSIZE + 1431, 35, "LCRNR29");
		fieldnames[55] = "LCRNR30";
		tagnames[55] = "LCRNR30";
		fields[55] = fieldLCRNR30 = new CharacterField(message,
				HEADERSIZE + 1466, 35, "LCRNR30");
		fieldnames[56] = "LCRNR31";
		tagnames[56] = "LCRNR31";
		fields[56] = fieldLCRNR31 = new CharacterField(message,
				HEADERSIZE + 1501, 35, "LCRNR31");
		fieldnames[57] = "LCRNR32";
		tagnames[57] = "LCRNR32";
		fields[57] = fieldLCRNR32 = new CharacterField(message,
				HEADERSIZE + 1536, 35, "LCRNR32");
		fieldnames[58] = "LCRNR33";
		tagnames[58] = "LCRNR33";
		fields[58] = fieldLCRNR33 = new CharacterField(message,
				HEADERSIZE + 1571, 35, "LCRNR33");
		fieldnames[59] = "LCRNR34";
		tagnames[59] = "LCRNR34";
		fields[59] = fieldLCRNR34 = new CharacterField(message,
				HEADERSIZE + 1606, 35, "LCRNR34");
		fieldnames[60] = "LCRNR35";
		tagnames[60] = "LCRNR35";
		fields[60] = fieldLCRNR35 = new CharacterField(message,
				HEADERSIZE + 1641, 35, "LCRNR35");
		fieldnames[61] = "LCRNR36";
		tagnames[61] = "LCRNR36";
		fields[61] = fieldLCRNR36 = new CharacterField(message,
				HEADERSIZE + 1676, 35, "LCRNR36");
		fieldnames[62] = "LCRNR37";
		tagnames[62] = "LCRNR37";
		fields[62] = fieldLCRNR37 = new CharacterField(message,
				HEADERSIZE + 1711, 35, "LCRNR37");
		fieldnames[63] = "LCRNR38";
		tagnames[63] = "LCRNR38";
		fields[63] = fieldLCRNR38 = new CharacterField(message,
				HEADERSIZE + 1746, 35, "LCRNR38");
		fieldnames[64] = "LCRNR39";
		tagnames[64] = "LCRNR39";
		fields[64] = fieldLCRNR39 = new CharacterField(message,
				HEADERSIZE + 1781, 35, "LCRNR39");
		fieldnames[65] = "LCRNR40";
		tagnames[65] = "LCRNR40";
		fields[65] = fieldLCRNR40 = new CharacterField(message,
				HEADERSIZE + 1816, 35, "LCRNR40");
		fieldnames[66] = "LCRNR41";
		tagnames[66] = "LCRNR41";
		fields[66] = fieldLCRNR41 = new CharacterField(message,
				HEADERSIZE + 1851, 35, "LCRNR41");
		fieldnames[67] = "LCRNR42";
		tagnames[67] = "LCRNR42";
		fields[67] = fieldLCRNR42 = new CharacterField(message,
				HEADERSIZE + 1886, 35, "LCRNR42");
		fieldnames[68] = "LCRNR43";
		tagnames[68] = "LCRNR43";
		fields[68] = fieldLCRNR43 = new CharacterField(message,
				HEADERSIZE + 1921, 35, "LCRNR43");
		fieldnames[69] = "LCRNR44";
		tagnames[69] = "LCRNR44";
		fields[69] = fieldLCRNR44 = new CharacterField(message,
				HEADERSIZE + 1956, 35, "LCRNR44");
		fieldnames[70] = "LCRNR45";
		tagnames[70] = "LCRNR45";
		fields[70] = fieldLCRNR45 = new CharacterField(message,
				HEADERSIZE + 1991, 35, "LCRNR45");
		fieldnames[71] = "LCRNR46";
		tagnames[71] = "LCRNR46";
		fields[71] = fieldLCRNR46 = new CharacterField(message,
				HEADERSIZE + 2026, 35, "LCRNR46");
		fieldnames[72] = "LCRNR47";
		tagnames[72] = "LCRNR47";
		fields[72] = fieldLCRNR47 = new CharacterField(message,
				HEADERSIZE + 2061, 35, "LCRNR47");
		fieldnames[73] = "LCRNR48";
		tagnames[73] = "LCRNR48";
		fields[73] = fieldLCRNR48 = new CharacterField(message,
				HEADERSIZE + 2096, 35, "LCRNR48");
		fieldnames[74] = "LCRNR49";
		tagnames[74] = "LCRNR49";
		fields[74] = fieldLCRNR49 = new CharacterField(message,
				HEADERSIZE + 2131, 35, "LCRNR49");
		fieldnames[75] = "LCRNR50";
		tagnames[75] = "LCRNR50";
		fields[75] = fieldLCRNR50 = new CharacterField(message,
				HEADERSIZE + 2166, 35, "LCRNR50");
		fieldnames[76] = "LCRSHP1";
		tagnames[76] = "LCRSHP1";
		fields[76] = fieldLCRSHP1 = new CharacterField(message,
				HEADERSIZE + 2201, 65, "LCRSHP1");
		fieldnames[77] = "LCRSHP2";
		tagnames[77] = "LCRSHP2";
		fields[77] = fieldLCRSHP2 = new CharacterField(message,
				HEADERSIZE + 2266, 65, "LCRSHP2");
		fieldnames[78] = "LCRSHP3";
		tagnames[78] = "LCRSHP3";
		fields[78] = fieldLCRSHP3 = new CharacterField(message,
				HEADERSIZE + 2331, 65, "LCRSHP3");
		fieldnames[79] = "LCRSHP4";
		tagnames[79] = "LCRSHP4";
		fields[79] = fieldLCRSHP4 = new CharacterField(message,
				HEADERSIZE + 2396, 65, "LCRSHP4");
		fieldnames[80] = "LCRSHP5";
		tagnames[80] = "LCRSHP5";
		fields[80] = fieldLCRSHP5 = new CharacterField(message,
				HEADERSIZE + 2461, 65, "LCRSHP5");
		fieldnames[81] = "LCRSHP6";
		tagnames[81] = "LCRSHP6";
		fields[81] = fieldLCRSHP6 = new CharacterField(message,
				HEADERSIZE + 2526, 65, "LCRSHP6");
		fieldnames[82] = "LCRSTR1";
		tagnames[82] = "LCRSTR1";
		fields[82] = fieldLCRSTR1 = new CharacterField(message,
				HEADERSIZE + 2591, 35, "LCRSTR1");
		fieldnames[83] = "LCRSTR2";
		tagnames[83] = "LCRSTR2";
		fields[83] = fieldLCRSTR2 = new CharacterField(message,
				HEADERSIZE + 2626, 35, "LCRSTR2");
		fieldnames[84] = "LCRSTR3";
		tagnames[84] = "LCRSTR3";
		fields[84] = fieldLCRSTR3 = new CharacterField(message,
				HEADERSIZE + 2661, 35, "LCRSTR3");
		fieldnames[85] = "LCRSTR4";
		tagnames[85] = "LCRSTR4";
		fields[85] = fieldLCRSTR4 = new CharacterField(message,
				HEADERSIZE + 2696, 35, "LCRSTR4");
		fieldnames[86] = "LCRSTR5";
		tagnames[86] = "LCRSTR5";
		fields[86] = fieldLCRSTR5 = new CharacterField(message,
				HEADERSIZE + 2731, 35, "LCRSTR5");
		fieldnames[87] = "LCRSTR6";
		tagnames[87] = "LCRSTR6";
		fields[87] = fieldLCRSTR6 = new CharacterField(message,
				HEADERSIZE + 2766, 35, "LCRSTR6");
	}

	/**
	 * Get value of field AMDAC1 as a String.
	 */
	public String getAMDAC1() {
		return fieldAMDAC1.getString();
	}

	/**
	 * Get value of field AMDAC2 as a String.
	 */
	public String getAMDAC2() {
		return fieldAMDAC2.getString();
	}

	/**
	 * Get value of field AMDAC3 as a String.
	 */
	public String getAMDAC3() {
		return fieldAMDAC3.getString();
	}

	/**
	 * Get value of field AMDAC4 as a String.
	 */
	public String getAMDAC4() {
		return fieldAMDAC4.getString();
	}

	/**
	 * Get value of field AMDAD1 as a String.
	 */
	public String getAMDAD1() {
		return fieldAMDAD1.getString();
	}

	/**
	 * Get value of field AMDAD2 as a String.
	 */
	public String getAMDAD2() {
		return fieldAMDAD2.getString();
	}

	/**
	 * Get value of field AMDAD3 as a String.
	 */
	public String getAMDAD3() {
		return fieldAMDAD3.getString();
	}

	/**
	 * Get value of field AMDAMT as a String.
	 */
	public String getAMDAMT() {
		return fieldAMDAMT.getString();
	}

	/**
	 * Get value of field AMDBN1 as a String.
	 */
	public String getAMDBN1() {
		return fieldAMDBN1.getString();
	}

	/**
	 * Get value of field AMDBN2 as a String.
	 */
	public String getAMDBN2() {
		return fieldAMDBN2.getString();
	}

	/**
	 * Get value of field AMDBN3 as a String.
	 */
	public String getAMDBN3() {
		return fieldAMDBN3.getString();
	}

	/**
	 * Get value of field AMDBN4 as a String.
	 */
	public String getAMDBN4() {
		return fieldAMDBN4.getString();
	}

	/**
	 * Get value of field AMDED1 as a String.
	 */
	public String getAMDED1() {
		return fieldAMDED1.getString();
	}

	/**
	 * Get value of field AMDED2 as a String.
	 */
	public String getAMDED2() {
		return fieldAMDED2.getString();
	}

	/**
	 * Get value of field AMDED3 as a String.
	 */
	public String getAMDED3() {
		return fieldAMDED3.getString();
	}

	/**
	 * Get value of field AMDIDA as a String.
	 */
	public String getAMDIDA() {
		return fieldAMDIDA.getString();
	}

	/**
	 * Get value of field AMDLAN as a String.
	 */
	public String getAMDLAN() {
		return fieldAMDLAN.getString();
	}

	/**
	 * Get value of field AMDLCR as a String.
	 */
	public String getAMDLCR() {
		return fieldAMDLCR.getString();
	}

	/**
	 * Get value of field AMDREF as a String.
	 */
	public String getAMDREF() {
		return fieldAMDREF.getString();
	}

	/**
	 * Get value of field AMDSD1 as a String.
	 */
	public String getAMDSD1() {
		return fieldAMDSD1.getString();
	}

	/**
	 * Get value of field AMDSD2 as a String.
	 */
	public String getAMDSD2() {
		return fieldAMDSD2.getString();
	}

	/**
	 * Get value of field AMDSD3 as a String.
	 */
	public String getAMDSD3() {
		return fieldAMDSD3.getString();
	}

	/**
	 * Get value of field AMDSHF as a String.
	 */
	public String getAMDSHF() {
		return fieldAMDSHF.getString();
	}

	/**
	 * Get value of field AMDSHT as a String.
	 */
	public String getAMDSHT() {
		return fieldAMDSHT.getString();
	}

	/**
	 * Get value of field AMDTRF as a String.
	 */
	public String getAMDTRF() {
		return fieldAMDTRF.getString();
	}

	/**
	 * Get value of field AMDUSER as a String.
	 */
	public String getAMDUSER() {
		return fieldAMDUSER.getString();
	}

	/**
	 * Return value of numeric field AMDAD1 as a BigDecimal.
	 */
	public BigDecimal getBigDecimalAMDAD1() {
		return fieldAMDAD1.getBigDecimal();
	}

	/**
	 * Return value of numeric field AMDAD2 as a BigDecimal.
	 */
	public BigDecimal getBigDecimalAMDAD2() {
		return fieldAMDAD2.getBigDecimal();
	}

	/**
	 * Return value of numeric field AMDAD3 as a BigDecimal.
	 */
	public BigDecimal getBigDecimalAMDAD3() {
		return fieldAMDAD3.getBigDecimal();
	}

	/**
	 * Return value of numeric field AMDAMT as a BigDecimal.
	 */
	public BigDecimal getBigDecimalAMDAMT() {
		return fieldAMDAMT.getBigDecimal();
	}

	/**
	 * Return value of numeric field AMDED1 as a BigDecimal.
	 */
	public BigDecimal getBigDecimalAMDED1() {
		return fieldAMDED1.getBigDecimal();
	}

	/**
	 * Return value of numeric field AMDED2 as a BigDecimal.
	 */
	public BigDecimal getBigDecimalAMDED2() {
		return fieldAMDED2.getBigDecimal();
	}

	/**
	 * Return value of numeric field AMDED3 as a BigDecimal.
	 */
	public BigDecimal getBigDecimalAMDED3() {
		return fieldAMDED3.getBigDecimal();
	}

	/**
	 * Return value of numeric field AMDLAN as a BigDecimal.
	 */
	public BigDecimal getBigDecimalAMDLAN() {
		return fieldAMDLAN.getBigDecimal();
	}

	/**
	 * Return value of numeric field AMDLCR as a BigDecimal.
	 */
	public BigDecimal getBigDecimalAMDLCR() {
		return fieldAMDLCR.getBigDecimal();
	}

	/**
	 * Return value of numeric field AMDSD1 as a BigDecimal.
	 */
	public BigDecimal getBigDecimalAMDSD1() {
		return fieldAMDSD1.getBigDecimal();
	}

	/**
	 * Return value of numeric field AMDSD2 as a BigDecimal.
	 */
	public BigDecimal getBigDecimalAMDSD2() {
		return fieldAMDSD2.getBigDecimal();
	}

	/**
	 * Return value of numeric field AMDSD3 as a BigDecimal.
	 */
	public BigDecimal getBigDecimalAMDSD3() {
		return fieldAMDSD3.getBigDecimal();
	}

	/**
	 * Get value of field LCRNR01 as a String.
	 */
	public String getLCRNR01() {
		return fieldLCRNR01.getString();
	}

	/**
	 * Get value of field LCRNR02 as a String.
	 */
	public String getLCRNR02() {
		return fieldLCRNR02.getString();
	}

	/**
	 * Get value of field LCRNR03 as a String.
	 */
	public String getLCRNR03() {
		return fieldLCRNR03.getString();
	}

	/**
	 * Get value of field LCRNR04 as a String.
	 */
	public String getLCRNR04() {
		return fieldLCRNR04.getString();
	}

	/**
	 * Get value of field LCRNR05 as a String.
	 */
	public String getLCRNR05() {
		return fieldLCRNR05.getString();
	}

	/**
	 * Get value of field LCRNR06 as a String.
	 */
	public String getLCRNR06() {
		return fieldLCRNR06.getString();
	}

	/**
	 * Get value of field LCRNR07 as a String.
	 */
	public String getLCRNR07() {
		return fieldLCRNR07.getString();
	}

	/**
	 * Get value of field LCRNR08 as a String.
	 */
	public String getLCRNR08() {
		return fieldLCRNR08.getString();
	}

	/**
	 * Get value of field LCRNR09 as a String.
	 */
	public String getLCRNR09() {
		return fieldLCRNR09.getString();
	}

	/**
	 * Get value of field LCRNR10 as a String.
	 */
	public String getLCRNR10() {
		return fieldLCRNR10.getString();
	}

	/**
	 * Get value of field LCRNR11 as a String.
	 */
	public String getLCRNR11() {
		return fieldLCRNR11.getString();
	}

	/**
	 * Get value of field LCRNR12 as a String.
	 */
	public String getLCRNR12() {
		return fieldLCRNR12.getString();
	}

	/**
	 * Get value of field LCRNR13 as a String.
	 */
	public String getLCRNR13() {
		return fieldLCRNR13.getString();
	}

	/**
	 * Get value of field LCRNR14 as a String.
	 */
	public String getLCRNR14() {
		return fieldLCRNR14.getString();
	}

	/**
	 * Get value of field LCRNR15 as a String.
	 */
	public String getLCRNR15() {
		return fieldLCRNR15.getString();
	}

	/**
	 * Get value of field LCRNR16 as a String.
	 */
	public String getLCRNR16() {
		return fieldLCRNR16.getString();
	}

	/**
	 * Get value of field LCRNR17 as a String.
	 */
	public String getLCRNR17() {
		return fieldLCRNR17.getString();
	}

	/**
	 * Get value of field LCRNR18 as a String.
	 */
	public String getLCRNR18() {
		return fieldLCRNR18.getString();
	}

	/**
	 * Get value of field LCRNR19 as a String.
	 */
	public String getLCRNR19() {
		return fieldLCRNR19.getString();
	}

	/**
	 * Get value of field LCRNR20 as a String.
	 */
	public String getLCRNR20() {
		return fieldLCRNR20.getString();
	}

	/**
	 * Get value of field LCRNR21 as a String.
	 */
	public String getLCRNR21() {
		return fieldLCRNR21.getString();
	}

	/**
	 * Get value of field LCRNR22 as a String.
	 */
	public String getLCRNR22() {
		return fieldLCRNR22.getString();
	}

	/**
	 * Get value of field LCRNR23 as a String.
	 */
	public String getLCRNR23() {
		return fieldLCRNR23.getString();
	}

	/**
	 * Get value of field LCRNR24 as a String.
	 */
	public String getLCRNR24() {
		return fieldLCRNR24.getString();
	}

	/**
	 * Get value of field LCRNR25 as a String.
	 */
	public String getLCRNR25() {
		return fieldLCRNR25.getString();
	}

	/**
	 * Get value of field LCRNR26 as a String.
	 */
	public String getLCRNR26() {
		return fieldLCRNR26.getString();
	}

	/**
	 * Get value of field LCRNR27 as a String.
	 */
	public String getLCRNR27() {
		return fieldLCRNR27.getString();
	}

	/**
	 * Get value of field LCRNR28 as a String.
	 */
	public String getLCRNR28() {
		return fieldLCRNR28.getString();
	}

	/**
	 * Get value of field LCRNR29 as a String.
	 */
	public String getLCRNR29() {
		return fieldLCRNR29.getString();
	}

	/**
	 * Get value of field LCRNR30 as a String.
	 */
	public String getLCRNR30() {
		return fieldLCRNR30.getString();
	}

	/**
	 * Get value of field LCRNR31 as a String.
	 */
	public String getLCRNR31() {
		return fieldLCRNR31.getString();
	}

	/**
	 * Get value of field LCRNR32 as a String.
	 */
	public String getLCRNR32() {
		return fieldLCRNR32.getString();
	}

	/**
	 * Get value of field LCRNR33 as a String.
	 */
	public String getLCRNR33() {
		return fieldLCRNR33.getString();
	}

	/**
	 * Get value of field LCRNR34 as a String.
	 */
	public String getLCRNR34() {
		return fieldLCRNR34.getString();
	}

	/**
	 * Get value of field LCRNR35 as a String.
	 */
	public String getLCRNR35() {
		return fieldLCRNR35.getString();
	}

	/**
	 * Get value of field LCRNR36 as a String.
	 */
	public String getLCRNR36() {
		return fieldLCRNR36.getString();
	}

	/**
	 * Get value of field LCRNR37 as a String.
	 */
	public String getLCRNR37() {
		return fieldLCRNR37.getString();
	}

	/**
	 * Get value of field LCRNR38 as a String.
	 */
	public String getLCRNR38() {
		return fieldLCRNR38.getString();
	}

	/**
	 * Get value of field LCRNR39 as a String.
	 */
	public String getLCRNR39() {
		return fieldLCRNR39.getString();
	}

	/**
	 * Get value of field LCRNR40 as a String.
	 */
	public String getLCRNR40() {
		return fieldLCRNR40.getString();
	}

	/**
	 * Get value of field LCRNR41 as a String.
	 */
	public String getLCRNR41() {
		return fieldLCRNR41.getString();
	}

	/**
	 * Get value of field LCRNR42 as a String.
	 */
	public String getLCRNR42() {
		return fieldLCRNR42.getString();
	}

	/**
	 * Get value of field LCRNR43 as a String.
	 */
	public String getLCRNR43() {
		return fieldLCRNR43.getString();
	}

	/**
	 * Get value of field LCRNR44 as a String.
	 */
	public String getLCRNR44() {
		return fieldLCRNR44.getString();
	}

	/**
	 * Get value of field LCRNR45 as a String.
	 */
	public String getLCRNR45() {
		return fieldLCRNR45.getString();
	}

	/**
	 * Get value of field LCRNR46 as a String.
	 */
	public String getLCRNR46() {
		return fieldLCRNR46.getString();
	}

	/**
	 * Get value of field LCRNR47 as a String.
	 */
	public String getLCRNR47() {
		return fieldLCRNR47.getString();
	}

	/**
	 * Get value of field LCRNR48 as a String.
	 */
	public String getLCRNR48() {
		return fieldLCRNR48.getString();
	}

	/**
	 * Get value of field LCRNR49 as a String.
	 */
	public String getLCRNR49() {
		return fieldLCRNR49.getString();
	}

	/**
	 * Get value of field LCRNR50 as a String.
	 */
	public String getLCRNR50() {
		return fieldLCRNR50.getString();
	}

	/**
	 * Get value of field LCRSHP1 as a String.
	 */
	public String getLCRSHP1() {
		return fieldLCRSHP1.getString();
	}

	/**
	 * Get value of field LCRSHP2 as a String.
	 */
	public String getLCRSHP2() {
		return fieldLCRSHP2.getString();
	}

	/**
	 * Get value of field LCRSHP3 as a String.
	 */
	public String getLCRSHP3() {
		return fieldLCRSHP3.getString();
	}

	/**
	 * Get value of field LCRSHP4 as a String.
	 */
	public String getLCRSHP4() {
		return fieldLCRSHP4.getString();
	}

	/**
	 * Get value of field LCRSHP5 as a String.
	 */
	public String getLCRSHP5() {
		return fieldLCRSHP5.getString();
	}

	/**
	 * Get value of field LCRSHP6 as a String.
	 */
	public String getLCRSHP6() {
		return fieldLCRSHP6.getString();
	}

	/**
	 * Get value of field LCRSTR1 as a String.
	 */
	public String getLCRSTR1() {
		return fieldLCRSTR1.getString();
	}

	/**
	 * Get value of field LCRSTR2 as a String.
	 */
	public String getLCRSTR2() {
		return fieldLCRSTR2.getString();
	}

	/**
	 * Get value of field LCRSTR3 as a String.
	 */
	public String getLCRSTR3() {
		return fieldLCRSTR3.getString();
	}

	/**
	 * Get value of field LCRSTR4 as a String.
	 */
	public String getLCRSTR4() {
		return fieldLCRSTR4.getString();
	}

	/**
	 * Get value of field LCRSTR5 as a String.
	 */
	public String getLCRSTR5() {
		return fieldLCRSTR5.getString();
	}

	/**
	 * Get value of field LCRSTR6 as a String.
	 */
	public String getLCRSTR6() {
		return fieldLCRSTR6.getString();
	}

	/**
	 * Set field AMDAC1 using a String value.
	 */
	public void setAMDAC1(String newvalue) {
		fieldAMDAC1.setString(newvalue);
	}

	/**
	 * Set field AMDAC2 using a String value.
	 */
	public void setAMDAC2(String newvalue) {
		fieldAMDAC2.setString(newvalue);
	}

	/**
	 * Set field AMDAC3 using a String value.
	 */
	public void setAMDAC3(String newvalue) {
		fieldAMDAC3.setString(newvalue);
	}

	/**
	 * Set field AMDAC4 using a String value.
	 */
	public void setAMDAC4(String newvalue) {
		fieldAMDAC4.setString(newvalue);
	}

	/**
	 * Set field AMDAD1 using a String value.
	 */
	public void setAMDAD1(String newvalue) {
		fieldAMDAD1.setString(newvalue);
	}

	/**
	 * Set numeric field AMDAD1 using a BigDecimal value.
	 */
	public void setAMDAD1(BigDecimal newvalue) {
		fieldAMDAD1.setBigDecimal(newvalue);
	}

	/**
	 * Set field AMDAD2 using a String value.
	 */
	public void setAMDAD2(String newvalue) {
		fieldAMDAD2.setString(newvalue);
	}

	/**
	 * Set numeric field AMDAD2 using a BigDecimal value.
	 */
	public void setAMDAD2(BigDecimal newvalue) {
		fieldAMDAD2.setBigDecimal(newvalue);
	}

	/**
	 * Set field AMDAD3 using a String value.
	 */
	public void setAMDAD3(String newvalue) {
		fieldAMDAD3.setString(newvalue);
	}

	/**
	 * Set numeric field AMDAD3 using a BigDecimal value.
	 */
	public void setAMDAD3(BigDecimal newvalue) {
		fieldAMDAD3.setBigDecimal(newvalue);
	}

	/**
	 * Set field AMDAMT using a String value.
	 */
	public void setAMDAMT(String newvalue) {
		fieldAMDAMT.setString(newvalue);
	}

	/**
	 * Set numeric field AMDAMT using a BigDecimal value.
	 */
	public void setAMDAMT(BigDecimal newvalue) {
		fieldAMDAMT.setBigDecimal(newvalue);
	}

	/**
	 * Set field AMDBN1 using a String value.
	 */
	public void setAMDBN1(String newvalue) {
		fieldAMDBN1.setString(newvalue);
	}

	/**
	 * Set field AMDBN2 using a String value.
	 */
	public void setAMDBN2(String newvalue) {
		fieldAMDBN2.setString(newvalue);
	}

	/**
	 * Set field AMDBN3 using a String value.
	 */
	public void setAMDBN3(String newvalue) {
		fieldAMDBN3.setString(newvalue);
	}

	/**
	 * Set field AMDBN4 using a String value.
	 */
	public void setAMDBN4(String newvalue) {
		fieldAMDBN4.setString(newvalue);
	}

	/**
	 * Set field AMDED1 using a String value.
	 */
	public void setAMDED1(String newvalue) {
		fieldAMDED1.setString(newvalue);
	}

	/**
	 * Set numeric field AMDED1 using a BigDecimal value.
	 */
	public void setAMDED1(BigDecimal newvalue) {
		fieldAMDED1.setBigDecimal(newvalue);
	}

	/**
	 * Set field AMDED2 using a String value.
	 */
	public void setAMDED2(String newvalue) {
		fieldAMDED2.setString(newvalue);
	}

	/**
	 * Set numeric field AMDED2 using a BigDecimal value.
	 */
	public void setAMDED2(BigDecimal newvalue) {
		fieldAMDED2.setBigDecimal(newvalue);
	}

	/**
	 * Set field AMDED3 using a String value.
	 */
	public void setAMDED3(String newvalue) {
		fieldAMDED3.setString(newvalue);
	}

	/**
	 * Set numeric field AMDED3 using a BigDecimal value.
	 */
	public void setAMDED3(BigDecimal newvalue) {
		fieldAMDED3.setBigDecimal(newvalue);
	}

	/**
	 * Set field AMDIDA using a String value.
	 */
	public void setAMDIDA(String newvalue) {
		fieldAMDIDA.setString(newvalue);
	}

	/**
	 * Set field AMDLAN using a String value.
	 */
	public void setAMDLAN(String newvalue) {
		fieldAMDLAN.setString(newvalue);
	}

	/**
	 * Set numeric field AMDLAN using a BigDecimal value.
	 */
	public void setAMDLAN(BigDecimal newvalue) {
		fieldAMDLAN.setBigDecimal(newvalue);
	}

	/**
	 * Set field AMDLCR using a String value.
	 */
	public void setAMDLCR(String newvalue) {
		fieldAMDLCR.setString(newvalue);
	}

	/**
	 * Set numeric field AMDLCR using a BigDecimal value.
	 */
	public void setAMDLCR(BigDecimal newvalue) {
		fieldAMDLCR.setBigDecimal(newvalue);
	}

	/**
	 * Set field AMDREF using a String value.
	 */
	public void setAMDREF(String newvalue) {
		fieldAMDREF.setString(newvalue);
	}

	/**
	 * Set field AMDSD1 using a String value.
	 */
	public void setAMDSD1(String newvalue) {
		fieldAMDSD1.setString(newvalue);
	}

	/**
	 * Set numeric field AMDSD1 using a BigDecimal value.
	 */
	public void setAMDSD1(BigDecimal newvalue) {
		fieldAMDSD1.setBigDecimal(newvalue);
	}

	/**
	 * Set field AMDSD2 using a String value.
	 */
	public void setAMDSD2(String newvalue) {
		fieldAMDSD2.setString(newvalue);
	}

	/**
	 * Set numeric field AMDSD2 using a BigDecimal value.
	 */
	public void setAMDSD2(BigDecimal newvalue) {
		fieldAMDSD2.setBigDecimal(newvalue);
	}

	/**
	 * Set field AMDSD3 using a String value.
	 */
	public void setAMDSD3(String newvalue) {
		fieldAMDSD3.setString(newvalue);
	}

	/**
	 * Set numeric field AMDSD3 using a BigDecimal value.
	 */
	public void setAMDSD3(BigDecimal newvalue) {
		fieldAMDSD3.setBigDecimal(newvalue);
	}

	/**
	 * Set field AMDSHF using a String value.
	 */
	public void setAMDSHF(String newvalue) {
		fieldAMDSHF.setString(newvalue);
	}

	/**
	 * Set field AMDSHT using a String value.
	 */
	public void setAMDSHT(String newvalue) {
		fieldAMDSHT.setString(newvalue);
	}

	/**
	 * Set field AMDTRF using a String value.
	 */
	public void setAMDTRF(String newvalue) {
		fieldAMDTRF.setString(newvalue);
	}

	/**
	 * Set field AMDUSER using a String value.
	 */
	public void setAMDUSER(String newvalue) {
		fieldAMDUSER.setString(newvalue);
	}

	/**
	 * Set field LCRNR01 using a String value.
	 */
	public void setLCRNR01(String newvalue) {
		fieldLCRNR01.setString(newvalue);
	}

	/**
	 * Set field LCRNR02 using a String value.
	 */
	public void setLCRNR02(String newvalue) {
		fieldLCRNR02.setString(newvalue);
	}

	/**
	 * Set field LCRNR03 using a String value.
	 */
	public void setLCRNR03(String newvalue) {
		fieldLCRNR03.setString(newvalue);
	}

	/**
	 * Set field LCRNR04 using a String value.
	 */
	public void setLCRNR04(String newvalue) {
		fieldLCRNR04.setString(newvalue);
	}

	/**
	 * Set field LCRNR05 using a String value.
	 */
	public void setLCRNR05(String newvalue) {
		fieldLCRNR05.setString(newvalue);
	}

	/**
	 * Set field LCRNR06 using a String value.
	 */
	public void setLCRNR06(String newvalue) {
		fieldLCRNR06.setString(newvalue);
	}

	/**
	 * Set field LCRNR07 using a String value.
	 */
	public void setLCRNR07(String newvalue) {
		fieldLCRNR07.setString(newvalue);
	}

	/**
	 * Set field LCRNR08 using a String value.
	 */
	public void setLCRNR08(String newvalue) {
		fieldLCRNR08.setString(newvalue);
	}

	/**
	 * Set field LCRNR09 using a String value.
	 */
	public void setLCRNR09(String newvalue) {
		fieldLCRNR09.setString(newvalue);
	}

	/**
	 * Set field LCRNR10 using a String value.
	 */
	public void setLCRNR10(String newvalue) {
		fieldLCRNR10.setString(newvalue);
	}

	/**
	 * Set field LCRNR11 using a String value.
	 */
	public void setLCRNR11(String newvalue) {
		fieldLCRNR11.setString(newvalue);
	}

	/**
	 * Set field LCRNR12 using a String value.
	 */
	public void setLCRNR12(String newvalue) {
		fieldLCRNR12.setString(newvalue);
	}

	/**
	 * Set field LCRNR13 using a String value.
	 */
	public void setLCRNR13(String newvalue) {
		fieldLCRNR13.setString(newvalue);
	}

	/**
	 * Set field LCRNR14 using a String value.
	 */
	public void setLCRNR14(String newvalue) {
		fieldLCRNR14.setString(newvalue);
	}

	/**
	 * Set field LCRNR15 using a String value.
	 */
	public void setLCRNR15(String newvalue) {
		fieldLCRNR15.setString(newvalue);
	}

	/**
	 * Set field LCRNR16 using a String value.
	 */
	public void setLCRNR16(String newvalue) {
		fieldLCRNR16.setString(newvalue);
	}

	/**
	 * Set field LCRNR17 using a String value.
	 */
	public void setLCRNR17(String newvalue) {
		fieldLCRNR17.setString(newvalue);
	}

	/**
	 * Set field LCRNR18 using a String value.
	 */
	public void setLCRNR18(String newvalue) {
		fieldLCRNR18.setString(newvalue);
	}

	/**
	 * Set field LCRNR19 using a String value.
	 */
	public void setLCRNR19(String newvalue) {
		fieldLCRNR19.setString(newvalue);
	}

	/**
	 * Set field LCRNR20 using a String value.
	 */
	public void setLCRNR20(String newvalue) {
		fieldLCRNR20.setString(newvalue);
	}

	/**
	 * Set field LCRNR21 using a String value.
	 */
	public void setLCRNR21(String newvalue) {
		fieldLCRNR21.setString(newvalue);
	}

	/**
	 * Set field LCRNR22 using a String value.
	 */
	public void setLCRNR22(String newvalue) {
		fieldLCRNR22.setString(newvalue);
	}

	/**
	 * Set field LCRNR23 using a String value.
	 */
	public void setLCRNR23(String newvalue) {
		fieldLCRNR23.setString(newvalue);
	}

	/**
	 * Set field LCRNR24 using a String value.
	 */
	public void setLCRNR24(String newvalue) {
		fieldLCRNR24.setString(newvalue);
	}

	/**
	 * Set field LCRNR25 using a String value.
	 */
	public void setLCRNR25(String newvalue) {
		fieldLCRNR25.setString(newvalue);
	}

	/**
	 * Set field LCRNR26 using a String value.
	 */
	public void setLCRNR26(String newvalue) {
		fieldLCRNR26.setString(newvalue);
	}

	/**
	 * Set field LCRNR27 using a String value.
	 */
	public void setLCRNR27(String newvalue) {
		fieldLCRNR27.setString(newvalue);
	}

	/**
	 * Set field LCRNR28 using a String value.
	 */
	public void setLCRNR28(String newvalue) {
		fieldLCRNR28.setString(newvalue);
	}

	/**
	 * Set field LCRNR29 using a String value.
	 */
	public void setLCRNR29(String newvalue) {
		fieldLCRNR29.setString(newvalue);
	}

	/**
	 * Set field LCRNR30 using a String value.
	 */
	public void setLCRNR30(String newvalue) {
		fieldLCRNR30.setString(newvalue);
	}

	/**
	 * Set field LCRNR31 using a String value.
	 */
	public void setLCRNR31(String newvalue) {
		fieldLCRNR31.setString(newvalue);
	}

	/**
	 * Set field LCRNR32 using a String value.
	 */
	public void setLCRNR32(String newvalue) {
		fieldLCRNR32.setString(newvalue);
	}

	/**
	 * Set field LCRNR33 using a String value.
	 */
	public void setLCRNR33(String newvalue) {
		fieldLCRNR33.setString(newvalue);
	}

	/**
	 * Set field LCRNR34 using a String value.
	 */
	public void setLCRNR34(String newvalue) {
		fieldLCRNR34.setString(newvalue);
	}

	/**
	 * Set field LCRNR35 using a String value.
	 */
	public void setLCRNR35(String newvalue) {
		fieldLCRNR35.setString(newvalue);
	}

	/**
	 * Set field LCRNR36 using a String value.
	 */
	public void setLCRNR36(String newvalue) {
		fieldLCRNR36.setString(newvalue);
	}

	/**
	 * Set field LCRNR37 using a String value.
	 */
	public void setLCRNR37(String newvalue) {
		fieldLCRNR37.setString(newvalue);
	}

	/**
	 * Set field LCRNR38 using a String value.
	 */
	public void setLCRNR38(String newvalue) {
		fieldLCRNR38.setString(newvalue);
	}

	/**
	 * Set field LCRNR39 using a String value.
	 */
	public void setLCRNR39(String newvalue) {
		fieldLCRNR39.setString(newvalue);
	}

	/**
	 * Set field LCRNR40 using a String value.
	 */
	public void setLCRNR40(String newvalue) {
		fieldLCRNR40.setString(newvalue);
	}

	/**
	 * Set field LCRNR41 using a String value.
	 */
	public void setLCRNR41(String newvalue) {
		fieldLCRNR41.setString(newvalue);
	}

	/**
	 * Set field LCRNR42 using a String value.
	 */
	public void setLCRNR42(String newvalue) {
		fieldLCRNR42.setString(newvalue);
	}

	/**
	 * Set field LCRNR43 using a String value.
	 */
	public void setLCRNR43(String newvalue) {
		fieldLCRNR43.setString(newvalue);
	}

	/**
	 * Set field LCRNR44 using a String value.
	 */
	public void setLCRNR44(String newvalue) {
		fieldLCRNR44.setString(newvalue);
	}

	/**
	 * Set field LCRNR45 using a String value.
	 */
	public void setLCRNR45(String newvalue) {
		fieldLCRNR45.setString(newvalue);
	}

	/**
	 * Set field LCRNR46 using a String value.
	 */
	public void setLCRNR46(String newvalue) {
		fieldLCRNR46.setString(newvalue);
	}

	/**
	 * Set field LCRNR47 using a String value.
	 */
	public void setLCRNR47(String newvalue) {
		fieldLCRNR47.setString(newvalue);
	}

	/**
	 * Set field LCRNR48 using a String value.
	 */
	public void setLCRNR48(String newvalue) {
		fieldLCRNR48.setString(newvalue);
	}

	/**
	 * Set field LCRNR49 using a String value.
	 */
	public void setLCRNR49(String newvalue) {
		fieldLCRNR49.setString(newvalue);
	}

	/**
	 * Set field LCRNR50 using a String value.
	 */
	public void setLCRNR50(String newvalue) {
		fieldLCRNR50.setString(newvalue);
	}

	/**
	 * Set field LCRSHP1 using a String value.
	 */
	public void setLCRSHP1(String newvalue) {
		fieldLCRSHP1.setString(newvalue);
	}

	/**
	 * Set field LCRSHP2 using a String value.
	 */
	public void setLCRSHP2(String newvalue) {
		fieldLCRSHP2.setString(newvalue);
	}

	/**
	 * Set field LCRSHP3 using a String value.
	 */
	public void setLCRSHP3(String newvalue) {
		fieldLCRSHP3.setString(newvalue);
	}

	/**
	 * Set field LCRSHP4 using a String value.
	 */
	public void setLCRSHP4(String newvalue) {
		fieldLCRSHP4.setString(newvalue);
	}

	/**
	 * Set field LCRSHP5 using a String value.
	 */
	public void setLCRSHP5(String newvalue) {
		fieldLCRSHP5.setString(newvalue);
	}

	/**
	 * Set field LCRSHP6 using a String value.
	 */
	public void setLCRSHP6(String newvalue) {
		fieldLCRSHP6.setString(newvalue);
	}

	/**
	 * Set field LCRSTR1 using a String value.
	 */
	public void setLCRSTR1(String newvalue) {
		fieldLCRSTR1.setString(newvalue);
	}

	/**
	 * Set field LCRSTR2 using a String value.
	 */
	public void setLCRSTR2(String newvalue) {
		fieldLCRSTR2.setString(newvalue);
	}

	/**
	 * Set field LCRSTR3 using a String value.
	 */
	public void setLCRSTR3(String newvalue) {
		fieldLCRSTR3.setString(newvalue);
	}

	/**
	 * Set field LCRSTR4 using a String value.
	 */
	public void setLCRSTR4(String newvalue) {
		fieldLCRSTR4.setString(newvalue);
	}

	/**
	 * Set field LCRSTR5 using a String value.
	 */
	public void setLCRSTR5(String newvalue) {
		fieldLCRSTR5.setString(newvalue);
	}

	/**
	 * Set field LCRSTR6 using a String value.
	 */
	public void setLCRSTR6(String newvalue) {
		fieldLCRSTR6.setString(newvalue);
	}
}