package com.afirme.afirmenet.ibs.messages;

import java.math.BigDecimal;

import com.datapro.sockets.CharacterField;
import com.datapro.sockets.DecimalField;
import com.datapro.sockets.MessageField;
import com.datapro.sockets.MessageRecord;

/**
 * Class generated by AS/400 CRTCLASS command from CLTDSJV physical file
 * definition.
 * 
 * File level identifier is 1000802211800. Record format level identifier is
 * 30345E25DDDAA.
 */

public class CLTDSJVMessage extends MessageRecord {
	final int FIELDCOUNT = 39;
	private CharacterField fieldCLTUSER = null;
	private CharacterField fieldCLTFLG = null;
	private DecimalField fieldCLTDCMACC = null;
	private CharacterField fieldCLTDCMCCY = null;
	private CharacterField fieldCLTDCMTYP = null;
	private CharacterField fieldCLTDCMSTY = null;
	private CharacterField fieldCLTDCMSTS = null;
	private CharacterField fieldCLTDCMRDF = null;
	private DecimalField fieldCLTDCMOAM = null;
	private DecimalField fieldCLTDCMAMN = null;
	private DecimalField fieldCLTISSDT1 = null;
	private DecimalField fieldCLTISSDT2 = null;
	private DecimalField fieldCLTISSDT3 = null;
	private DecimalField fieldCLTEXPDT1 = null;
	private DecimalField fieldCLTEXPDT2 = null;
	private DecimalField fieldCLTEXPDT3 = null;
	private CharacterField fieldCLTDCMORF = null;
	private CharacterField fieldCLTDCMDRF = null;
	private DecimalField fieldCLTDCMCKN = null;
	private CharacterField fieldCLTDCMDR1 = null;
	private CharacterField fieldCLTDCMDR2 = null;
	private CharacterField fieldCLTDCMDR3 = null;
	private CharacterField fieldCLTDCMDR4 = null;
	private CharacterField fieldCLTDCMDW1 = null;
	private CharacterField fieldCLTDCMDW2 = null;
	private CharacterField fieldCLTDCMDW3 = null;
	private CharacterField fieldCLTDCMDW4 = null;
	private CharacterField fieldCLTDCMRB1 = null;
	private CharacterField fieldCLTDCMRB2 = null;
	private CharacterField fieldCLTDCMRB3 = null;
	private CharacterField fieldCLTDCMRB4 = null;
	private CharacterField fieldCLTDCMCL1 = null;
	private CharacterField fieldCLTDCMCL2 = null;
	private CharacterField fieldCLTDCMCL3 = null;
	private CharacterField fieldCLTDCMCL4 = null;
	private CharacterField fieldCLTDCMAG1 = null;
	private CharacterField fieldCLTDCMAG2 = null;
	private CharacterField fieldCLTDCMAG3 = null;
	private CharacterField fieldCLTDCMAG4 = null;

	/**
	 * Constructor for CLTDSJVMessage.
	 */
	public CLTDSJVMessage() {
		createFields();
		initialize();
	}

	/**
	 * Create fields for this message. This method implements the abstract
	 * method in the MessageRecord superclass.
	 */
	protected void createFields() {
		recordsize = 821;
		fileid = "1000802211800";
		recordid = "30345E25DDDAA";
		message = new byte[getByteLength()];
		formatname = "CLTDSJV";
		fieldnames = new String[FIELDCOUNT];
		tagnames = new String[FIELDCOUNT];
		fields = new MessageField[FIELDCOUNT];

		fieldnames[0] = "CLTUSER";
		tagnames[0] = "CLTUSER";
		fields[0] = fieldCLTUSER = new CharacterField(message, HEADERSIZE + 0,
				10, "CLTUSER");
		fieldnames[1] = "CLTFLG";
		tagnames[1] = "CLTFLG";
		fields[1] = fieldCLTFLG = new CharacterField(message, HEADERSIZE + 10,
				1, "CLTFLG");
		fieldnames[2] = "CLTDCMACC";
		tagnames[2] = "CLTDCMACC";
		fields[2] = fieldCLTDCMACC = new DecimalField(message, HEADERSIZE + 11,
				13, 0, "CLTDCMACC");
		fieldnames[3] = "CLTDCMCCY";
		tagnames[3] = "CLTDCMCCY";
		fields[3] = fieldCLTDCMCCY = new CharacterField(message,
				HEADERSIZE + 24, 3, "CLTDCMCCY");
		fieldnames[4] = "CLTDCMTYP";
		tagnames[4] = "CLTDCMTYP";
		fields[4] = fieldCLTDCMTYP = new CharacterField(message,
				HEADERSIZE + 27, 1, "CLTDCMTYP");
		fieldnames[5] = "CLTDCMSTY";
		tagnames[5] = "CLTDCMSTY";
		fields[5] = fieldCLTDCMSTY = new CharacterField(message,
				HEADERSIZE + 28, 1, "CLTDCMSTY");
		fieldnames[6] = "CLTDCMSTS";
		tagnames[6] = "CLTDCMSTS";
		fields[6] = fieldCLTDCMSTS = new CharacterField(message,
				HEADERSIZE + 29, 1, "CLTDCMSTS");
		fieldnames[7] = "CLTDCMRDF";
		tagnames[7] = "CLTDCMRDF";
		fields[7] = fieldCLTDCMRDF = new CharacterField(message,
				HEADERSIZE + 30, 1, "CLTDCMRDF");
		fieldnames[8] = "CLTDCMOAM";
		tagnames[8] = "CLTDCMOAM";
		fields[8] = fieldCLTDCMOAM = new DecimalField(message, HEADERSIZE + 31,
				15, 2, "CLTDCMOAM");
		fieldnames[9] = "CLTDCMAMN";
		tagnames[9] = "CLTDCMAMN";
		fields[9] = fieldCLTDCMAMN = new DecimalField(message, HEADERSIZE + 46,
				15, 2, "CLTDCMAMN");
		fieldnames[10] = "CLTISSDT1";
		tagnames[10] = "CLTISSDT1";
		fields[10] = fieldCLTISSDT1 = new DecimalField(message,
				HEADERSIZE + 61, 3, 0, "CLTISSDT1");
		fieldnames[11] = "CLTISSDT2";
		tagnames[11] = "CLTISSDT2";
		fields[11] = fieldCLTISSDT2 = new DecimalField(message,
				HEADERSIZE + 64, 3, 0, "CLTISSDT2");
		fieldnames[12] = "CLTISSDT3";
		tagnames[12] = "CLTISSDT3";
		fields[12] = fieldCLTISSDT3 = new DecimalField(message,
				HEADERSIZE + 67, 3, 0, "CLTISSDT3");
		fieldnames[13] = "CLTEXPDT1";
		tagnames[13] = "CLTEXPDT1";
		fields[13] = fieldCLTEXPDT1 = new DecimalField(message,
				HEADERSIZE + 70, 3, 0, "CLTEXPDT1");
		fieldnames[14] = "CLTEXPDT2";
		tagnames[14] = "CLTEXPDT2";
		fields[14] = fieldCLTEXPDT2 = new DecimalField(message,
				HEADERSIZE + 73, 3, 0, "CLTEXPDT2");
		fieldnames[15] = "CLTEXPDT3";
		tagnames[15] = "CLTEXPDT3";
		fields[15] = fieldCLTEXPDT3 = new DecimalField(message,
				HEADERSIZE + 76, 3, 0, "CLTEXPDT3");
		fieldnames[16] = "CLTDCMORF";
		tagnames[16] = "CLTDCMORF";
		fields[16] = fieldCLTDCMORF = new CharacterField(message,
				HEADERSIZE + 79, 16, "CLTDCMORF");
		fieldnames[17] = "CLTDCMDRF";
		tagnames[17] = "CLTDCMDRF";
		fields[17] = fieldCLTDCMDRF = new CharacterField(message,
				HEADERSIZE + 95, 16, "CLTDCMDRF");
		fieldnames[18] = "CLTDCMCKN";
		tagnames[18] = "CLTDCMCKN";
		fields[18] = fieldCLTDCMCKN = new DecimalField(message,
				HEADERSIZE + 111, 10, 0, "CLTDCMCKN");
		fieldnames[19] = "CLTDCMDR1";
		tagnames[19] = "CLTDCMDR1";
		fields[19] = fieldCLTDCMDR1 = new CharacterField(message,
				HEADERSIZE + 121, 35, "CLTDCMDR1");
		fieldnames[20] = "CLTDCMDR2";
		tagnames[20] = "CLTDCMDR2";
		fields[20] = fieldCLTDCMDR2 = new CharacterField(message,
				HEADERSIZE + 156, 35, "CLTDCMDR2");
		fieldnames[21] = "CLTDCMDR3";
		tagnames[21] = "CLTDCMDR3";
		fields[21] = fieldCLTDCMDR3 = new CharacterField(message,
				HEADERSIZE + 191, 35, "CLTDCMDR3");
		fieldnames[22] = "CLTDCMDR4";
		tagnames[22] = "CLTDCMDR4";
		fields[22] = fieldCLTDCMDR4 = new CharacterField(message,
				HEADERSIZE + 226, 35, "CLTDCMDR4");
		fieldnames[23] = "CLTDCMDW1";
		tagnames[23] = "CLTDCMDW1";
		fields[23] = fieldCLTDCMDW1 = new CharacterField(message,
				HEADERSIZE + 261, 35, "CLTDCMDW1");
		fieldnames[24] = "CLTDCMDW2";
		tagnames[24] = "CLTDCMDW2";
		fields[24] = fieldCLTDCMDW2 = new CharacterField(message,
				HEADERSIZE + 296, 35, "CLTDCMDW2");
		fieldnames[25] = "CLTDCMDW3";
		tagnames[25] = "CLTDCMDW3";
		fields[25] = fieldCLTDCMDW3 = new CharacterField(message,
				HEADERSIZE + 331, 35, "CLTDCMDW3");
		fieldnames[26] = "CLTDCMDW4";
		tagnames[26] = "CLTDCMDW4";
		fields[26] = fieldCLTDCMDW4 = new CharacterField(message,
				HEADERSIZE + 366, 35, "CLTDCMDW4");
		fieldnames[27] = "CLTDCMRB1";
		tagnames[27] = "CLTDCMRB1";
		fields[27] = fieldCLTDCMRB1 = new CharacterField(message,
				HEADERSIZE + 401, 35, "CLTDCMRB1");
		fieldnames[28] = "CLTDCMRB2";
		tagnames[28] = "CLTDCMRB2";
		fields[28] = fieldCLTDCMRB2 = new CharacterField(message,
				HEADERSIZE + 436, 35, "CLTDCMRB2");
		fieldnames[29] = "CLTDCMRB3";
		tagnames[29] = "CLTDCMRB3";
		fields[29] = fieldCLTDCMRB3 = new CharacterField(message,
				HEADERSIZE + 471, 35, "CLTDCMRB3");
		fieldnames[30] = "CLTDCMRB4";
		tagnames[30] = "CLTDCMRB4";
		fields[30] = fieldCLTDCMRB4 = new CharacterField(message,
				HEADERSIZE + 506, 35, "CLTDCMRB4");
		fieldnames[31] = "CLTDCMCL1";
		tagnames[31] = "CLTDCMCL1";
		fields[31] = fieldCLTDCMCL1 = new CharacterField(message,
				HEADERSIZE + 541, 35, "CLTDCMCL1");
		fieldnames[32] = "CLTDCMCL2";
		tagnames[32] = "CLTDCMCL2";
		fields[32] = fieldCLTDCMCL2 = new CharacterField(message,
				HEADERSIZE + 576, 35, "CLTDCMCL2");
		fieldnames[33] = "CLTDCMCL3";
		tagnames[33] = "CLTDCMCL3";
		fields[33] = fieldCLTDCMCL3 = new CharacterField(message,
				HEADERSIZE + 611, 35, "CLTDCMCL3");
		fieldnames[34] = "CLTDCMCL4";
		tagnames[34] = "CLTDCMCL4";
		fields[34] = fieldCLTDCMCL4 = new CharacterField(message,
				HEADERSIZE + 646, 35, "CLTDCMCL4");
		fieldnames[35] = "CLTDCMAG1";
		tagnames[35] = "CLTDCMAG1";
		fields[35] = fieldCLTDCMAG1 = new CharacterField(message,
				HEADERSIZE + 681, 35, "CLTDCMAG1");
		fieldnames[36] = "CLTDCMAG2";
		tagnames[36] = "CLTDCMAG2";
		fields[36] = fieldCLTDCMAG2 = new CharacterField(message,
				HEADERSIZE + 716, 35, "CLTDCMAG2");
		fieldnames[37] = "CLTDCMAG3";
		tagnames[37] = "CLTDCMAG3";
		fields[37] = fieldCLTDCMAG3 = new CharacterField(message,
				HEADERSIZE + 751, 35, "CLTDCMAG3");
		fieldnames[38] = "CLTDCMAG4";
		tagnames[38] = "CLTDCMAG4";
		fields[38] = fieldCLTDCMAG4 = new CharacterField(message,
				HEADERSIZE + 786, 35, "CLTDCMAG4");
	}

	/**
	 * Return value of numeric field CLTDCMACC as a BigDecimal.
	 */
	public BigDecimal getBigDecimalCLTDCMACC() {
		return fieldCLTDCMACC.getBigDecimal();
	}

	/**
	 * Return value of numeric field CLTDCMAMN as a BigDecimal.
	 */
	public BigDecimal getBigDecimalCLTDCMAMN() {
		return fieldCLTDCMAMN.getBigDecimal();
	}

	/**
	 * Return value of numeric field CLTDCMCKN as a BigDecimal.
	 */
	public BigDecimal getBigDecimalCLTDCMCKN() {
		return fieldCLTDCMCKN.getBigDecimal();
	}

	/**
	 * Return value of numeric field CLTDCMOAM as a BigDecimal.
	 */
	public BigDecimal getBigDecimalCLTDCMOAM() {
		return fieldCLTDCMOAM.getBigDecimal();
	}

	/**
	 * Return value of numeric field CLTEXPDT1 as a BigDecimal.
	 */
	public BigDecimal getBigDecimalCLTEXPDT1() {
		return fieldCLTEXPDT1.getBigDecimal();
	}

	/**
	 * Return value of numeric field CLTEXPDT2 as a BigDecimal.
	 */
	public BigDecimal getBigDecimalCLTEXPDT2() {
		return fieldCLTEXPDT2.getBigDecimal();
	}

	/**
	 * Return value of numeric field CLTEXPDT3 as a BigDecimal.
	 */
	public BigDecimal getBigDecimalCLTEXPDT3() {
		return fieldCLTEXPDT3.getBigDecimal();
	}

	/**
	 * Return value of numeric field CLTISSDT1 as a BigDecimal.
	 */
	public BigDecimal getBigDecimalCLTISSDT1() {
		return fieldCLTISSDT1.getBigDecimal();
	}

	/**
	 * Return value of numeric field CLTISSDT2 as a BigDecimal.
	 */
	public BigDecimal getBigDecimalCLTISSDT2() {
		return fieldCLTISSDT2.getBigDecimal();
	}

	/**
	 * Return value of numeric field CLTISSDT3 as a BigDecimal.
	 */
	public BigDecimal getBigDecimalCLTISSDT3() {
		return fieldCLTISSDT3.getBigDecimal();
	}

	/**
	 * Get value of field CLTDCMACC as a String.
	 */
	public String getCLTDCMACC() {
		return fieldCLTDCMACC.getString();
	}

	/**
	 * Get value of field CLTDCMAG1 as a String.
	 */
	public String getCLTDCMAG1() {
		return fieldCLTDCMAG1.getString();
	}

	/**
	 * Get value of field CLTDCMAG2 as a String.
	 */
	public String getCLTDCMAG2() {
		return fieldCLTDCMAG2.getString();
	}

	/**
	 * Get value of field CLTDCMAG3 as a String.
	 */
	public String getCLTDCMAG3() {
		return fieldCLTDCMAG3.getString();
	}

	/**
	 * Get value of field CLTDCMAG4 as a String.
	 */
	public String getCLTDCMAG4() {
		return fieldCLTDCMAG4.getString();
	}

	/**
	 * Get value of field CLTDCMAMN as a String.
	 */
	public String getCLTDCMAMN() {
		return fieldCLTDCMAMN.getString();
	}

	/**
	 * Get value of field CLTDCMCCY as a String.
	 */
	public String getCLTDCMCCY() {
		return fieldCLTDCMCCY.getString();
	}

	/**
	 * Get value of field CLTDCMCKN as a String.
	 */
	public String getCLTDCMCKN() {
		return fieldCLTDCMCKN.getString();
	}

	/**
	 * Get value of field CLTDCMCL1 as a String.
	 */
	public String getCLTDCMCL1() {
		return fieldCLTDCMCL1.getString();
	}

	/**
	 * Get value of field CLTDCMCL2 as a String.
	 */
	public String getCLTDCMCL2() {
		return fieldCLTDCMCL2.getString();
	}

	/**
	 * Get value of field CLTDCMCL3 as a String.
	 */
	public String getCLTDCMCL3() {
		return fieldCLTDCMCL3.getString();
	}

	/**
	 * Get value of field CLTDCMCL4 as a String.
	 */
	public String getCLTDCMCL4() {
		return fieldCLTDCMCL4.getString();
	}

	/**
	 * Get value of field CLTDCMDR1 as a String.
	 */
	public String getCLTDCMDR1() {
		return fieldCLTDCMDR1.getString();
	}

	/**
	 * Get value of field CLTDCMDR2 as a String.
	 */
	public String getCLTDCMDR2() {
		return fieldCLTDCMDR2.getString();
	}

	/**
	 * Get value of field CLTDCMDR3 as a String.
	 */
	public String getCLTDCMDR3() {
		return fieldCLTDCMDR3.getString();
	}

	/**
	 * Get value of field CLTDCMDR4 as a String.
	 */
	public String getCLTDCMDR4() {
		return fieldCLTDCMDR4.getString();
	}

	/**
	 * Get value of field CLTDCMDRF as a String.
	 */
	public String getCLTDCMDRF() {
		return fieldCLTDCMDRF.getString();
	}

	/**
	 * Get value of field CLTDCMDW1 as a String.
	 */
	public String getCLTDCMDW1() {
		return fieldCLTDCMDW1.getString();
	}

	/**
	 * Get value of field CLTDCMDW2 as a String.
	 */
	public String getCLTDCMDW2() {
		return fieldCLTDCMDW2.getString();
	}

	/**
	 * Get value of field CLTDCMDW3 as a String.
	 */
	public String getCLTDCMDW3() {
		return fieldCLTDCMDW3.getString();
	}

	/**
	 * Get value of field CLTDCMDW4 as a String.
	 */
	public String getCLTDCMDW4() {
		return fieldCLTDCMDW4.getString();
	}

	/**
	 * Get value of field CLTDCMOAM as a String.
	 */
	public String getCLTDCMOAM() {
		return fieldCLTDCMOAM.getString();
	}

	/**
	 * Get value of field CLTDCMORF as a String.
	 */
	public String getCLTDCMORF() {
		return fieldCLTDCMORF.getString();
	}

	/**
	 * Get value of field CLTDCMRB1 as a String.
	 */
	public String getCLTDCMRB1() {
		return fieldCLTDCMRB1.getString();
	}

	/**
	 * Get value of field CLTDCMRB2 as a String.
	 */
	public String getCLTDCMRB2() {
		return fieldCLTDCMRB2.getString();
	}

	/**
	 * Get value of field CLTDCMRB3 as a String.
	 */
	public String getCLTDCMRB3() {
		return fieldCLTDCMRB3.getString();
	}

	/**
	 * Get value of field CLTDCMRB4 as a String.
	 */
	public String getCLTDCMRB4() {
		return fieldCLTDCMRB4.getString();
	}

	/**
	 * Get value of field CLTDCMRDF as a String.
	 */
	public String getCLTDCMRDF() {
		return fieldCLTDCMRDF.getString();
	}

	/**
	 * Get value of field CLTDCMSTS as a String.
	 */
	public String getCLTDCMSTS() {
		return fieldCLTDCMSTS.getString();
	}

	/**
	 * Get value of field CLTDCMSTY as a String.
	 */
	public String getCLTDCMSTY() {
		return fieldCLTDCMSTY.getString();
	}

	/**
	 * Get value of field CLTDCMTYP as a String.
	 */
	public String getCLTDCMTYP() {
		return fieldCLTDCMTYP.getString();
	}

	/**
	 * Get value of field CLTEXPDT1 as a String.
	 */
	public String getCLTEXPDT1() {
		return fieldCLTEXPDT1.getString();
	}

	/**
	 * Get value of field CLTEXPDT2 as a String.
	 */
	public String getCLTEXPDT2() {
		return fieldCLTEXPDT2.getString();
	}

	/**
	 * Get value of field CLTEXPDT3 as a String.
	 */
	public String getCLTEXPDT3() {
		return fieldCLTEXPDT3.getString();
	}

	/**
	 * Get value of field CLTFLG as a String.
	 */
	public String getCLTFLG() {
		return fieldCLTFLG.getString();
	}

	/**
	 * Get value of field CLTISSDT1 as a String.
	 */
	public String getCLTISSDT1() {
		return fieldCLTISSDT1.getString();
	}

	/**
	 * Get value of field CLTISSDT2 as a String.
	 */
	public String getCLTISSDT2() {
		return fieldCLTISSDT2.getString();
	}

	/**
	 * Get value of field CLTISSDT3 as a String.
	 */
	public String getCLTISSDT3() {
		return fieldCLTISSDT3.getString();
	}

	/**
	 * Get value of field CLTUSER as a String.
	 */
	public String getCLTUSER() {
		return fieldCLTUSER.getString();
	}

	/**
	 * Set field CLTDCMACC using a String value.
	 */
	public void setCLTDCMACC(String newvalue) {
		fieldCLTDCMACC.setString(newvalue);
	}

	/**
	 * Set numeric field CLTDCMACC using a BigDecimal value.
	 */
	public void setCLTDCMACC(BigDecimal newvalue) {
		fieldCLTDCMACC.setBigDecimal(newvalue);
	}

	/**
	 * Set field CLTDCMAG1 using a String value.
	 */
	public void setCLTDCMAG1(String newvalue) {
		fieldCLTDCMAG1.setString(newvalue);
	}

	/**
	 * Set field CLTDCMAG2 using a String value.
	 */
	public void setCLTDCMAG2(String newvalue) {
		fieldCLTDCMAG2.setString(newvalue);
	}

	/**
	 * Set field CLTDCMAG3 using a String value.
	 */
	public void setCLTDCMAG3(String newvalue) {
		fieldCLTDCMAG3.setString(newvalue);
	}

	/**
	 * Set field CLTDCMAG4 using a String value.
	 */
	public void setCLTDCMAG4(String newvalue) {
		fieldCLTDCMAG4.setString(newvalue);
	}

	/**
	 * Set field CLTDCMAMN using a String value.
	 */
	public void setCLTDCMAMN(String newvalue) {
		fieldCLTDCMAMN.setString(newvalue);
	}

	/**
	 * Set numeric field CLTDCMAMN using a BigDecimal value.
	 */
	public void setCLTDCMAMN(BigDecimal newvalue) {
		fieldCLTDCMAMN.setBigDecimal(newvalue);
	}

	/**
	 * Set field CLTDCMCCY using a String value.
	 */
	public void setCLTDCMCCY(String newvalue) {
		fieldCLTDCMCCY.setString(newvalue);
	}

	/**
	 * Set field CLTDCMCKN using a String value.
	 */
	public void setCLTDCMCKN(String newvalue) {
		fieldCLTDCMCKN.setString(newvalue);
	}

	/**
	 * Set numeric field CLTDCMCKN using a BigDecimal value.
	 */
	public void setCLTDCMCKN(BigDecimal newvalue) {
		fieldCLTDCMCKN.setBigDecimal(newvalue);
	}

	/**
	 * Set field CLTDCMCL1 using a String value.
	 */
	public void setCLTDCMCL1(String newvalue) {
		fieldCLTDCMCL1.setString(newvalue);
	}

	/**
	 * Set field CLTDCMCL2 using a String value.
	 */
	public void setCLTDCMCL2(String newvalue) {
		fieldCLTDCMCL2.setString(newvalue);
	}

	/**
	 * Set field CLTDCMCL3 using a String value.
	 */
	public void setCLTDCMCL3(String newvalue) {
		fieldCLTDCMCL3.setString(newvalue);
	}

	/**
	 * Set field CLTDCMCL4 using a String value.
	 */
	public void setCLTDCMCL4(String newvalue) {
		fieldCLTDCMCL4.setString(newvalue);
	}

	/**
	 * Set field CLTDCMDR1 using a String value.
	 */
	public void setCLTDCMDR1(String newvalue) {
		fieldCLTDCMDR1.setString(newvalue);
	}

	/**
	 * Set field CLTDCMDR2 using a String value.
	 */
	public void setCLTDCMDR2(String newvalue) {
		fieldCLTDCMDR2.setString(newvalue);
	}

	/**
	 * Set field CLTDCMDR3 using a String value.
	 */
	public void setCLTDCMDR3(String newvalue) {
		fieldCLTDCMDR3.setString(newvalue);
	}

	/**
	 * Set field CLTDCMDR4 using a String value.
	 */
	public void setCLTDCMDR4(String newvalue) {
		fieldCLTDCMDR4.setString(newvalue);
	}

	/**
	 * Set field CLTDCMDRF using a String value.
	 */
	public void setCLTDCMDRF(String newvalue) {
		fieldCLTDCMDRF.setString(newvalue);
	}

	/**
	 * Set field CLTDCMDW1 using a String value.
	 */
	public void setCLTDCMDW1(String newvalue) {
		fieldCLTDCMDW1.setString(newvalue);
	}

	/**
	 * Set field CLTDCMDW2 using a String value.
	 */
	public void setCLTDCMDW2(String newvalue) {
		fieldCLTDCMDW2.setString(newvalue);
	}

	/**
	 * Set field CLTDCMDW3 using a String value.
	 */
	public void setCLTDCMDW3(String newvalue) {
		fieldCLTDCMDW3.setString(newvalue);
	}

	/**
	 * Set field CLTDCMDW4 using a String value.
	 */
	public void setCLTDCMDW4(String newvalue) {
		fieldCLTDCMDW4.setString(newvalue);
	}

	/**
	 * Set field CLTDCMOAM using a String value.
	 */
	public void setCLTDCMOAM(String newvalue) {
		fieldCLTDCMOAM.setString(newvalue);
	}

	/**
	 * Set numeric field CLTDCMOAM using a BigDecimal value.
	 */
	public void setCLTDCMOAM(BigDecimal newvalue) {
		fieldCLTDCMOAM.setBigDecimal(newvalue);
	}

	/**
	 * Set field CLTDCMORF using a String value.
	 */
	public void setCLTDCMORF(String newvalue) {
		fieldCLTDCMORF.setString(newvalue);
	}

	/**
	 * Set field CLTDCMRB1 using a String value.
	 */
	public void setCLTDCMRB1(String newvalue) {
		fieldCLTDCMRB1.setString(newvalue);
	}

	/**
	 * Set field CLTDCMRB2 using a String value.
	 */
	public void setCLTDCMRB2(String newvalue) {
		fieldCLTDCMRB2.setString(newvalue);
	}

	/**
	 * Set field CLTDCMRB3 using a String value.
	 */
	public void setCLTDCMRB3(String newvalue) {
		fieldCLTDCMRB3.setString(newvalue);
	}

	/**
	 * Set field CLTDCMRB4 using a String value.
	 */
	public void setCLTDCMRB4(String newvalue) {
		fieldCLTDCMRB4.setString(newvalue);
	}

	/**
	 * Set field CLTDCMRDF using a String value.
	 */
	public void setCLTDCMRDF(String newvalue) {
		fieldCLTDCMRDF.setString(newvalue);
	}

	/**
	 * Set field CLTDCMSTS using a String value.
	 */
	public void setCLTDCMSTS(String newvalue) {
		fieldCLTDCMSTS.setString(newvalue);
	}

	/**
	 * Set field CLTDCMSTY using a String value.
	 */
	public void setCLTDCMSTY(String newvalue) {
		fieldCLTDCMSTY.setString(newvalue);
	}

	/**
	 * Set field CLTDCMTYP using a String value.
	 */
	public void setCLTDCMTYP(String newvalue) {
		fieldCLTDCMTYP.setString(newvalue);
	}

	/**
	 * Set field CLTEXPDT1 using a String value.
	 */
	public void setCLTEXPDT1(String newvalue) {
		fieldCLTEXPDT1.setString(newvalue);
	}

	/**
	 * Set numeric field CLTEXPDT1 using a BigDecimal value.
	 */
	public void setCLTEXPDT1(BigDecimal newvalue) {
		fieldCLTEXPDT1.setBigDecimal(newvalue);
	}

	/**
	 * Set field CLTEXPDT2 using a String value.
	 */
	public void setCLTEXPDT2(String newvalue) {
		fieldCLTEXPDT2.setString(newvalue);
	}

	/**
	 * Set numeric field CLTEXPDT2 using a BigDecimal value.
	 */
	public void setCLTEXPDT2(BigDecimal newvalue) {
		fieldCLTEXPDT2.setBigDecimal(newvalue);
	}

	/**
	 * Set field CLTEXPDT3 using a String value.
	 */
	public void setCLTEXPDT3(String newvalue) {
		fieldCLTEXPDT3.setString(newvalue);
	}

	/**
	 * Set numeric field CLTEXPDT3 using a BigDecimal value.
	 */
	public void setCLTEXPDT3(BigDecimal newvalue) {
		fieldCLTEXPDT3.setBigDecimal(newvalue);
	}

	/**
	 * Set field CLTFLG using a String value.
	 */
	public void setCLTFLG(String newvalue) {
		fieldCLTFLG.setString(newvalue);
	}

	/**
	 * Set field CLTISSDT1 using a String value.
	 */
	public void setCLTISSDT1(String newvalue) {
		fieldCLTISSDT1.setString(newvalue);
	}

	/**
	 * Set numeric field CLTISSDT1 using a BigDecimal value.
	 */
	public void setCLTISSDT1(BigDecimal newvalue) {
		fieldCLTISSDT1.setBigDecimal(newvalue);
	}

	/**
	 * Set field CLTISSDT2 using a String value.
	 */
	public void setCLTISSDT2(String newvalue) {
		fieldCLTISSDT2.setString(newvalue);
	}

	/**
	 * Set numeric field CLTISSDT2 using a BigDecimal value.
	 */
	public void setCLTISSDT2(BigDecimal newvalue) {
		fieldCLTISSDT2.setBigDecimal(newvalue);
	}

	/**
	 * Set field CLTISSDT3 using a String value.
	 */
	public void setCLTISSDT3(String newvalue) {
		fieldCLTISSDT3.setString(newvalue);
	}

	/**
	 * Set numeric field CLTISSDT3 using a BigDecimal value.
	 */
	public void setCLTISSDT3(BigDecimal newvalue) {
		fieldCLTISSDT3.setBigDecimal(newvalue);
	}

	/**
	 * Set field CLTUSER using a String value.
	 */
	public void setCLTUSER(String newvalue) {
		fieldCLTUSER.setString(newvalue);
	}
}