package com.afirme.afirmenet.ibs.messages;

import java.math.BigDecimal;
import java.util.Hashtable;

import com.datapro.sockets.CharacterField;
import com.datapro.sockets.DecimalField;
import com.datapro.sockets.MessageField;
import com.datapro.sockets.MessageRecord;

/**
* Class generated by AS/400 CRTCLASS command from DTLPRDSJV physical file definition.
* 
* File level identifier is 1041007112947.
* Record format level identifier is 441D90344BEBC.
*/
@SuppressWarnings("rawtypes")
public class DTLPRDSJVMessage extends MessageRecord
{
  final static String fldnames[] = {
                                     "DT_USER",
                                     "DT_TRNCDE",
                                     "DT_FLGMAS",
                                     "DT_TIPREG",
                                     "DT_SECDET",
                                     "DT_FOLIO",
                                     "DT_RFC",
                                     "DT_CLAVE",
                                     "DT_FECPRE",
                                     "DT_HORPRE",
                                     "DT_PERIOD",
                                     "DT_EJERCI",
                                     "DT_TIPPAG",
                                     "DT_FECPAG",
                                     "DT_AFAVOR",
                                     "DT_ACARGO",
                                     "DT_PARACT",
                                     "DT_RCARGO",
                                     "DT_MULTA",
                                     "DT_TOTCON",
                                     "DT_CRSALA",
                                     "DT_COMPEN",
                                     "DT_CRDIES",
                                     "DT_DIEAUT",
                                     "DT_CARRET",
                                     "DT_AGAVE",
                                     "DT_OTREST",
                                     "DT_CERTIF",
                                     "DT_MONANT",
                                     "DT_TOTAPL",
                                     "DT_CANCAR",
                                     "DT_PARCIA",
                                     "DT_NOPARC",
                                     "DT_PAGEXC",
                                     "DT_CANPAG",
                                     "DT_UTILID",
                                     "DT_FECDEC",
                                     "DT_NUMSAT",
                                     "DT_NUMCRE",
                                     "DT_ENTIDA",
                                     "DT_DEPEND",
                                     "DT_CONTAB",
                                     "DT_CADENA",
                                     "DT_DPA",
                                     "DT_CAMPO1",
                                     "DT_CAMPO2",
                                     "DT_CAMPO3",
                                     "DT_CAMPO4",
                                     "DT_CAMPO5"
                                   };
  final static String tnames[] = {
                                   "DT_USER",
                                   "DT_TRNCDE",
                                   "DT_FLGMAS",
                                   "DT_TIPREG",
                                   "DT_SECDET",
                                   "DT_FOLIO",
                                   "DT_RFC",
                                   "DT_CLAVE",
                                   "DT_FECPRE",
                                   "DT_HORPRE",
                                   "DT_PERIOD",
                                   "DT_EJERCI",
                                   "DT_TIPPAG",
                                   "DT_FECPAG",
                                   "DT_AFAVOR",
                                   "DT_ACARGO",
                                   "DT_PARACT",
                                   "DT_RCARGO",
                                   "DT_MULTA",
                                   "DT_TOTCON",
                                   "DT_CRSALA",
                                   "DT_COMPEN",
                                   "DT_CRDIES",
                                   "DT_DIEAUT",
                                   "DT_CARRET",
                                   "DT_AGAVE",
                                   "DT_OTREST",
                                   "DT_CERTIF",
                                   "DT_MONANT",
                                   "DT_TOTAPL",
                                   "DT_CANCAR",
                                   "DT_PARCIA",
                                   "DT_NOPARC",
                                   "DT_PAGEXC",
                                   "DT_CANPAG",
                                   "DT_UTILID",
                                   "DT_FECDEC",
                                   "DT_NUMSAT",
                                   "DT_NUMCRE",
                                   "DT_ENTIDA",
                                   "DT_DEPEND",
                                   "DT_CONTAB",
                                   "DT_CADENA",
                                   "DT_DPA",
                                   "DT_CAMPO1",
                                   "DT_CAMPO2",
                                   "DT_CAMPO3",
                                   "DT_CAMPO4",
                                   "DT_CAMPO5"
                                 };
  final static String fid = "1041007112947";
  final static String rid = "441D90344BEBC";
  final static String fmtname = "DTLPRDSJV";
  final int FIELDCOUNT = 49;
  private static Hashtable tlookup = new Hashtable();
  private CharacterField fieldDT_USER = null;
  private DecimalField fieldDT_TRNCDE = null;
  private CharacterField fieldDT_FLGMAS = null;
  private CharacterField fieldDT_TIPREG = null;
  private DecimalField fieldDT_SECDET = null;
  private DecimalField fieldDT_FOLIO = null;
  private CharacterField fieldDT_RFC = null;
  private DecimalField fieldDT_CLAVE = null;
  private CharacterField fieldDT_FECPRE = null;
  private CharacterField fieldDT_HORPRE = null;
  private DecimalField fieldDT_PERIOD = null;
  private DecimalField fieldDT_EJERCI = null;
  private DecimalField fieldDT_TIPPAG = null;
  private CharacterField fieldDT_FECPAG = null;
  private DecimalField fieldDT_AFAVOR = null;
  private DecimalField fieldDT_ACARGO = null;
  private DecimalField fieldDT_PARACT = null;
  private DecimalField fieldDT_RCARGO = null;
  private DecimalField fieldDT_MULTA = null;
  private DecimalField fieldDT_TOTCON = null;
  private DecimalField fieldDT_CRSALA = null;
  private DecimalField fieldDT_COMPEN = null;
  private DecimalField fieldDT_CRDIES = null;
  private DecimalField fieldDT_DIEAUT = null;
  private DecimalField fieldDT_CARRET = null;
  private DecimalField fieldDT_AGAVE = null;
  private DecimalField fieldDT_OTREST = null;
  private DecimalField fieldDT_CERTIF = null;
  private DecimalField fieldDT_MONANT = null;
  private DecimalField fieldDT_TOTAPL = null;
  private DecimalField fieldDT_CANCAR = null;
  private DecimalField fieldDT_PARCIA = null;
  private DecimalField fieldDT_NOPARC = null;
  private DecimalField fieldDT_PAGEXC = null;
  private DecimalField fieldDT_CANPAG = null;
  private DecimalField fieldDT_UTILID = null;
  private CharacterField fieldDT_FECDEC = null;
  private CharacterField fieldDT_NUMSAT = null;
  private DecimalField fieldDT_NUMCRE = null;
  private DecimalField fieldDT_ENTIDA = null;
  private DecimalField fieldDT_DEPEND = null;
  private DecimalField fieldDT_CONTAB = null;
  private CharacterField fieldDT_CADENA = null;
  private DecimalField fieldDT_DPA = null;
  private DecimalField fieldDT_CAMPO1 = null;
  private DecimalField fieldDT_CAMPO2 = null;
  private CharacterField fieldDT_CAMPO3 = null;
  private CharacterField fieldDT_CAMPO4 = null;
  private CharacterField fieldDT_CAMPO5 = null;

  /**
  * Constructor for DTLPRDSJVMessage.
  */
  public DTLPRDSJVMessage()
  {
    createFields();
    initialize();
  }

  /**
  * Create fields for this message.
  * This method implements the abstract method in the MessageRecord superclass.
  */
@SuppressWarnings("unchecked")    protected void createFields()
  {
    recordsize = 529;
    fileid = fid;
    recordid = rid;
    message = new byte[getByteLength()];
    formatname = fmtname;
    fieldnames = fldnames;
    tagnames = tnames;
    fields = new MessageField[FIELDCOUNT];

    fields[0] = fieldDT_USER =
    new CharacterField(message, HEADERSIZE + 0, 10, "DT_USER");
    fields[1] = fieldDT_TRNCDE =
    new DecimalField(message, HEADERSIZE + 10, 5, 0, "DT_TRNCDE");
    fields[2] = fieldDT_FLGMAS =
    new CharacterField(message, HEADERSIZE + 15, 1, "DT_FLGMAS");
    fields[3] = fieldDT_TIPREG =
    new CharacterField(message, HEADERSIZE + 16, 1, "DT_TIPREG");
    fields[4] = fieldDT_SECDET =
    new DecimalField(message, HEADERSIZE + 17, 5, 0, "DT_SECDET");
    fields[5] = fieldDT_FOLIO =
    new DecimalField(message, HEADERSIZE + 22, 9, 0, "DT_FOLIO");
    fields[6] = fieldDT_RFC =
    new CharacterField(message, HEADERSIZE + 31, 18, "DT_RFC");
    fields[7] = fieldDT_CLAVE =
    new DecimalField(message, HEADERSIZE + 49, 4, 0, "DT_CLAVE");
    fields[8] = fieldDT_FECPRE =
    new CharacterField(message, HEADERSIZE + 53, 8, "DT_FECPRE");
    fields[9] = fieldDT_HORPRE =
    new CharacterField(message, HEADERSIZE + 61, 5, "DT_HORPRE");
    fields[10] = fieldDT_PERIOD =
    new DecimalField(message, HEADERSIZE + 66, 3, 0, "DT_PERIOD");
    fields[11] = fieldDT_EJERCI =
    new DecimalField(message, HEADERSIZE + 69, 5, 0, "DT_EJERCI");
    fields[12] = fieldDT_TIPPAG =
    new DecimalField(message, HEADERSIZE + 74, 2, 0, "DT_TIPPAG");
    fields[13] = fieldDT_FECPAG =
    new CharacterField(message, HEADERSIZE + 76, 8, "DT_FECPAG");
    fields[14] = fieldDT_AFAVOR =
    new DecimalField(message, HEADERSIZE + 84, 13, 0, "DT_AFAVOR");
    fields[15] = fieldDT_ACARGO =
    new DecimalField(message, HEADERSIZE + 97, 13, 0, "DT_ACARGO");
    fields[16] = fieldDT_PARACT =
    new DecimalField(message, HEADERSIZE + 110, 13, 0, "DT_PARACT");
    fields[17] = fieldDT_RCARGO =
    new DecimalField(message, HEADERSIZE + 123, 13, 0, "DT_RCARGO");
    fields[18] = fieldDT_MULTA =
    new DecimalField(message, HEADERSIZE + 136, 13, 0, "DT_MULTA");
    fields[19] = fieldDT_TOTCON =
    new DecimalField(message, HEADERSIZE + 149, 13, 0, "DT_TOTCON");
    fields[20] = fieldDT_CRSALA =
    new DecimalField(message, HEADERSIZE + 162, 13, 0, "DT_CRSALA");
    fields[21] = fieldDT_COMPEN =
    new DecimalField(message, HEADERSIZE + 175, 13, 0, "DT_COMPEN");
    fields[22] = fieldDT_CRDIES =
    new DecimalField(message, HEADERSIZE + 188, 13, 0, "DT_CRDIES");
    fields[23] = fieldDT_DIEAUT =
    new DecimalField(message, HEADERSIZE + 201, 13, 0, "DT_DIEAUT");
    fields[24] = fieldDT_CARRET =
    new DecimalField(message, HEADERSIZE + 214, 13, 0, "DT_CARRET");
    fields[25] = fieldDT_AGAVE =
    new DecimalField(message, HEADERSIZE + 227, 13, 0, "DT_AGAVE");
    fields[26] = fieldDT_OTREST =
    new DecimalField(message, HEADERSIZE + 240, 13, 0, "DT_OTREST");
    fields[27] = fieldDT_CERTIF =
    new DecimalField(message, HEADERSIZE + 253, 13, 0, "DT_CERTIF");
    fields[28] = fieldDT_MONANT =
    new DecimalField(message, HEADERSIZE + 266, 13, 0, "DT_MONANT");
    fields[29] = fieldDT_TOTAPL =
    new DecimalField(message, HEADERSIZE + 279, 13, 0, "DT_TOTAPL");
    fields[30] = fieldDT_CANCAR =
    new DecimalField(message, HEADERSIZE + 292, 13, 0, "DT_CANCAR");
    fields[31] = fieldDT_PARCIA =
    new DecimalField(message, HEADERSIZE + 305, 13, 0, "DT_PARCIA");
    fields[32] = fieldDT_NOPARC =
    new DecimalField(message, HEADERSIZE + 318, 13, 0, "DT_NOPARC");
    fields[33] = fieldDT_PAGEXC =
    new DecimalField(message, HEADERSIZE + 331, 13, 0, "DT_PAGEXC");
    fields[34] = fieldDT_CANPAG =
    new DecimalField(message, HEADERSIZE + 344, 13, 0, "DT_CANPAG");
    fields[35] = fieldDT_UTILID =
    new DecimalField(message, HEADERSIZE + 357, 13, 0, "DT_UTILID");
    fields[36] = fieldDT_FECDEC =
    new CharacterField(message, HEADERSIZE + 370, 8, "DT_FECDEC");
    fields[37] = fieldDT_NUMSAT =
    new CharacterField(message, HEADERSIZE + 378, 10, "DT_NUMSAT");
    fields[38] = fieldDT_NUMCRE =
    new DecimalField(message, HEADERSIZE + 388, 15, 0, "DT_NUMCRE");
    fields[39] = fieldDT_ENTIDA =
    new DecimalField(message, HEADERSIZE + 403, 6, 0, "DT_ENTIDA");
    fields[40] = fieldDT_DEPEND =
    new DecimalField(message, HEADERSIZE + 409, 3, 0, "DT_DEPEND");
    fields[41] = fieldDT_CONTAB =
    new DecimalField(message, HEADERSIZE + 412, 7, 0, "DT_CONTAB");
    fields[42] = fieldDT_CADENA =
    new CharacterField(message, HEADERSIZE + 419, 14, "DT_CADENA");
    fields[43] = fieldDT_DPA =
    new DecimalField(message, HEADERSIZE + 433, 10, 0, "DT_DPA");
    fields[44] = fieldDT_CAMPO1 =
    new DecimalField(message, HEADERSIZE + 443, 13, 0, "DT_CAMPO1");
    fields[45] = fieldDT_CAMPO2 =
    new DecimalField(message, HEADERSIZE + 456, 13, 0, "DT_CAMPO2");
    fields[46] = fieldDT_CAMPO3 =
    new CharacterField(message, HEADERSIZE + 469, 10, "DT_CAMPO3");
    fields[47] = fieldDT_CAMPO4 =
    new CharacterField(message, HEADERSIZE + 479, 20, "DT_CAMPO4");
    fields[48] = fieldDT_CAMPO5 =
    new CharacterField(message, HEADERSIZE + 499, 30, "DT_CAMPO5");

    synchronized (tlookup)
    {
      if (tlookup.isEmpty())
      {
        for (int i = 0; i < tnames.length; i++)
          tlookup.put(tnames[i], new Integer(i));
      }
    }

    taglookup = tlookup;
  }

  /**
  * Set field DT_USER using a String value.
  */
  public void setDT_USER(String newvalue)
  {
    fieldDT_USER.setString(newvalue);
  }

  /**
  * Get value of field DT_USER as a String.
  */
  public String getDT_USER()
  {
    return fieldDT_USER.getString();
  }

  /**
  * Set field DT_TRNCDE using a String value.
  */
  public void setDT_TRNCDE(String newvalue)
  {
    fieldDT_TRNCDE.setString(newvalue);
  }

  /**
  * Get value of field DT_TRNCDE as a String.
  */
  public String getDT_TRNCDE()
  {
    return fieldDT_TRNCDE.getString();
  }

  /**
  * Set numeric field DT_TRNCDE using a BigDecimal value.
  */
  public void setDT_TRNCDE(BigDecimal newvalue)
  {
    fieldDT_TRNCDE.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field DT_TRNCDE as a BigDecimal.
  */
  public BigDecimal getBigDecimalDT_TRNCDE()
  {
    return fieldDT_TRNCDE.getBigDecimal();
  }

  /**
  * Set field DT_FLGMAS using a String value.
  */
  public void setDT_FLGMAS(String newvalue)
  {
    fieldDT_FLGMAS.setString(newvalue);
  }

  /**
  * Get value of field DT_FLGMAS as a String.
  */
  public String getDT_FLGMAS()
  {
    return fieldDT_FLGMAS.getString();
  }

  /**
  * Set field DT_TIPREG using a String value.
  */
  public void setDT_TIPREG(String newvalue)
  {
    fieldDT_TIPREG.setString(newvalue);
  }

  /**
  * Get value of field DT_TIPREG as a String.
  */
  public String getDT_TIPREG()
  {
    return fieldDT_TIPREG.getString();
  }

  /**
  * Set field DT_SECDET using a String value.
  */
  public void setDT_SECDET(String newvalue)
  {
    fieldDT_SECDET.setString(newvalue);
  }

  /**
  * Get value of field DT_SECDET as a String.
  */
  public String getDT_SECDET()
  {
    return fieldDT_SECDET.getString();
  }

  /**
  * Set numeric field DT_SECDET using a BigDecimal value.
  */
  public void setDT_SECDET(BigDecimal newvalue)
  {
    fieldDT_SECDET.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field DT_SECDET as a BigDecimal.
  */
  public BigDecimal getBigDecimalDT_SECDET()
  {
    return fieldDT_SECDET.getBigDecimal();
  }

  /**
  * Set field DT_FOLIO using a String value.
  */
  public void setDT_FOLIO(String newvalue)
  {
    fieldDT_FOLIO.setString(newvalue);
  }

  /**
  * Get value of field DT_FOLIO as a String.
  */
  public String getDT_FOLIO()
  {
    return fieldDT_FOLIO.getString();
  }

  /**
  * Set numeric field DT_FOLIO using a BigDecimal value.
  */
  public void setDT_FOLIO(BigDecimal newvalue)
  {
    fieldDT_FOLIO.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field DT_FOLIO as a BigDecimal.
  */
  public BigDecimal getBigDecimalDT_FOLIO()
  {
    return fieldDT_FOLIO.getBigDecimal();
  }

  /**
  * Set field DT_RFC using a String value.
  */
  public void setDT_RFC(String newvalue)
  {
    fieldDT_RFC.setString(newvalue);
  }

  /**
  * Get value of field DT_RFC as a String.
  */
  public String getDT_RFC()
  {
    return fieldDT_RFC.getString();
  }

  /**
  * Set field DT_CLAVE using a String value.
  */
  public void setDT_CLAVE(String newvalue)
  {
    fieldDT_CLAVE.setString(newvalue);
  }

  /**
  * Get value of field DT_CLAVE as a String.
  */
  public String getDT_CLAVE()
  {
    return fieldDT_CLAVE.getString();
  }

  /**
  * Set numeric field DT_CLAVE using a BigDecimal value.
  */
  public void setDT_CLAVE(BigDecimal newvalue)
  {
    fieldDT_CLAVE.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field DT_CLAVE as a BigDecimal.
  */
  public BigDecimal getBigDecimalDT_CLAVE()
  {
    return fieldDT_CLAVE.getBigDecimal();
  }

  /**
  * Set field DT_FECPRE using a String value.
  */
  public void setDT_FECPRE(String newvalue)
  {
    fieldDT_FECPRE.setString(newvalue);
  }

  /**
  * Get value of field DT_FECPRE as a String.
  */
  public String getDT_FECPRE()
  {
    return fieldDT_FECPRE.getString();
  }

  /**
  * Set field DT_HORPRE using a String value.
  */
  public void setDT_HORPRE(String newvalue)
  {
    fieldDT_HORPRE.setString(newvalue);
  }

  /**
  * Get value of field DT_HORPRE as a String.
  */
  public String getDT_HORPRE()
  {
    return fieldDT_HORPRE.getString();
  }

  /**
  * Set field DT_PERIOD using a String value.
  */
  public void setDT_PERIOD(String newvalue)
  {
    fieldDT_PERIOD.setString(newvalue);
  }

  /**
  * Get value of field DT_PERIOD as a String.
  */
  public String getDT_PERIOD()
  {
    return fieldDT_PERIOD.getString();
  }

  /**
  * Set numeric field DT_PERIOD using a BigDecimal value.
  */
  public void setDT_PERIOD(BigDecimal newvalue)
  {
    fieldDT_PERIOD.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field DT_PERIOD as a BigDecimal.
  */
  public BigDecimal getBigDecimalDT_PERIOD()
  {
    return fieldDT_PERIOD.getBigDecimal();
  }

  /**
  * Set field DT_EJERCI using a String value.
  */
  public void setDT_EJERCI(String newvalue)
  {
    fieldDT_EJERCI.setString(newvalue);
  }

  /**
  * Get value of field DT_EJERCI as a String.
  */
  public String getDT_EJERCI()
  {
    return fieldDT_EJERCI.getString();
  }

  /**
  * Set numeric field DT_EJERCI using a BigDecimal value.
  */
  public void setDT_EJERCI(BigDecimal newvalue)
  {
    fieldDT_EJERCI.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field DT_EJERCI as a BigDecimal.
  */
  public BigDecimal getBigDecimalDT_EJERCI()
  {
    return fieldDT_EJERCI.getBigDecimal();
  }

  /**
  * Set field DT_TIPPAG using a String value.
  */
  public void setDT_TIPPAG(String newvalue)
  {
    fieldDT_TIPPAG.setString(newvalue);
  }

  /**
  * Get value of field DT_TIPPAG as a String.
  */
  public String getDT_TIPPAG()
  {
    return fieldDT_TIPPAG.getString();
  }

  /**
  * Set numeric field DT_TIPPAG using a BigDecimal value.
  */
  public void setDT_TIPPAG(BigDecimal newvalue)
  {
    fieldDT_TIPPAG.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field DT_TIPPAG as a BigDecimal.
  */
  public BigDecimal getBigDecimalDT_TIPPAG()
  {
    return fieldDT_TIPPAG.getBigDecimal();
  }

  /**
  * Set field DT_FECPAG using a String value.
  */
  public void setDT_FECPAG(String newvalue)
  {
    fieldDT_FECPAG.setString(newvalue);
  }

  /**
  * Get value of field DT_FECPAG as a String.
  */
  public String getDT_FECPAG()
  {
    return fieldDT_FECPAG.getString();
  }

  /**
  * Set field DT_AFAVOR using a String value.
  */
  public void setDT_AFAVOR(String newvalue)
  {
    fieldDT_AFAVOR.setString(newvalue);
  }

  /**
  * Get value of field DT_AFAVOR as a String.
  */
  public String getDT_AFAVOR()
  {
    return fieldDT_AFAVOR.getString();
  }

  /**
  * Set numeric field DT_AFAVOR using a BigDecimal value.
  */
  public void setDT_AFAVOR(BigDecimal newvalue)
  {
    fieldDT_AFAVOR.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field DT_AFAVOR as a BigDecimal.
  */
  public BigDecimal getBigDecimalDT_AFAVOR()
  {
    return fieldDT_AFAVOR.getBigDecimal();
  }

  /**
  * Set field DT_ACARGO using a String value.
  */
  public void setDT_ACARGO(String newvalue)
  {
    fieldDT_ACARGO.setString(newvalue);
  }

  /**
  * Get value of field DT_ACARGO as a String.
  */
  public String getDT_ACARGO()
  {
    return fieldDT_ACARGO.getString();
  }

  /**
  * Set numeric field DT_ACARGO using a BigDecimal value.
  */
  public void setDT_ACARGO(BigDecimal newvalue)
  {
    fieldDT_ACARGO.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field DT_ACARGO as a BigDecimal.
  */
  public BigDecimal getBigDecimalDT_ACARGO()
  {
    return fieldDT_ACARGO.getBigDecimal();
  }

  /**
  * Set field DT_PARACT using a String value.
  */
  public void setDT_PARACT(String newvalue)
  {
    fieldDT_PARACT.setString(newvalue);
  }

  /**
  * Get value of field DT_PARACT as a String.
  */
  public String getDT_PARACT()
  {
    return fieldDT_PARACT.getString();
  }

  /**
  * Set numeric field DT_PARACT using a BigDecimal value.
  */
  public void setDT_PARACT(BigDecimal newvalue)
  {
    fieldDT_PARACT.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field DT_PARACT as a BigDecimal.
  */
  public BigDecimal getBigDecimalDT_PARACT()
  {
    return fieldDT_PARACT.getBigDecimal();
  }

  /**
  * Set field DT_RCARGO using a String value.
  */
  public void setDT_RCARGO(String newvalue)
  {
    fieldDT_RCARGO.setString(newvalue);
  }

  /**
  * Get value of field DT_RCARGO as a String.
  */
  public String getDT_RCARGO()
  {
    return fieldDT_RCARGO.getString();
  }

  /**
  * Set numeric field DT_RCARGO using a BigDecimal value.
  */
  public void setDT_RCARGO(BigDecimal newvalue)
  {
    fieldDT_RCARGO.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field DT_RCARGO as a BigDecimal.
  */
  public BigDecimal getBigDecimalDT_RCARGO()
  {
    return fieldDT_RCARGO.getBigDecimal();
  }

  /**
  * Set field DT_MULTA using a String value.
  */
  public void setDT_MULTA(String newvalue)
  {
    fieldDT_MULTA.setString(newvalue);
  }

  /**
  * Get value of field DT_MULTA as a String.
  */
  public String getDT_MULTA()
  {
    return fieldDT_MULTA.getString();
  }

  /**
  * Set numeric field DT_MULTA using a BigDecimal value.
  */
  public void setDT_MULTA(BigDecimal newvalue)
  {
    fieldDT_MULTA.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field DT_MULTA as a BigDecimal.
  */
  public BigDecimal getBigDecimalDT_MULTA()
  {
    return fieldDT_MULTA.getBigDecimal();
  }

  /**
  * Set field DT_TOTCON using a String value.
  */
  public void setDT_TOTCON(String newvalue)
  {
    fieldDT_TOTCON.setString(newvalue);
  }

  /**
  * Get value of field DT_TOTCON as a String.
  */
  public String getDT_TOTCON()
  {
    return fieldDT_TOTCON.getString();
  }

  /**
  * Set numeric field DT_TOTCON using a BigDecimal value.
  */
  public void setDT_TOTCON(BigDecimal newvalue)
  {
    fieldDT_TOTCON.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field DT_TOTCON as a BigDecimal.
  */
  public BigDecimal getBigDecimalDT_TOTCON()
  {
    return fieldDT_TOTCON.getBigDecimal();
  }

  /**
  * Set field DT_CRSALA using a String value.
  */
  public void setDT_CRSALA(String newvalue)
  {
    fieldDT_CRSALA.setString(newvalue);
  }

  /**
  * Get value of field DT_CRSALA as a String.
  */
  public String getDT_CRSALA()
  {
    return fieldDT_CRSALA.getString();
  }

  /**
  * Set numeric field DT_CRSALA using a BigDecimal value.
  */
  public void setDT_CRSALA(BigDecimal newvalue)
  {
    fieldDT_CRSALA.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field DT_CRSALA as a BigDecimal.
  */
  public BigDecimal getBigDecimalDT_CRSALA()
  {
    return fieldDT_CRSALA.getBigDecimal();
  }

  /**
  * Set field DT_COMPEN using a String value.
  */
  public void setDT_COMPEN(String newvalue)
  {
    fieldDT_COMPEN.setString(newvalue);
  }

  /**
  * Get value of field DT_COMPEN as a String.
  */
  public String getDT_COMPEN()
  {
    return fieldDT_COMPEN.getString();
  }

  /**
  * Set numeric field DT_COMPEN using a BigDecimal value.
  */
  public void setDT_COMPEN(BigDecimal newvalue)
  {
    fieldDT_COMPEN.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field DT_COMPEN as a BigDecimal.
  */
  public BigDecimal getBigDecimalDT_COMPEN()
  {
    return fieldDT_COMPEN.getBigDecimal();
  }

  /**
  * Set field DT_CRDIES using a String value.
  */
  public void setDT_CRDIES(String newvalue)
  {
    fieldDT_CRDIES.setString(newvalue);
  }

  /**
  * Get value of field DT_CRDIES as a String.
  */
  public String getDT_CRDIES()
  {
    return fieldDT_CRDIES.getString();
  }

  /**
  * Set numeric field DT_CRDIES using a BigDecimal value.
  */
  public void setDT_CRDIES(BigDecimal newvalue)
  {
    fieldDT_CRDIES.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field DT_CRDIES as a BigDecimal.
  */
  public BigDecimal getBigDecimalDT_CRDIES()
  {
    return fieldDT_CRDIES.getBigDecimal();
  }

  /**
  * Set field DT_DIEAUT using a String value.
  */
  public void setDT_DIEAUT(String newvalue)
  {
    fieldDT_DIEAUT.setString(newvalue);
  }

  /**
  * Get value of field DT_DIEAUT as a String.
  */
  public String getDT_DIEAUT()
  {
    return fieldDT_DIEAUT.getString();
  }

  /**
  * Set numeric field DT_DIEAUT using a BigDecimal value.
  */
  public void setDT_DIEAUT(BigDecimal newvalue)
  {
    fieldDT_DIEAUT.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field DT_DIEAUT as a BigDecimal.
  */
  public BigDecimal getBigDecimalDT_DIEAUT()
  {
    return fieldDT_DIEAUT.getBigDecimal();
  }

  /**
  * Set field DT_CARRET using a String value.
  */
  public void setDT_CARRET(String newvalue)
  {
    fieldDT_CARRET.setString(newvalue);
  }

  /**
  * Get value of field DT_CARRET as a String.
  */
  public String getDT_CARRET()
  {
    return fieldDT_CARRET.getString();
  }

  /**
  * Set numeric field DT_CARRET using a BigDecimal value.
  */
  public void setDT_CARRET(BigDecimal newvalue)
  {
    fieldDT_CARRET.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field DT_CARRET as a BigDecimal.
  */
  public BigDecimal getBigDecimalDT_CARRET()
  {
    return fieldDT_CARRET.getBigDecimal();
  }

  /**
  * Set field DT_AGAVE using a String value.
  */
  public void setDT_AGAVE(String newvalue)
  {
    fieldDT_AGAVE.setString(newvalue);
  }

  /**
  * Get value of field DT_AGAVE as a String.
  */
  public String getDT_AGAVE()
  {
    return fieldDT_AGAVE.getString();
  }

  /**
  * Set numeric field DT_AGAVE using a BigDecimal value.
  */
  public void setDT_AGAVE(BigDecimal newvalue)
  {
    fieldDT_AGAVE.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field DT_AGAVE as a BigDecimal.
  */
  public BigDecimal getBigDecimalDT_AGAVE()
  {
    return fieldDT_AGAVE.getBigDecimal();
  }

  /**
  * Set field DT_OTREST using a String value.
  */
  public void setDT_OTREST(String newvalue)
  {
    fieldDT_OTREST.setString(newvalue);
  }

  /**
  * Get value of field DT_OTREST as a String.
  */
  public String getDT_OTREST()
  {
    return fieldDT_OTREST.getString();
  }

  /**
  * Set numeric field DT_OTREST using a BigDecimal value.
  */
  public void setDT_OTREST(BigDecimal newvalue)
  {
    fieldDT_OTREST.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field DT_OTREST as a BigDecimal.
  */
  public BigDecimal getBigDecimalDT_OTREST()
  {
    return fieldDT_OTREST.getBigDecimal();
  }

  /**
  * Set field DT_CERTIF using a String value.
  */
  public void setDT_CERTIF(String newvalue)
  {
    fieldDT_CERTIF.setString(newvalue);
  }

  /**
  * Get value of field DT_CERTIF as a String.
  */
  public String getDT_CERTIF()
  {
    return fieldDT_CERTIF.getString();
  }

  /**
  * Set numeric field DT_CERTIF using a BigDecimal value.
  */
  public void setDT_CERTIF(BigDecimal newvalue)
  {
    fieldDT_CERTIF.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field DT_CERTIF as a BigDecimal.
  */
  public BigDecimal getBigDecimalDT_CERTIF()
  {
    return fieldDT_CERTIF.getBigDecimal();
  }

  /**
  * Set field DT_MONANT using a String value.
  */
  public void setDT_MONANT(String newvalue)
  {
    fieldDT_MONANT.setString(newvalue);
  }

  /**
  * Get value of field DT_MONANT as a String.
  */
  public String getDT_MONANT()
  {
    return fieldDT_MONANT.getString();
  }

  /**
  * Set numeric field DT_MONANT using a BigDecimal value.
  */
  public void setDT_MONANT(BigDecimal newvalue)
  {
    fieldDT_MONANT.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field DT_MONANT as a BigDecimal.
  */
  public BigDecimal getBigDecimalDT_MONANT()
  {
    return fieldDT_MONANT.getBigDecimal();
  }

  /**
  * Set field DT_TOTAPL using a String value.
  */
  public void setDT_TOTAPL(String newvalue)
  {
    fieldDT_TOTAPL.setString(newvalue);
  }

  /**
  * Get value of field DT_TOTAPL as a String.
  */
  public String getDT_TOTAPL()
  {
    return fieldDT_TOTAPL.getString();
  }

  /**
  * Set numeric field DT_TOTAPL using a BigDecimal value.
  */
  public void setDT_TOTAPL(BigDecimal newvalue)
  {
    fieldDT_TOTAPL.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field DT_TOTAPL as a BigDecimal.
  */
  public BigDecimal getBigDecimalDT_TOTAPL()
  {
    return fieldDT_TOTAPL.getBigDecimal();
  }

  /**
  * Set field DT_CANCAR using a String value.
  */
  public void setDT_CANCAR(String newvalue)
  {
    fieldDT_CANCAR.setString(newvalue);
  }

  /**
  * Get value of field DT_CANCAR as a String.
  */
  public String getDT_CANCAR()
  {
    return fieldDT_CANCAR.getString();
  }

  /**
  * Set numeric field DT_CANCAR using a BigDecimal value.
  */
  public void setDT_CANCAR(BigDecimal newvalue)
  {
    fieldDT_CANCAR.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field DT_CANCAR as a BigDecimal.
  */
  public BigDecimal getBigDecimalDT_CANCAR()
  {
    return fieldDT_CANCAR.getBigDecimal();
  }

  /**
  * Set field DT_PARCIA using a String value.
  */
  public void setDT_PARCIA(String newvalue)
  {
    fieldDT_PARCIA.setString(newvalue);
  }

  /**
  * Get value of field DT_PARCIA as a String.
  */
  public String getDT_PARCIA()
  {
    return fieldDT_PARCIA.getString();
  }

  /**
  * Set numeric field DT_PARCIA using a BigDecimal value.
  */
  public void setDT_PARCIA(BigDecimal newvalue)
  {
    fieldDT_PARCIA.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field DT_PARCIA as a BigDecimal.
  */
  public BigDecimal getBigDecimalDT_PARCIA()
  {
    return fieldDT_PARCIA.getBigDecimal();
  }

  /**
  * Set field DT_NOPARC using a String value.
  */
  public void setDT_NOPARC(String newvalue)
  {
    fieldDT_NOPARC.setString(newvalue);
  }

  /**
  * Get value of field DT_NOPARC as a String.
  */
  public String getDT_NOPARC()
  {
    return fieldDT_NOPARC.getString();
  }

  /**
  * Set numeric field DT_NOPARC using a BigDecimal value.
  */
  public void setDT_NOPARC(BigDecimal newvalue)
  {
    fieldDT_NOPARC.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field DT_NOPARC as a BigDecimal.
  */
  public BigDecimal getBigDecimalDT_NOPARC()
  {
    return fieldDT_NOPARC.getBigDecimal();
  }

  /**
  * Set field DT_PAGEXC using a String value.
  */
  public void setDT_PAGEXC(String newvalue)
  {
    fieldDT_PAGEXC.setString(newvalue);
  }

  /**
  * Get value of field DT_PAGEXC as a String.
  */
  public String getDT_PAGEXC()
  {
    return fieldDT_PAGEXC.getString();
  }

  /**
  * Set numeric field DT_PAGEXC using a BigDecimal value.
  */
  public void setDT_PAGEXC(BigDecimal newvalue)
  {
    fieldDT_PAGEXC.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field DT_PAGEXC as a BigDecimal.
  */
  public BigDecimal getBigDecimalDT_PAGEXC()
  {
    return fieldDT_PAGEXC.getBigDecimal();
  }

  /**
  * Set field DT_CANPAG using a String value.
  */
  public void setDT_CANPAG(String newvalue)
  {
    fieldDT_CANPAG.setString(newvalue);
  }

  /**
  * Get value of field DT_CANPAG as a String.
  */
  public String getDT_CANPAG()
  {
    return fieldDT_CANPAG.getString();
  }

  /**
  * Set numeric field DT_CANPAG using a BigDecimal value.
  */
  public void setDT_CANPAG(BigDecimal newvalue)
  {
    fieldDT_CANPAG.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field DT_CANPAG as a BigDecimal.
  */
  public BigDecimal getBigDecimalDT_CANPAG()
  {
    return fieldDT_CANPAG.getBigDecimal();
  }

  /**
  * Set field DT_UTILID using a String value.
  */
  public void setDT_UTILID(String newvalue)
  {
    fieldDT_UTILID.setString(newvalue);
  }

  /**
  * Get value of field DT_UTILID as a String.
  */
  public String getDT_UTILID()
  {
    return fieldDT_UTILID.getString();
  }

  /**
  * Set numeric field DT_UTILID using a BigDecimal value.
  */
  public void setDT_UTILID(BigDecimal newvalue)
  {
    fieldDT_UTILID.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field DT_UTILID as a BigDecimal.
  */
  public BigDecimal getBigDecimalDT_UTILID()
  {
    return fieldDT_UTILID.getBigDecimal();
  }

  /**
  * Set field DT_FECDEC using a String value.
  */
  public void setDT_FECDEC(String newvalue)
  {
    fieldDT_FECDEC.setString(newvalue);
  }

  /**
  * Get value of field DT_FECDEC as a String.
  */
  public String getDT_FECDEC()
  {
    return fieldDT_FECDEC.getString();
  }

  /**
  * Set field DT_NUMSAT using a String value.
  */
  public void setDT_NUMSAT(String newvalue)
  {
    fieldDT_NUMSAT.setString(newvalue);
  }

  /**
  * Get value of field DT_NUMSAT as a String.
  */
  public String getDT_NUMSAT()
  {
    return fieldDT_NUMSAT.getString();
  }

  /**
  * Set field DT_NUMCRE using a String value.
  */
  public void setDT_NUMCRE(String newvalue)
  {
    fieldDT_NUMCRE.setString(newvalue);
  }

  /**
  * Get value of field DT_NUMCRE as a String.
  */
  public String getDT_NUMCRE()
  {
    return fieldDT_NUMCRE.getString();
  }

  /**
  * Set numeric field DT_NUMCRE using a BigDecimal value.
  */
  public void setDT_NUMCRE(BigDecimal newvalue)
  {
    fieldDT_NUMCRE.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field DT_NUMCRE as a BigDecimal.
  */
  public BigDecimal getBigDecimalDT_NUMCRE()
  {
    return fieldDT_NUMCRE.getBigDecimal();
  }

  /**
  * Set field DT_ENTIDA using a String value.
  */
  public void setDT_ENTIDA(String newvalue)
  {
    fieldDT_ENTIDA.setString(newvalue);
  }

  /**
  * Get value of field DT_ENTIDA as a String.
  */
  public String getDT_ENTIDA()
  {
    return fieldDT_ENTIDA.getString();
  }

  /**
  * Set numeric field DT_ENTIDA using a BigDecimal value.
  */
  public void setDT_ENTIDA(BigDecimal newvalue)
  {
    fieldDT_ENTIDA.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field DT_ENTIDA as a BigDecimal.
  */
  public BigDecimal getBigDecimalDT_ENTIDA()
  {
    return fieldDT_ENTIDA.getBigDecimal();
  }

  /**
  * Set field DT_DEPEND using a String value.
  */
  public void setDT_DEPEND(String newvalue)
  {
    fieldDT_DEPEND.setString(newvalue);
  }

  /**
  * Get value of field DT_DEPEND as a String.
  */
  public String getDT_DEPEND()
  {
    return fieldDT_DEPEND.getString();
  }

  /**
  * Set numeric field DT_DEPEND using a BigDecimal value.
  */
  public void setDT_DEPEND(BigDecimal newvalue)
  {
    fieldDT_DEPEND.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field DT_DEPEND as a BigDecimal.
  */
  public BigDecimal getBigDecimalDT_DEPEND()
  {
    return fieldDT_DEPEND.getBigDecimal();
  }

  /**
  * Set field DT_CONTAB using a String value.
  */
  public void setDT_CONTAB(String newvalue)
  {
    fieldDT_CONTAB.setString(newvalue);
  }

  /**
  * Get value of field DT_CONTAB as a String.
  */
  public String getDT_CONTAB()
  {
    return fieldDT_CONTAB.getString();
  }

  /**
  * Set numeric field DT_CONTAB using a BigDecimal value.
  */
  public void setDT_CONTAB(BigDecimal newvalue)
  {
    fieldDT_CONTAB.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field DT_CONTAB as a BigDecimal.
  */
  public BigDecimal getBigDecimalDT_CONTAB()
  {
    return fieldDT_CONTAB.getBigDecimal();
  }

  /**
  * Set field DT_CADENA using a String value.
  */
  public void setDT_CADENA(String newvalue)
  {
    fieldDT_CADENA.setString(newvalue);
  }

  /**
  * Get value of field DT_CADENA as a String.
  */
  public String getDT_CADENA()
  {
    return fieldDT_CADENA.getString();
  }

  /**
  * Set field DT_DPA using a String value.
  */
  public void setDT_DPA(String newvalue)
  {
    fieldDT_DPA.setString(newvalue);
  }

  /**
  * Get value of field DT_DPA as a String.
  */
  public String getDT_DPA()
  {
    return fieldDT_DPA.getString();
  }

  /**
  * Set numeric field DT_DPA using a BigDecimal value.
  */
  public void setDT_DPA(BigDecimal newvalue)
  {
    fieldDT_DPA.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field DT_DPA as a BigDecimal.
  */
  public BigDecimal getBigDecimalDT_DPA()
  {
    return fieldDT_DPA.getBigDecimal();
  }

  /**
  * Set field DT_CAMPO1 using a String value.
  */
  public void setDT_CAMPO1(String newvalue)
  {
    fieldDT_CAMPO1.setString(newvalue);
  }

  /**
  * Get value of field DT_CAMPO1 as a String.
  */
  public String getDT_CAMPO1()
  {
    return fieldDT_CAMPO1.getString();
  }

  /**
  * Set numeric field DT_CAMPO1 using a BigDecimal value.
  */
  public void setDT_CAMPO1(BigDecimal newvalue)
  {
    fieldDT_CAMPO1.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field DT_CAMPO1 as a BigDecimal.
  */
  public BigDecimal getBigDecimalDT_CAMPO1()
  {
    return fieldDT_CAMPO1.getBigDecimal();
  }

  /**
  * Set field DT_CAMPO2 using a String value.
  */
  public void setDT_CAMPO2(String newvalue)
  {
    fieldDT_CAMPO2.setString(newvalue);
  }

  /**
  * Get value of field DT_CAMPO2 as a String.
  */
  public String getDT_CAMPO2()
  {
    return fieldDT_CAMPO2.getString();
  }

  /**
  * Set numeric field DT_CAMPO2 using a BigDecimal value.
  */
  public void setDT_CAMPO2(BigDecimal newvalue)
  {
    fieldDT_CAMPO2.setBigDecimal(newvalue);
  }

  /**
  * Return value of numeric field DT_CAMPO2 as a BigDecimal.
  */
  public BigDecimal getBigDecimalDT_CAMPO2()
  {
    return fieldDT_CAMPO2.getBigDecimal();
  }

  /**
  * Set field DT_CAMPO3 using a String value.
  */
  public void setDT_CAMPO3(String newvalue)
  {
    fieldDT_CAMPO3.setString(newvalue);
  }

  /**
  * Get value of field DT_CAMPO3 as a String.
  */
  public String getDT_CAMPO3()
  {
    return fieldDT_CAMPO3.getString();
  }

  /**
  * Set field DT_CAMPO4 using a String value.
  */
  public void setDT_CAMPO4(String newvalue)
  {
    fieldDT_CAMPO4.setString(newvalue);
  }

  /**
  * Get value of field DT_CAMPO4 as a String.
  */
  public String getDT_CAMPO4()
  {
    return fieldDT_CAMPO4.getString();
  }

  /**
  * Set field DT_CAMPO5 using a String value.
  */
  public void setDT_CAMPO5(String newvalue)
  {
    fieldDT_CAMPO5.setString(newvalue);
  }

  /**
  * Get value of field DT_CAMPO5 as a String.
  */
  public String getDT_CAMPO5()
  {
    return fieldDT_CAMPO5.getString();
  }

}
