/**
 *  This Class was created By Luis Velando
 *  Copyright Datapro Inc. 1999
 **/

package com.afirme.afirmenet.ibs.messages;

import java.math.BigDecimal;

import com.datapro.sockets.CharacterField;
import com.datapro.sockets.DecimalField;
import com.datapro.sockets.MessageField;
import com.datapro.sockets.MessageRecord;

/**
 * Class generated by AS/400 CRTCLASS command from EWD0001S physical file
 * definition.
 */

public class EWD0001SMessage extends MessageRecord {
	final int FIELDCOUNT = 8;
	private DecimalField fieldSWDCUN = null;
	private CharacterField fieldSWDNA1 = null;
	private CharacterField fieldSWDSHN = null;
	private CharacterField fieldSWDIDN = null;
	private CharacterField fieldSWDTID = null;
	private CharacterField fieldSWDPID = null;
	private DecimalField fieldSWDREC = null;
	private CharacterField fieldSWDOPE = null;

	/**
	 * Constructor for EWD0001SMessage.
	 */
	public EWD0001SMessage() {
		createFields();
		initialize();
		setFormatNameBytes();
	}

	/**
	 * Create fields for this message. This method implements the abstract
	 * method in the MessageRecord superclass.
	 */
	protected void createFields() {
		recordsize = 102;
		message = new byte[getByteLength()];
		formatname = "EWD0001S";
		fieldnames = new String[FIELDCOUNT];
		fields = new MessageField[FIELDCOUNT];

		fieldnames[0] = "SWDCUN";
		fields[0] = fieldSWDCUN = new DecimalField(message, HEADERSIZE + 0, 10,
				0);
		fieldnames[1] = "SWDNA1";
		fields[1] = fieldSWDNA1 = new CharacterField(message, HEADERSIZE + 10,
				45);
		fieldnames[2] = "SWDSHN";
		fields[2] = fieldSWDSHN = new CharacterField(message, HEADERSIZE + 55,
				15);
		fieldnames[3] = "SWDIDN";
		fields[3] = fieldSWDIDN = new CharacterField(message, HEADERSIZE + 70,
				15);
		fieldnames[4] = "SWDTID";
		fields[4] = fieldSWDTID = new CharacterField(message, HEADERSIZE + 85,
				4);
		fieldnames[5] = "SWDPID";
		fields[5] = fieldSWDPID = new CharacterField(message, HEADERSIZE + 89,
				4);
		fieldnames[6] = "SWDREC";
		fields[6] = fieldSWDREC = new DecimalField(message, HEADERSIZE + 93, 8,
				0);
		fieldnames[7] = "SWDOPE";
		fields[7] = fieldSWDOPE = new CharacterField(message, HEADERSIZE + 101,
				1);
	}

	/**
	 * Return value of numeric field SWDCUN as a BigDecimal.
	 */
	public BigDecimal getBigDecimalSWDCUN() {
		return fieldSWDCUN.getBigDecimal();
	}

	/**
	 * Return value of numeric field SWDREC as a BigDecimal.
	 */
	public BigDecimal getBigDecimalSWDREC() {
		return fieldSWDREC.getBigDecimal();
	}

	/**
	 * Get value of field SWDCUN as a String.
	 */
	public String getSWDCUN() {
		return fieldSWDCUN.getString();
	}

	/**
	 * Get value of field SWDIDN as a String.
	 */
	public String getSWDIDN() {
		return fieldSWDIDN.getString();
	}

	/**
	 * Get value of field SWDNA1 as a String.
	 */
	public String getSWDNA1() {
		return fieldSWDNA1.getString();
	}

	/**
	 * Get value of field SWDOPE as a String.
	 */
	public String getSWDOPE() {
		return fieldSWDOPE.getString();
	}

	/**
	 * Get value of field SWDPID as a String.
	 */
	public String getSWDPID() {
		return fieldSWDPID.getString();
	}

	/**
	 * Get value of field SWDREC as a String.
	 */
	public String getSWDREC() {
		return fieldSWDREC.getString();
	}

	/**
	 * Get value of field SWDSHN as a String.
	 */
	public String getSWDSHN() {
		return fieldSWDSHN.getString();
	}

	/**
	 * Get value of field SWDTID as a String.
	 */
	public String getSWDTID() {
		return fieldSWDTID.getString();
	}

	/**
	 * Set field SWDCUN using a String value.
	 */
	public void setSWDCUN(String newvalue) {
		fieldSWDCUN.setString(newvalue);
	}

	/**
	 * Set numeric field SWDCUN using a BigDecimal value.
	 */
	public void setSWDCUN(BigDecimal newvalue) {
		fieldSWDCUN.setBigDecimal(newvalue);
	}

	/**
	 * Set field SWDIDN using a String value.
	 */
	public void setSWDIDN(String newvalue) {
		fieldSWDIDN.setString(newvalue);
	}

	/**
	 * Set field SWDNA1 using a String value.
	 */
	public void setSWDNA1(String newvalue) {
		fieldSWDNA1.setString(newvalue);
	}

	/**
	 * Set field SWDOPE using a String value.
	 */
	public void setSWDOPE(String newvalue) {
		fieldSWDOPE.setString(newvalue);
	}

	/**
	 * Set field SWDPID using a String value.
	 */
	public void setSWDPID(String newvalue) {
		fieldSWDPID.setString(newvalue);
	}

	/**
	 * Set field SWDREC using a String value.
	 */
	public void setSWDREC(String newvalue) {
		fieldSWDREC.setString(newvalue);
	}

	/**
	 * Set numeric field SWDREC using a BigDecimal value.
	 */
	public void setSWDREC(BigDecimal newvalue) {
		fieldSWDREC.setBigDecimal(newvalue);
	}

	/**
	 * Set field SWDSHN using a String value.
	 */
	public void setSWDSHN(String newvalue) {
		fieldSWDSHN.setString(newvalue);
	}

	/**
	 * Set field SWDTID using a String value.
	 */
	public void setSWDTID(String newvalue) {
		fieldSWDTID.setString(newvalue);
	}
}