/**
 *  This Class was created By Luis Velando
 *  Copyright Datapro Inc. 1999
 **/

package com.afirme.afirmenet.ibs.messages;

import java.math.BigDecimal;

import com.datapro.sockets.CharacterField;
import com.datapro.sockets.DecimalField;
import com.datapro.sockets.MessageField;
import com.datapro.sockets.MessageRecord;

/**
 * Class generated by AS/400 CRTCLASS command from FEMSTDSJV physical file
 * definition.
 */

public class FEMSTDSJVMessage extends MessageRecord {
	final int FIELDCOUNT = 16;
	private CharacterField fieldFEMUSER = null;
	private DecimalField fieldFEMFEMACC = null;
	private CharacterField fieldFEMFEMCCY = null;
	private DecimalField fieldFEMFEMSOA = null;
	private DecimalField fieldFEMFEMEXR = null;
	private DecimalField fieldFEMFEMDD1 = null;
	private DecimalField fieldFEMFEMDD2 = null;
	private DecimalField fieldFEMFEMDD3 = null;
	private DecimalField fieldFEMFEMVD1 = null;
	private DecimalField fieldFEMFEMVD2 = null;
	private DecimalField fieldFEMFEMVD3 = null;
	private CharacterField fieldFEMFEMDCY = null;
	private DecimalField fieldFEMFEMDOA = null;
	private DecimalField fieldFEMFEMDEX = null;
	private CharacterField fieldFEMFEMTHR = null;
	private CharacterField fieldFEMFEMPTP = null;

	/**
	 * Constructor for FEMSTDSJVMessage.
	 */
	public FEMSTDSJVMessage() {
		createFields();
		initialize();
		setFormatNameBytes();
	}

	/**
	 * Create fields for this message. This method implements the abstract
	 * method in the MessageRecord superclass.
	 */
	protected void createFields() {
		recordsize = 123;
		message = new byte[getByteLength()];
		formatname = "FEMSTDSJV";
		fieldnames = new String[FIELDCOUNT];
		fields = new MessageField[FIELDCOUNT];

		fieldnames[0] = "FEMUSER";
		fields[0] = fieldFEMUSER = new CharacterField(message, HEADERSIZE + 0,
				10);
		fieldnames[1] = "FEMFEMACC";
		fields[1] = fieldFEMFEMACC = new DecimalField(message, HEADERSIZE + 10,
				13, 0);
		fieldnames[2] = "FEMFEMCCY";
		fields[2] = fieldFEMFEMCCY = new CharacterField(message,
				HEADERSIZE + 23, 3);
		fieldnames[3] = "FEMFEMSOA";
		fields[3] = fieldFEMFEMSOA = new DecimalField(message, HEADERSIZE + 26,
				17, 2);
		fieldnames[4] = "FEMFEMEXR";
		fields[4] = fieldFEMFEMEXR = new DecimalField(message, HEADERSIZE + 43,
				13, 6);
		fieldnames[5] = "FEMFEMDD1";
		fields[5] = fieldFEMFEMDD1 = new DecimalField(message, HEADERSIZE + 56,
				3, 0);
		fieldnames[6] = "FEMFEMDD2";
		fields[6] = fieldFEMFEMDD2 = new DecimalField(message, HEADERSIZE + 59,
				3, 0);
		fieldnames[7] = "FEMFEMDD3";
		fields[7] = fieldFEMFEMDD3 = new DecimalField(message, HEADERSIZE + 62,
				3, 0);
		fieldnames[8] = "FEMFEMVD1";
		fields[8] = fieldFEMFEMVD1 = new DecimalField(message, HEADERSIZE + 65,
				3, 0);
		fieldnames[9] = "FEMFEMVD2";
		fields[9] = fieldFEMFEMVD2 = new DecimalField(message, HEADERSIZE + 68,
				3, 0);
		fieldnames[10] = "FEMFEMVD3";
		fields[10] = fieldFEMFEMVD3 = new DecimalField(message,
				HEADERSIZE + 71, 3, 0);
		fieldnames[11] = "FEMFEMDCY";
		fields[11] = fieldFEMFEMDCY = new CharacterField(message,
				HEADERSIZE + 74, 3);
		fieldnames[12] = "FEMFEMDOA";
		fields[12] = fieldFEMFEMDOA = new DecimalField(message,
				HEADERSIZE + 77, 17, 2);
		fieldnames[13] = "FEMFEMDEX";
		fields[13] = fieldFEMFEMDEX = new DecimalField(message,
				HEADERSIZE + 94, 13, 6);
		fieldnames[14] = "FEMFEMTHR";
		fields[14] = fieldFEMFEMTHR = new CharacterField(message,
				HEADERSIZE + 107, 15);
		fieldnames[15] = "FEMFEMPTP";
		fields[15] = fieldFEMFEMPTP = new CharacterField(message,
				HEADERSIZE + 122, 1);
	}

	/**
	 * Return value of numeric field FEMFEMACC as a BigDecimal.
	 */
	public BigDecimal getBigDecimalFEMFEMACC() {
		return fieldFEMFEMACC.getBigDecimal();
	}

	/**
	 * Return value of numeric field FEMFEMDD1 as a BigDecimal.
	 */
	public BigDecimal getBigDecimalFEMFEMDD1() {
		return fieldFEMFEMDD1.getBigDecimal();
	}

	/**
	 * Return value of numeric field FEMFEMDD2 as a BigDecimal.
	 */
	public BigDecimal getBigDecimalFEMFEMDD2() {
		return fieldFEMFEMDD2.getBigDecimal();
	}

	/**
	 * Return value of numeric field FEMFEMDD3 as a BigDecimal.
	 */
	public BigDecimal getBigDecimalFEMFEMDD3() {
		return fieldFEMFEMDD3.getBigDecimal();
	}

	/**
	 * Return value of numeric field FEMFEMDEX as a BigDecimal.
	 */
	public BigDecimal getBigDecimalFEMFEMDEX() {
		return fieldFEMFEMDEX.getBigDecimal();
	}

	/**
	 * Return value of numeric field FEMFEMDOA as a BigDecimal.
	 */
	public BigDecimal getBigDecimalFEMFEMDOA() {
		return fieldFEMFEMDOA.getBigDecimal();
	}

	/**
	 * Return value of numeric field FEMFEMEXR as a BigDecimal.
	 */
	public BigDecimal getBigDecimalFEMFEMEXR() {
		return fieldFEMFEMEXR.getBigDecimal();
	}

	/**
	 * Return value of numeric field FEMFEMSOA as a BigDecimal.
	 */
	public BigDecimal getBigDecimalFEMFEMSOA() {
		return fieldFEMFEMSOA.getBigDecimal();
	}

	/**
	 * Return value of numeric field FEMFEMVD1 as a BigDecimal.
	 */
	public BigDecimal getBigDecimalFEMFEMVD1() {
		return fieldFEMFEMVD1.getBigDecimal();
	}

	/**
	 * Return value of numeric field FEMFEMVD2 as a BigDecimal.
	 */
	public BigDecimal getBigDecimalFEMFEMVD2() {
		return fieldFEMFEMVD2.getBigDecimal();
	}

	/**
	 * Return value of numeric field FEMFEMVD3 as a BigDecimal.
	 */
	public BigDecimal getBigDecimalFEMFEMVD3() {
		return fieldFEMFEMVD3.getBigDecimal();
	}

	/**
	 * Get value of field FEMFEMACC as a String.
	 */
	public String getFEMFEMACC() {
		return fieldFEMFEMACC.getString();
	}

	/**
	 * Get value of field FEMFEMCCY as a String.
	 */
	public String getFEMFEMCCY() {
		return fieldFEMFEMCCY.getString();
	}

	/**
	 * Get value of field FEMFEMDCY as a String.
	 */
	public String getFEMFEMDCY() {
		return fieldFEMFEMDCY.getString();
	}

	/**
	 * Get value of field FEMFEMDD1 as a String.
	 */
	public String getFEMFEMDD1() {
		return fieldFEMFEMDD1.getString();
	}

	/**
	 * Get value of field FEMFEMDD2 as a String.
	 */
	public String getFEMFEMDD2() {
		return fieldFEMFEMDD2.getString();
	}

	/**
	 * Get value of field FEMFEMDD3 as a String.
	 */
	public String getFEMFEMDD3() {
		return fieldFEMFEMDD3.getString();
	}

	/**
	 * Get value of field FEMFEMDEX as a String.
	 */
	public String getFEMFEMDEX() {
		return fieldFEMFEMDEX.getString();
	}

	/**
	 * Get value of field FEMFEMDOA as a String.
	 */
	public String getFEMFEMDOA() {
		return fieldFEMFEMDOA.getString();
	}

	/**
	 * Get value of field FEMFEMEXR as a String.
	 */
	public String getFEMFEMEXR() {
		return fieldFEMFEMEXR.getString();
	}

	/**
	 * Get value of field FEMFEMPTP as a String.
	 */
	public String getFEMFEMPTP() {
		return fieldFEMFEMPTP.getString();
	}

	/**
	 * Get value of field FEMFEMSOA as a String.
	 */
	public String getFEMFEMSOA() {
		return fieldFEMFEMSOA.getString();
	}

	/**
	 * Get value of field FEMFEMTHR as a String.
	 */
	public String getFEMFEMTHR() {
		return fieldFEMFEMTHR.getString();
	}

	/**
	 * Get value of field FEMFEMVD1 as a String.
	 */
	public String getFEMFEMVD1() {
		return fieldFEMFEMVD1.getString();
	}

	/**
	 * Get value of field FEMFEMVD2 as a String.
	 */
	public String getFEMFEMVD2() {
		return fieldFEMFEMVD2.getString();
	}

	/**
	 * Get value of field FEMFEMVD3 as a String.
	 */
	public String getFEMFEMVD3() {
		return fieldFEMFEMVD3.getString();
	}

	/**
	 * Get value of field FEMUSER as a String.
	 */
	public String getFEMUSER() {
		return fieldFEMUSER.getString();
	}

	/**
	 * Set field FEMFEMACC using a String value.
	 */
	public void setFEMFEMACC(String newvalue) {
		fieldFEMFEMACC.setString(newvalue);
	}

	/**
	 * Set numeric field FEMFEMACC using a BigDecimal value.
	 */
	public void setFEMFEMACC(BigDecimal newvalue) {
		fieldFEMFEMACC.setBigDecimal(newvalue);
	}

	/**
	 * Set field FEMFEMCCY using a String value.
	 */
	public void setFEMFEMCCY(String newvalue) {
		fieldFEMFEMCCY.setString(newvalue);
	}

	/**
	 * Set field FEMFEMDCY using a String value.
	 */
	public void setFEMFEMDCY(String newvalue) {
		fieldFEMFEMDCY.setString(newvalue);
	}

	/**
	 * Set field FEMFEMDD1 using a String value.
	 */
	public void setFEMFEMDD1(String newvalue) {
		fieldFEMFEMDD1.setString(newvalue);
	}

	/**
	 * Set numeric field FEMFEMDD1 using a BigDecimal value.
	 */
	public void setFEMFEMDD1(BigDecimal newvalue) {
		fieldFEMFEMDD1.setBigDecimal(newvalue);
	}

	/**
	 * Set field FEMFEMDD2 using a String value.
	 */
	public void setFEMFEMDD2(String newvalue) {
		fieldFEMFEMDD2.setString(newvalue);
	}

	/**
	 * Set numeric field FEMFEMDD2 using a BigDecimal value.
	 */
	public void setFEMFEMDD2(BigDecimal newvalue) {
		fieldFEMFEMDD2.setBigDecimal(newvalue);
	}

	/**
	 * Set field FEMFEMDD3 using a String value.
	 */
	public void setFEMFEMDD3(String newvalue) {
		fieldFEMFEMDD3.setString(newvalue);
	}

	/**
	 * Set numeric field FEMFEMDD3 using a BigDecimal value.
	 */
	public void setFEMFEMDD3(BigDecimal newvalue) {
		fieldFEMFEMDD3.setBigDecimal(newvalue);
	}

	/**
	 * Set field FEMFEMDEX using a String value.
	 */
	public void setFEMFEMDEX(String newvalue) {
		fieldFEMFEMDEX.setString(newvalue);
	}

	/**
	 * Set numeric field FEMFEMDEX using a BigDecimal value.
	 */
	public void setFEMFEMDEX(BigDecimal newvalue) {
		fieldFEMFEMDEX.setBigDecimal(newvalue);
	}

	/**
	 * Set field FEMFEMDOA using a String value.
	 */
	public void setFEMFEMDOA(String newvalue) {
		fieldFEMFEMDOA.setString(newvalue);
	}

	/**
	 * Set numeric field FEMFEMDOA using a BigDecimal value.
	 */
	public void setFEMFEMDOA(BigDecimal newvalue) {
		fieldFEMFEMDOA.setBigDecimal(newvalue);
	}

	/**
	 * Set field FEMFEMEXR using a String value.
	 */
	public void setFEMFEMEXR(String newvalue) {
		fieldFEMFEMEXR.setString(newvalue);
	}

	/**
	 * Set numeric field FEMFEMEXR using a BigDecimal value.
	 */
	public void setFEMFEMEXR(BigDecimal newvalue) {
		fieldFEMFEMEXR.setBigDecimal(newvalue);
	}

	/**
	 * Set field FEMFEMPTP using a String value.
	 */
	public void setFEMFEMPTP(String newvalue) {
		fieldFEMFEMPTP.setString(newvalue);
	}

	/**
	 * Set field FEMFEMSOA using a String value.
	 */
	public void setFEMFEMSOA(String newvalue) {
		fieldFEMFEMSOA.setString(newvalue);
	}

	/**
	 * Set numeric field FEMFEMSOA using a BigDecimal value.
	 */
	public void setFEMFEMSOA(BigDecimal newvalue) {
		fieldFEMFEMSOA.setBigDecimal(newvalue);
	}

	/**
	 * Set field FEMFEMTHR using a String value.
	 */
	public void setFEMFEMTHR(String newvalue) {
		fieldFEMFEMTHR.setString(newvalue);
	}

	/**
	 * Set field FEMFEMVD1 using a String value.
	 */
	public void setFEMFEMVD1(String newvalue) {
		fieldFEMFEMVD1.setString(newvalue);
	}

	/**
	 * Set numeric field FEMFEMVD1 using a BigDecimal value.
	 */
	public void setFEMFEMVD1(BigDecimal newvalue) {
		fieldFEMFEMVD1.setBigDecimal(newvalue);
	}

	/**
	 * Set field FEMFEMVD2 using a String value.
	 */
	public void setFEMFEMVD2(String newvalue) {
		fieldFEMFEMVD2.setString(newvalue);
	}

	/**
	 * Set numeric field FEMFEMVD2 using a BigDecimal value.
	 */
	public void setFEMFEMVD2(BigDecimal newvalue) {
		fieldFEMFEMVD2.setBigDecimal(newvalue);
	}

	/**
	 * Set field FEMFEMVD3 using a String value.
	 */
	public void setFEMFEMVD3(String newvalue) {
		fieldFEMFEMVD3.setString(newvalue);
	}

	/**
	 * Set numeric field FEMFEMVD3 using a BigDecimal value.
	 */
	public void setFEMFEMVD3(BigDecimal newvalue) {
		fieldFEMFEMVD3.setBigDecimal(newvalue);
	}

	/**
	 * Set field FEMUSER using a String value.
	 */
	public void setFEMUSER(String newvalue) {
		fieldFEMUSER.setString(newvalue);
	}
}