package com.afirme.afirmenet.ibs.messages;

import java.math.BigDecimal;

import com.datapro.sockets.CharacterField;
import com.datapro.sockets.DecimalField;
import com.datapro.sockets.MessageField;
import com.datapro.sockets.MessageRecord;

/**
 * Class generated by AS/400 CRTCLASS command from IIN098601 physical file
 * definition.
 * 
 * File level identifier is 1010201201032. Record format level identifier is
 * 4525883A39E6E.
 */

public class IIN098601Message extends MessageRecord {
	final int FIELDCOUNT = 10;
	private CharacterField fieldIN986USR = null;
	private CharacterField fieldIN986CCN = null;
	private CharacterField fieldIN986END = null;
	private DecimalField fieldIN986FEFC = null;
	private DecimalField fieldIN986FPOS = null;
	private DecimalField fieldIN986RPGO = null;
	private CharacterField fieldIN986DESC = null;
	private DecimalField fieldIN986DEBI = null;
	private DecimalField fieldIN986CRED = null;
	private DecimalField fieldIN986FCOR = null;

	/**
	 * Constructor for IIN098601Message.
	 */
	public IIN098601Message() {
		createFields();
		initialize();
	}

	/**
	 * Create fields for this message. This method implements the abstract
	 * method in the MessageRecord superclass.
	 */

	protected void createFields() {
		recordsize = 139;
		fileid = "1010201201032";
		recordid = "4525883A39E6E";
		message = new byte[getByteLength()];
		formatname = "IIN098601";
		fieldnames = new String[FIELDCOUNT];
		tagnames = new String[FIELDCOUNT];
		fields = new MessageField[FIELDCOUNT];

		fieldnames[0] = "IN986USR";
		tagnames[0] = "IN986USR";
		fields[0] = fieldIN986USR = new CharacterField(message, HEADERSIZE + 0,
				10, "IN986USR");
		fieldnames[1] = "IN986CCN";
		tagnames[1] = "IN986CCN";
		fields[1] = fieldIN986CCN = new CharacterField(message,
				HEADERSIZE + 10, 19, "IN986CCN");
		fieldnames[2] = "IN986END";
		tagnames[2] = "IN986END";
		fields[2] = fieldIN986END = new CharacterField(message,
				HEADERSIZE + 29, 1, "IN986END");
		fieldnames[3] = "IN986FEFC";
		tagnames[3] = "IN986FEFC";
		fields[3] = fieldIN986FEFC = new DecimalField(message, HEADERSIZE + 30,
				9, 0, "IN986FEFC");
		fieldnames[4] = "IN986FPOS";
		tagnames[4] = "IN986FPOS";
		fields[4] = fieldIN986FPOS = new DecimalField(message, HEADERSIZE + 39,
				9, 0, "IN986FPOS");
		fieldnames[5] = "IN986RPGO";
		tagnames[5] = "IN986RPGO";
		fields[5] = fieldIN986RPGO = new DecimalField(message, HEADERSIZE + 48,
				16, 0, "IN986RPGO");
		fieldnames[6] = "IN986DESC";
		tagnames[6] = "IN986DESC";
		fields[6] = fieldIN986DESC = new CharacterField(message,
				HEADERSIZE + 64, 40, "IN986DESC");
		fieldnames[7] = "IN986DEBI";
		tagnames[7] = "IN986DEBI";
		fields[7] = fieldIN986DEBI = new DecimalField(message,
				HEADERSIZE + 104, 13, 2, "IN986DEBI");
		fieldnames[8] = "IN986CRED";
		tagnames[8] = "IN986CRED";
		fields[8] = fieldIN986CRED = new DecimalField(message,
				HEADERSIZE + 117, 13, 2, "IN986CRED");
		fieldnames[9] = "IN986FCOR";
		tagnames[9] = "IN986FCOR";
		fields[9] = fieldIN986FCOR = new DecimalField(message,
				HEADERSIZE + 130, 9, 0, "IN986FCOR");
	}

	/**
	 * Return value of numeric field IN986CRED as a BigDecimal.
	 */
	public BigDecimal getBigDecimalIN986CRED() {
		return fieldIN986CRED.getBigDecimal();
	}

	/**
	 * Return value of numeric field IN986DEBI as a BigDecimal.
	 */
	public BigDecimal getBigDecimalIN986DEBI() {
		return fieldIN986DEBI.getBigDecimal();
	}

	/**
	 * Return value of numeric field IN986FCOR as a BigDecimal.
	 */
	public BigDecimal getBigDecimalIN986FCOR() {
		return fieldIN986FCOR.getBigDecimal();
	}

	/**
	 * Return value of numeric field IN986FEFC as a BigDecimal.
	 */
	public BigDecimal getBigDecimalIN986FEFC() {
		return fieldIN986FEFC.getBigDecimal();
	}

	/**
	 * Return value of numeric field IN986FPOS as a BigDecimal.
	 */
	public BigDecimal getBigDecimalIN986FPOS() {
		return fieldIN986FPOS.getBigDecimal();
	}

	/**
	 * Return value of numeric field IN986RPGO as a BigDecimal.
	 */
	public BigDecimal getBigDecimalIN986RPGO() {
		return fieldIN986RPGO.getBigDecimal();
	}

	/**
	 * Get value of field IN986CCN as a String.
	 */
	public String getIN986CCN() {
		return fieldIN986CCN.getString();
	}

	/**
	 * Get value of field IN986CRED as a String.
	 */
	public String getIN986CRED() {
		return fieldIN986CRED.getString();
	}

	/**
	 * Get value of field IN986DEBI as a String.
	 */
	public String getIN986DEBI() {
		return fieldIN986DEBI.getString();
	}

	/**
	 * Get value of field IN986DESC as a String.
	 */
	public String getIN986DESC() {
		return fieldIN986DESC.getString();
	}

	/**
	 * Get value of field IN986END as a String.
	 */
	public String getIN986END() {
		return fieldIN986END.getString();
	}

	/**
	 * Get value of field IN986FCOR as a String.
	 */
	public String getIN986FCOR() {
		return fieldIN986FCOR.getString();
	}

	/**
	 * Get value of field IN986FEFC as a String.
	 */
	public String getIN986FEFC() {
		return fieldIN986FEFC.getString();
	}

	/**
	 * Get value of field IN986FPOS as a String.
	 */
	public String getIN986FPOS() {
		return fieldIN986FPOS.getString();
	}

	/**
	 * Get value of field IN986RPGO as a String.
	 */
	public String getIN986RPGO() {
		return fieldIN986RPGO.getString();
	}

	/**
	 * Get value of field IN986USR as a String.
	 */
	public String getIN986USR() {
		return fieldIN986USR.getString();
	}

	/**
	 * Set field IN986CCN using a String value.
	 */
	public void setIN986CCN(String newvalue) {
		fieldIN986CCN.setString(newvalue);
	}

	/**
	 * Set field IN986CRED using a String value.
	 */
	public void setIN986CRED(String newvalue) {
		fieldIN986CRED.setString(newvalue);
	}

	/**
	 * Set numeric field IN986CRED using a BigDecimal value.
	 */
	public void setIN986CRED(BigDecimal newvalue) {
		fieldIN986CRED.setBigDecimal(newvalue);
	}

	/**
	 * Set field IN986DEBI using a String value.
	 */
	public void setIN986DEBI(String newvalue) {
		fieldIN986DEBI.setString(newvalue);
	}

	/**
	 * Set numeric field IN986DEBI using a BigDecimal value.
	 */
	public void setIN986DEBI(BigDecimal newvalue) {
		fieldIN986DEBI.setBigDecimal(newvalue);
	}

	/**
	 * Set field IN986DESC using a String value.
	 */
	public void setIN986DESC(String newvalue) {
		fieldIN986DESC.setString(newvalue);
	}

	/**
	 * Set field IN986END using a String value.
	 */
	public void setIN986END(String newvalue) {
		fieldIN986END.setString(newvalue);
	}

	/**
	 * Set field IN986FCOR using a String value.
	 */
	public void setIN986FCOR(String newvalue) {
		fieldIN986FCOR.setString(newvalue);
	}

	/**
	 * Set numeric field IN986FCOR using a BigDecimal value.
	 */
	public void setIN986FCOR(BigDecimal newvalue) {
		fieldIN986FCOR.setBigDecimal(newvalue);
	}

	/**
	 * Set field IN986FEFC using a String value.
	 */
	public void setIN986FEFC(String newvalue) {
		fieldIN986FEFC.setString(newvalue);
	}

	/**
	 * Set numeric field IN986FEFC using a BigDecimal value.
	 */
	public void setIN986FEFC(BigDecimal newvalue) {
		fieldIN986FEFC.setBigDecimal(newvalue);
	}

	/**
	 * Set field IN986FPOS using a String value.
	 */
	public void setIN986FPOS(String newvalue) {
		fieldIN986FPOS.setString(newvalue);
	}

	/**
	 * Set numeric field IN986FPOS using a BigDecimal value.
	 */
	public void setIN986FPOS(BigDecimal newvalue) {
		fieldIN986FPOS.setBigDecimal(newvalue);
	}

	/**
	 * Set field IN986RPGO using a String value.
	 */
	public void setIN986RPGO(String newvalue) {
		fieldIN986RPGO.setString(newvalue);
	}

	/**
	 * Set numeric field IN986RPGO using a BigDecimal value.
	 */
	public void setIN986RPGO(BigDecimal newvalue) {
		fieldIN986RPGO.setBigDecimal(newvalue);
	}

	/**
	 * Set field IN986USR using a String value.
	 */
	public void setIN986USR(String newvalue) {
		fieldIN986USR.setString(newvalue);
	}
}