package com.afirme.afirmenet.ibs.messages;

import java.math.BigDecimal;

import com.datapro.sockets.CharacterField;
import com.datapro.sockets.DecimalField;
import com.datapro.sockets.MessageField;
import com.datapro.sockets.MessageRecord;

/**
 * Class generated by AS/400 CRTCLASS command from IN098001 physical file
 * definition.
 * 
 * File level identifier is 1000803180134. Record format level identifier is
 * 4571E5A444806.
 */

public class IN098001Message extends MessageRecord {
	final int FIELDCOUNT = 22;
	private CharacterField fieldH01USERID = null;
	private CharacterField fieldH01PROGRM = null;
	private CharacterField fieldH01TIMSYS = null;
	private CharacterField fieldH01SCRCOD = null;
	private CharacterField fieldH01OPECOD = null;
	private CharacterField fieldH01FLGMAS = null;
	private CharacterField fieldH01FLGWK1 = null;
	private CharacterField fieldH01FLGWK2 = null;
	private CharacterField fieldH01FLGWK3 = null;
	private DecimalField fieldE01DEAACC = null;
	private DecimalField fieldE01DEABRN = null;
	private CharacterField fieldE01DEACCY = null;
	private DecimalField fieldE01DEAMEP = null;
	private DecimalField fieldE01DEAMEI = null;
	private DecimalField fieldE01DEAMEM = null;
	private DecimalField fieldE01DEADED = null;
	private DecimalField fieldE01TOTDUE = null;
	private DecimalField fieldE01DEARTE = null;
	private CharacterField fieldE01NICKNM = null;
	private DecimalField fieldE01MATDT1 = null;
	private DecimalField fieldE01MATDT2 = null;
	private DecimalField fieldE01MATDT3 = null;

	/**
	 * Constructor for IN098001Message.
	 */
	public IN098001Message() {
		createFields();
		initialize();
	}

	/**
	 * Create fields for this message. This method implements the abstract
	 * method in the MessageRecord superclass.
	 */
	protected void createFields() {
		recordsize = 197;
		fileid = "1000803180134";
		recordid = "4571E5A444806";
		message = new byte[getByteLength()];
		formatname = "IN098001";
		fieldnames = new String[FIELDCOUNT];
		tagnames = new String[FIELDCOUNT];
		fields = new MessageField[FIELDCOUNT];

		fieldnames[0] = "H01USERID";
		tagnames[0] = "H01USERID";
		fields[0] = fieldH01USERID = new CharacterField(message,
				HEADERSIZE + 0, 10, "H01USERID");
		fieldnames[1] = "H01PROGRM";
		tagnames[1] = "H01PROGRM";
		fields[1] = fieldH01PROGRM = new CharacterField(message,
				HEADERSIZE + 10, 10, "H01PROGRM");
		fieldnames[2] = "H01TIMSYS";
		tagnames[2] = "H01TIMSYS";
		fields[2] = fieldH01TIMSYS = new CharacterField(message,
				HEADERSIZE + 20, 12, "H01TIMSYS");
		fieldnames[3] = "H01SCRCOD";
		tagnames[3] = "H01SCRCOD";
		fields[3] = fieldH01SCRCOD = new CharacterField(message,
				HEADERSIZE + 32, 2, "H01SCRCOD");
		fieldnames[4] = "H01OPECOD";
		tagnames[4] = "H01OPECOD";
		fields[4] = fieldH01OPECOD = new CharacterField(message,
				HEADERSIZE + 34, 4, "H01OPECOD");
		fieldnames[5] = "H01FLGMAS";
		tagnames[5] = "H01FLGMAS";
		fields[5] = fieldH01FLGMAS = new CharacterField(message,
				HEADERSIZE + 38, 1, "H01FLGMAS");
		fieldnames[6] = "H01FLGWK1";
		tagnames[6] = "H01FLGWK1";
		fields[6] = fieldH01FLGWK1 = new CharacterField(message,
				HEADERSIZE + 39, 1, "H01FLGWK1");
		fieldnames[7] = "H01FLGWK2";
		tagnames[7] = "H01FLGWK2";
		fields[7] = fieldH01FLGWK2 = new CharacterField(message,
				HEADERSIZE + 40, 1, "H01FLGWK2");
		fieldnames[8] = "H01FLGWK3";
		tagnames[8] = "H01FLGWK3";
		fields[8] = fieldH01FLGWK3 = new CharacterField(message,
				HEADERSIZE + 41, 1, "H01FLGWK3");
		fieldnames[9] = "E01DEAACC";
		tagnames[9] = "E01DEAACC";
		fields[9] = fieldE01DEAACC = new DecimalField(message, HEADERSIZE + 42,
				13, 0, "E01DEAACC");
		fieldnames[10] = "E01DEABRN";
		tagnames[10] = "E01DEABRN";
		fields[10] = fieldE01DEABRN = new DecimalField(message,
				HEADERSIZE + 55, 4, 0, "E01DEABRN");
		fieldnames[11] = "E01DEACCY";
		tagnames[11] = "E01DEACCY";
		fields[11] = fieldE01DEACCY = new CharacterField(message,
				HEADERSIZE + 59, 3, "E01DEACCY");
		fieldnames[12] = "E01DEAMEP";
		tagnames[12] = "E01DEAMEP";
		fields[12] = fieldE01DEAMEP = new DecimalField(message,
				HEADERSIZE + 62, 17, 2, "E01DEAMEP");
		fieldnames[13] = "E01DEAMEI";
		tagnames[13] = "E01DEAMEI";
		fields[13] = fieldE01DEAMEI = new DecimalField(message,
				HEADERSIZE + 79, 17, 2, "E01DEAMEI");
		fieldnames[14] = "E01DEAMEM";
		tagnames[14] = "E01DEAMEM";
		fields[14] = fieldE01DEAMEM = new DecimalField(message,
				HEADERSIZE + 96, 17, 2, "E01DEAMEM");
		fieldnames[15] = "E01DEADED";
		tagnames[15] = "E01DEADED";
		fields[15] = fieldE01DEADED = new DecimalField(message,
				HEADERSIZE + 113, 17, 2, "E01DEADED");
		fieldnames[16] = "E01TOTDUE";
		tagnames[16] = "E01TOTDUE";
		fields[16] = fieldE01TOTDUE = new DecimalField(message,
				HEADERSIZE + 130, 17, 2, "E01TOTDUE");
		fieldnames[17] = "E01DEARTE";
		tagnames[17] = "E01DEARTE";
		fields[17] = fieldE01DEARTE = new DecimalField(message,
				HEADERSIZE + 147, 11, 6, "E01DEARTE");
		fieldnames[18] = "E01NICKNM";
		tagnames[18] = "E01NICKNM";
		fields[18] = fieldE01NICKNM = new CharacterField(message,
				HEADERSIZE + 158, 30, "E01NICKNM");
		fieldnames[19] = "E01MATDT1";
		tagnames[19] = "E01MATDT1";
		fields[19] = fieldE01MATDT1 = new DecimalField(message,
				HEADERSIZE + 188, 3, 0, "E01MATDT1");
		fieldnames[20] = "E01MATDT2";
		tagnames[20] = "E01MATDT2";
		fields[20] = fieldE01MATDT2 = new DecimalField(message,
				HEADERSIZE + 191, 3, 0, "E01MATDT2");
		fieldnames[21] = "E01MATDT3";
		tagnames[21] = "E01MATDT3";
		fields[21] = fieldE01MATDT3 = new DecimalField(message,
				HEADERSIZE + 194, 3, 0, "E01MATDT3");
	}

	/**
	 * Return value of numeric field E01DEAACC as a BigDecimal.
	 */
	public BigDecimal getBigDecimalE01DEAACC() {
		return fieldE01DEAACC.getBigDecimal();
	}

	/**
	 * Return value of numeric field E01DEABRN as a BigDecimal.
	 */
	public BigDecimal getBigDecimalE01DEABRN() {
		return fieldE01DEABRN.getBigDecimal();
	}

	/**
	 * Return value of numeric field E01DEADED as a BigDecimal.
	 */
	public BigDecimal getBigDecimalE01DEADED() {
		return fieldE01DEADED.getBigDecimal();
	}

	/**
	 * Return value of numeric field E01DEAMEI as a BigDecimal.
	 */
	public BigDecimal getBigDecimalE01DEAMEI() {
		return fieldE01DEAMEI.getBigDecimal();
	}

	/**
	 * Return value of numeric field E01DEAMEM as a BigDecimal.
	 */
	public BigDecimal getBigDecimalE01DEAMEM() {
		return fieldE01DEAMEM.getBigDecimal();
	}

	/**
	 * Return value of numeric field E01DEAMEP as a BigDecimal.
	 */
	public BigDecimal getBigDecimalE01DEAMEP() {
		return fieldE01DEAMEP.getBigDecimal();
	}

	/**
	 * Return value of numeric field E01DEARTE as a BigDecimal.
	 */
	public BigDecimal getBigDecimalE01DEARTE() {
		return fieldE01DEARTE.getBigDecimal();
	}

	/**
	 * Return value of numeric field E01MATDT1 as a BigDecimal.
	 */
	public BigDecimal getBigDecimalE01MATDT1() {
		return fieldE01MATDT1.getBigDecimal();
	}

	/**
	 * Return value of numeric field E01MATDT2 as a BigDecimal.
	 */
	public BigDecimal getBigDecimalE01MATDT2() {
		return fieldE01MATDT2.getBigDecimal();
	}

	/**
	 * Return value of numeric field E01MATDT3 as a BigDecimal.
	 */
	public BigDecimal getBigDecimalE01MATDT3() {
		return fieldE01MATDT3.getBigDecimal();
	}

	/**
	 * Return value of numeric field E01TOTDUE as a BigDecimal.
	 */
	public BigDecimal getBigDecimalE01TOTDUE() {
		return fieldE01TOTDUE.getBigDecimal();
	}

	/**
	 * Get value of field E01DEAACC as a String.
	 */
	public String getE01DEAACC() {
		return fieldE01DEAACC.getString();
	}

	/**
	 * Get value of field E01DEABRN as a String.
	 */
	public String getE01DEABRN() {
		return fieldE01DEABRN.getString();
	}

	/**
	 * Get value of field E01DEACCY as a String.
	 */
	public String getE01DEACCY() {
		return fieldE01DEACCY.getString();
	}

	/**
	 * Get value of field E01DEADED as a String.
	 */
	public String getE01DEADED() {
		return fieldE01DEADED.getString();
	}

	/**
	 * Get value of field E01DEAMEI as a String.
	 */
	public String getE01DEAMEI() {
		return fieldE01DEAMEI.getString();
	}

	/**
	 * Get value of field E01DEAMEM as a String.
	 */
	public String getE01DEAMEM() {
		return fieldE01DEAMEM.getString();
	}

	/**
	 * Get value of field E01DEAMEP as a String.
	 */
	public String getE01DEAMEP() {
		return fieldE01DEAMEP.getString();
	}

	/**
	 * Get value of field E01DEARTE as a String.
	 */
	public String getE01DEARTE() {
		return fieldE01DEARTE.getString();
	}

	/**
	 * Get value of field E01MATDT1 as a String.
	 */
	public String getE01MATDT1() {
		return fieldE01MATDT1.getString();
	}

	/**
	 * Get value of field E01MATDT2 as a String.
	 */
	public String getE01MATDT2() {
		return fieldE01MATDT2.getString();
	}

	/**
	 * Get value of field E01MATDT3 as a String.
	 */
	public String getE01MATDT3() {
		return fieldE01MATDT3.getString();
	}

	/**
	 * Get value of field E01NICKNM as a String.
	 */
	public String getE01NICKNM() {
		return fieldE01NICKNM.getString();
	}

	/**
	 * Get value of field E01TOTDUE as a String.
	 */
	public String getE01TOTDUE() {
		return fieldE01TOTDUE.getString();
	}

	/**
	 * Get value of field H01FLGMAS as a String.
	 */
	public String getH01FLGMAS() {
		return fieldH01FLGMAS.getString();
	}

	/**
	 * Get value of field H01FLGWK1 as a String.
	 */
	public String getH01FLGWK1() {
		return fieldH01FLGWK1.getString();
	}

	/**
	 * Get value of field H01FLGWK2 as a String.
	 */
	public String getH01FLGWK2() {
		return fieldH01FLGWK2.getString();
	}

	/**
	 * Get value of field H01FLGWK3 as a String.
	 */
	public String getH01FLGWK3() {
		return fieldH01FLGWK3.getString();
	}

	/**
	 * Get value of field H01OPECOD as a String.
	 */
	public String getH01OPECOD() {
		return fieldH01OPECOD.getString();
	}

	/**
	 * Get value of field H01PROGRM as a String.
	 */
	public String getH01PROGRM() {
		return fieldH01PROGRM.getString();
	}

	/**
	 * Get value of field H01SCRCOD as a String.
	 */
	public String getH01SCRCOD() {
		return fieldH01SCRCOD.getString();
	}

	/**
	 * Get value of field H01TIMSYS as a String.
	 */
	public String getH01TIMSYS() {
		return fieldH01TIMSYS.getString();
	}

	/**
	 * Get value of field H01USERID as a String.
	 */
	public String getH01USERID() {
		return fieldH01USERID.getString();
	}

	/**
	 * Set field E01DEAACC using a String value.
	 */
	public void setE01DEAACC(String newvalue) {
		fieldE01DEAACC.setString(newvalue);
	}

	/**
	 * Set numeric field E01DEAACC using a BigDecimal value.
	 */
	public void setE01DEAACC(BigDecimal newvalue) {
		fieldE01DEAACC.setBigDecimal(newvalue);
	}

	/**
	 * Set field E01DEABRN using a String value.
	 */
	public void setE01DEABRN(String newvalue) {
		fieldE01DEABRN.setString(newvalue);
	}

	/**
	 * Set numeric field E01DEABRN using a BigDecimal value.
	 */
	public void setE01DEABRN(BigDecimal newvalue) {
		fieldE01DEABRN.setBigDecimal(newvalue);
	}

	/**
	 * Set field E01DEACCY using a String value.
	 */
	public void setE01DEACCY(String newvalue) {
		fieldE01DEACCY.setString(newvalue);
	}

	/**
	 * Set field E01DEADED using a String value.
	 */
	public void setE01DEADED(String newvalue) {
		fieldE01DEADED.setString(newvalue);
	}

	/**
	 * Set numeric field E01DEADED using a BigDecimal value.
	 */
	public void setE01DEADED(BigDecimal newvalue) {
		fieldE01DEADED.setBigDecimal(newvalue);
	}

	/**
	 * Set field E01DEAMEI using a String value.
	 */
	public void setE01DEAMEI(String newvalue) {
		fieldE01DEAMEI.setString(newvalue);
	}

	/**
	 * Set numeric field E01DEAMEI using a BigDecimal value.
	 */
	public void setE01DEAMEI(BigDecimal newvalue) {
		fieldE01DEAMEI.setBigDecimal(newvalue);
	}

	/**
	 * Set field E01DEAMEM using a String value.
	 */
	public void setE01DEAMEM(String newvalue) {
		fieldE01DEAMEM.setString(newvalue);
	}

	/**
	 * Set numeric field E01DEAMEM using a BigDecimal value.
	 */
	public void setE01DEAMEM(BigDecimal newvalue) {
		fieldE01DEAMEM.setBigDecimal(newvalue);
	}

	/**
	 * Set field E01DEAMEP using a String value.
	 */
	public void setE01DEAMEP(String newvalue) {
		fieldE01DEAMEP.setString(newvalue);
	}

	/**
	 * Set numeric field E01DEAMEP using a BigDecimal value.
	 */
	public void setE01DEAMEP(BigDecimal newvalue) {
		fieldE01DEAMEP.setBigDecimal(newvalue);
	}

	/**
	 * Set field E01DEARTE using a String value.
	 */
	public void setE01DEARTE(String newvalue) {
		fieldE01DEARTE.setString(newvalue);
	}

	/**
	 * Set numeric field E01DEARTE using a BigDecimal value.
	 */
	public void setE01DEARTE(BigDecimal newvalue) {
		fieldE01DEARTE.setBigDecimal(newvalue);
	}

	/**
	 * Set field E01MATDT1 using a String value.
	 */
	public void setE01MATDT1(String newvalue) {
		fieldE01MATDT1.setString(newvalue);
	}

	/**
	 * Set numeric field E01MATDT1 using a BigDecimal value.
	 */
	public void setE01MATDT1(BigDecimal newvalue) {
		fieldE01MATDT1.setBigDecimal(newvalue);
	}

	/**
	 * Set field E01MATDT2 using a String value.
	 */
	public void setE01MATDT2(String newvalue) {
		fieldE01MATDT2.setString(newvalue);
	}

	/**
	 * Set numeric field E01MATDT2 using a BigDecimal value.
	 */
	public void setE01MATDT2(BigDecimal newvalue) {
		fieldE01MATDT2.setBigDecimal(newvalue);
	}

	/**
	 * Set field E01MATDT3 using a String value.
	 */
	public void setE01MATDT3(String newvalue) {
		fieldE01MATDT3.setString(newvalue);
	}

	/**
	 * Set numeric field E01MATDT3 using a BigDecimal value.
	 */
	public void setE01MATDT3(BigDecimal newvalue) {
		fieldE01MATDT3.setBigDecimal(newvalue);
	}

	/**
	 * Set field E01NICKNM using a String value.
	 */
	public void setE01NICKNM(String newvalue) {
		fieldE01NICKNM.setString(newvalue);
	}

	/**
	 * Set field E01TOTDUE using a String value.
	 */
	public void setE01TOTDUE(String newvalue) {
		fieldE01TOTDUE.setString(newvalue);
	}

	/**
	 * Set numeric field E01TOTDUE using a BigDecimal value.
	 */
	public void setE01TOTDUE(BigDecimal newvalue) {
		fieldE01TOTDUE.setBigDecimal(newvalue);
	}

	/**
	 * Set field H01FLGMAS using a String value.
	 */
	public void setH01FLGMAS(String newvalue) {
		fieldH01FLGMAS.setString(newvalue);
	}

	/**
	 * Set field H01FLGWK1 using a String value.
	 */
	public void setH01FLGWK1(String newvalue) {
		fieldH01FLGWK1.setString(newvalue);
	}

	/**
	 * Set field H01FLGWK2 using a String value.
	 */
	public void setH01FLGWK2(String newvalue) {
		fieldH01FLGWK2.setString(newvalue);
	}

	/**
	 * Set field H01FLGWK3 using a String value.
	 */
	public void setH01FLGWK3(String newvalue) {
		fieldH01FLGWK3.setString(newvalue);
	}

	/**
	 * Set field H01OPECOD using a String value.
	 */
	public void setH01OPECOD(String newvalue) {
		fieldH01OPECOD.setString(newvalue);
	}

	/**
	 * Set field H01PROGRM using a String value.
	 */
	public void setH01PROGRM(String newvalue) {
		fieldH01PROGRM.setString(newvalue);
	}

	/**
	 * Set field H01SCRCOD using a String value.
	 */
	public void setH01SCRCOD(String newvalue) {
		fieldH01SCRCOD.setString(newvalue);
	}

	/**
	 * Set field H01TIMSYS using a String value.
	 */
	public void setH01TIMSYS(String newvalue) {
		fieldH01TIMSYS.setString(newvalue);
	}

	/**
	 * Set field H01USERID using a String value.
	 */
	public void setH01USERID(String newvalue) {
		fieldH01USERID.setString(newvalue);
	}
}