package com.afirme.afirmenet.ibs.messages;

import com.datapro.sockets.CharacterField;
import com.datapro.sockets.MessageField;
import com.datapro.sockets.MessageRecord;

/**
 * Class generated by AS/400 CRTCLASS command from IN095501 physical file
 * definition.
 * 
 * File level identifier is 1000920164225. Record format level identifier is
 * 2B4463D8DFD5F.
 */

public class IN095501Message extends MessageRecord {
	final int FIELDCOUNT = 4;
	private CharacterField fieldIN9551USR = null;
	private CharacterField fieldIN9551TYP = null;
	private CharacterField fieldIN9551ACC = null;
	private CharacterField fieldIN9551EOF = null;

	/**
	 * Constructor for IN095501Message.
	 */
	public IN095501Message() {
		createFields();
		initialize();
	}

	/**
	 * Create fields for this message. This method implements the abstract
	 * method in the MessageRecord superclass.
	 */
	protected void createFields() {
		recordsize = 31;
		fileid = "1000920164225";
		recordid = "2B4463D8DFD5F";
		message = new byte[getByteLength()];
		formatname = "IN095501";
		fieldnames = new String[FIELDCOUNT];
		tagnames = new String[FIELDCOUNT];
		fields = new MessageField[FIELDCOUNT];

		fieldnames[0] = "IN9551USR";
		tagnames[0] = "IN9551USR";
		fields[0] = fieldIN9551USR = new CharacterField(message,
				HEADERSIZE + 0, 10, "IN9551USR");
		fieldnames[1] = "IN9551TYP";
		tagnames[1] = "IN9551TYP";
		fields[1] = fieldIN9551TYP = new CharacterField(message,
				HEADERSIZE + 10, 2, "IN9551TYP");
		fieldnames[2] = "IN9551ACC";
		tagnames[2] = "IN9551ACC";
		fields[2] = fieldIN9551ACC = new CharacterField(message,
				HEADERSIZE + 12, 18, "IN9551ACC");
		fieldnames[3] = "IN9551EOF";
		tagnames[3] = "IN9551EOF";
		fields[3] = fieldIN9551EOF = new CharacterField(message,
				HEADERSIZE + 30, 1, "IN9551EOF");
	}

	/**
	 * Get value of field IN9551ACC as a String.
	 */
	public String getIN9551ACC() {
		return fieldIN9551ACC.getString();
	}

	/**
	 * Get value of field IN9551EOF as a String.
	 */
	public String getIN9551EOF() {
		return fieldIN9551EOF.getString();
	}

	/**
	 * Get value of field IN9551TYP as a String.
	 */
	public String getIN9551TYP() {
		return fieldIN9551TYP.getString();
	}

	/**
	 * Get value of field IN9551USR as a String.
	 */
	public String getIN9551USR() {
		return fieldIN9551USR.getString();
	}

	/**
	 * Set field IN9551ACC using a String value.
	 */
	public void setIN9551ACC(String newvalue) {
		fieldIN9551ACC.setString(newvalue);
	}

	/**
	 * Set field IN9551EOF using a String value.
	 */
	public void setIN9551EOF(String newvalue) {
		fieldIN9551EOF.setString(newvalue);
	}

	/**
	 * Set field IN9551TYP using a String value.
	 */
	public void setIN9551TYP(String newvalue) {
		fieldIN9551TYP.setString(newvalue);
	}

	/**
	 * Set field IN9551USR using a String value.
	 */
	public void setIN9551USR(String newvalue) {
		fieldIN9551USR.setString(newvalue);
	}
}