/*
 * Creado el 17/01/2008
 *
 * Para cambiar la plantilla para este archivo generado vaya a
 * Ventana&gt;Preferencias&gt;Java&gt;Generación de código&gt;Código y comentarios
 */
package com.afirme.afirmenet.ibs.messages;

import java.math.BigDecimal;
import java.util.Hashtable;

import com.datapro.sockets.CharacterField;
import com.datapro.sockets.DecimalField;
import com.datapro.sockets.MessageField;
import com.datapro.sockets.MessageRecord;

/**
 * Class generated by AS/400 CRTCLASS command from INFORMU01 physical file
 * definition.
 * 
 * File level identifier is 1090708103752. Record format level identifier is
 * 3FC231BCB63E4.
 */
@SuppressWarnings("rawtypes")
public class INFORMU01Message extends MessageRecord {
	final static String fldnames[] = { "INCOPE", "INTUSR", "INTREF",
			"INTXPMTV", "INTFECHA", "INTHORA", "INTGRUPO", "INTCLAVE",
			"INTBANCO", "INTCTACGO", "INTAUTOR", "INTFECPAGO", "INTLCAPT",
			"INTMONEDA", "INTIMPORTE", "INTNOMBRE", "INTDIREC", "INTCOLONIA",
			"INTCODPOS", "INTDELEGA", "INTESTADO", "INTCVETIPO", "INTTIPO",
			"INPERIODO", "INTRFC", "INTPLACA", "INTMODELO", "INCVEMARCA",
			"INTMARCA", "INTFOLIO", "INTANOINF", "INTCVEVER", "INTCVEHOLO",
			"INTHOLOGR", "INTCANT", "INTFOLHOL", "INTFOLREG", "INTPREUNI",
			"INTFOLFACT", "INTCUENTA", "INTEJERC", "INTBIM", "INTEJEFIS",
			"INSUBMARCA", "INTVALFACT", "INTNCILIND", "INTEJEIMP", "INTMESIMP",
			"INTIPODECL", "INTRENUM", "INTNUMTRAB", "INTFECEVEN", "INCVEOPER",
			"INTIPOPER", "INTFECESC", "INTFOLPROP", "INCVETRAM", "INTRAMITE",
			"INTNUMESC", "INVIGENCIA", "INTNOTARIO", "INTCERTIF", "INTTIF",
			"INTSTS", "INTORIGEN", "INTSUBCPTO", "INTREFPAGO", "INTCVEADTR" };
	final static String tnames[] = { "INCOPE", "INTUSR", "INTREF", "INTXPMTV",
			"INTFECHA", "INTHORA", "INTGRUPO", "INTCLAVE", "INTBANCO",
			"INTCTACGO", "INTAUTOR", "INTFECPAGO", "INTLCAPT", "INTMONEDA",
			"INTIMPORTE", "INTNOMBRE", "INTDIREC", "INTCOLONIA", "INTCODPOS",
			"INTDELEGA", "INTESTADO", "INTCVETIPO", "INTTIPO", "INPERIODO",
			"INTRFC", "INTPLACA", "INTMODELO", "INCVEMARCA", "INTMARCA",
			"INTFOLIO", "INTANOINF", "INTCVEVER", "INTCVEHOLO", "INTHOLOGR",
			"INTCANT", "INTFOLHOL", "INTFOLREG", "INTPREUNI", "INTFOLFACT",
			"INTCUENTA", "INTEJERC", "INTBIM", "INTEJEFIS", "INSUBMARCA",
			"INTVALFACT", "INTNCILIND", "INTEJEIMP", "INTMESIMP", "INTIPODECL",
			"INTRENUM", "INTNUMTRAB", "INTFECEVEN", "INCVEOPER", "INTIPOPER",
			"INTFECESC", "INTFOLPROP", "INCVETRAM", "INTRAMITE", "INTNUMESC",
			"INVIGENCIA", "INTNOTARIO", "INTCERTIF", "INTTIF", "INTSTS",
			"INTORIGEN", "INTSUBCPTO", "INTREFPAGO", "INTCVEADTR" };
	final static String fid = "1090708103752";
	final static String rid = "3FC231BCB63E4";
	final static String fmtname = "INFORMU01";
	final int FIELDCOUNT = 68;
	private static Hashtable tlookup = new Hashtable();
	private CharacterField fieldINCOPE = null;
	private CharacterField fieldINTUSR = null;
	private CharacterField fieldINTREF = null;
	private CharacterField fieldINTXPMTV = null;
	private DecimalField fieldINTFECHA = null;
	private DecimalField fieldINTHORA = null;
	private DecimalField fieldINTGRUPO = null;
	private DecimalField fieldINTCLAVE = null;
	private DecimalField fieldINTBANCO = null;
	private DecimalField fieldINTCTACGO = null;
	private DecimalField fieldINTAUTOR = null;
	private DecimalField fieldINTFECPAGO = null;
	private CharacterField fieldINTLCAPT = null;
	private CharacterField fieldINTMONEDA = null;
	private DecimalField fieldINTIMPORTE = null;
	private CharacterField fieldINTNOMBRE = null;
	private CharacterField fieldINTDIREC = null;
	private CharacterField fieldINTCOLONIA = null;
	private CharacterField fieldINTCODPOS = null;
	private CharacterField fieldINTDELEGA = null;
	private CharacterField fieldINTESTADO = null;
	private CharacterField fieldINTCVETIPO = null;
	private CharacterField fieldINTTIPO = null;
	private CharacterField fieldINPERIODO = null;
	private CharacterField fieldINTRFC = null;
	private CharacterField fieldINTPLACA = null;
	private DecimalField fieldINTMODELO = null;
	private DecimalField fieldINCVEMARCA = null;
	private CharacterField fieldINTMARCA = null;
	private DecimalField fieldINTFOLIO = null;
	private DecimalField fieldINTANOINF = null;
	private DecimalField fieldINTCVEVER = null;
	private CharacterField fieldINTCVEHOLO = null;
	private CharacterField fieldINTHOLOGR = null;
	private DecimalField fieldINTCANT = null;
	private DecimalField fieldINTFOLHOL = null;
	private DecimalField fieldINTFOLREG = null;
	private DecimalField fieldINTPREUNI = null;
	private DecimalField fieldINTFOLFACT = null;
	private CharacterField fieldINTCUENTA = null;
	private DecimalField fieldINTEJERC = null;
	private CharacterField fieldINTBIM = null;
	private DecimalField fieldINTEJEFIS = null;
	private CharacterField fieldINSUBMARCA = null;
	private DecimalField fieldINTVALFACT = null;
	private DecimalField fieldINTNCILIND = null;
	private DecimalField fieldINTEJEIMP = null;
	private CharacterField fieldINTMESIMP = null;
	private DecimalField fieldINTIPODECL = null;
	private DecimalField fieldINTRENUM = null;
	private DecimalField fieldINTNUMTRAB = null;
	private CharacterField fieldINTFECEVEN = null;
	private CharacterField fieldINCVEOPER = null;
	private CharacterField fieldINTIPOPER = null;
	private DecimalField fieldINTFECESC = null;
	private DecimalField fieldINTFOLPROP = null;
	private CharacterField fieldINCVETRAM = null;
	private CharacterField fieldINTRAMITE = null;
	private CharacterField fieldINTNUMESC = null;
	private DecimalField fieldINVIGENCIA = null;
	private CharacterField fieldINTNOTARIO = null;
	private CharacterField fieldINTCERTIF = null;
	private DecimalField fieldINTTIF = null;
	private CharacterField fieldINTSTS = null;
	private CharacterField fieldINTORIGEN = null;
	private CharacterField fieldINTSUBCPTO = null;
	private CharacterField fieldINTREFPAGO = null;
	private CharacterField fieldINTCVEADTR = null;

	/**
	 * Constructor for INFORMU01Message.
	 */
	public INFORMU01Message() {
		createFields();
		initialize();
	}

	/**
	 * Create fields for this message. This method implements the abstract
	 * method in the MessageRecord superclass.
	 */
	@SuppressWarnings("unchecked")
	protected void createFields() {
		recordsize = 1073;
		fileid = fid;
		recordid = rid;
		message = new byte[getByteLength()];
		formatname = fmtname;
		fieldnames = fldnames;
		tagnames = tnames;
		fields = new MessageField[FIELDCOUNT];

		fields[0] = fieldINCOPE = new CharacterField(message, HEADERSIZE + 0,
				1, "INCOPE");
		fields[1] = fieldINTUSR = new CharacterField(message, HEADERSIZE + 1,
				10, "INTUSR");
		fields[2] = fieldINTREF = new CharacterField(message, HEADERSIZE + 11,
				12, "INTREF");
		fields[3] = fieldINTXPMTV = new CharacterField(message,
				HEADERSIZE + 23, 2, "INTXPMTV");
		fields[4] = fieldINTFECHA = new DecimalField(message, HEADERSIZE + 25,
				9, 0, "INTFECHA");
		fields[5] = fieldINTHORA = new DecimalField(message, HEADERSIZE + 34,
				7, 0, "INTHORA");
		fields[6] = fieldINTGRUPO = new DecimalField(message, HEADERSIZE + 41,
				4, 0, "INTGRUPO");
		fields[7] = fieldINTCLAVE = new DecimalField(message, HEADERSIZE + 45,
				4, 0, "INTCLAVE");
		fields[8] = fieldINTBANCO = new DecimalField(message, HEADERSIZE + 49,
				4, 0, "INTBANCO");
		fields[9] = fieldINTCTACGO = new DecimalField(message, HEADERSIZE + 53,
				13, 0, "INTCTACGO");
		fields[10] = fieldINTAUTOR = new DecimalField(message, HEADERSIZE + 66,
				13, 0, "INTAUTOR");
		fields[11] = fieldINTFECPAGO = new DecimalField(message,
				HEADERSIZE + 79, 9, 0, "INTFECPAGO");
		fields[12] = fieldINTLCAPT = new CharacterField(message,
				HEADERSIZE + 88, 20, "INTLCAPT");
		fields[13] = fieldINTMONEDA = new CharacterField(message,
				HEADERSIZE + 108, 3, "INTMONEDA");
		fields[14] = fieldINTIMPORTE = new DecimalField(message,
				HEADERSIZE + 111, 17, 2, "INTIMPORTE");
		fields[15] = fieldINTNOMBRE = new CharacterField(message,
				HEADERSIZE + 128, 80, "INTNOMBRE");
		fields[16] = fieldINTDIREC = new CharacterField(message,
				HEADERSIZE + 208, 80, "INTDIREC");
		fields[17] = fieldINTCOLONIA = new CharacterField(message,
				HEADERSIZE + 288, 40, "INTCOLONIA");
		fields[18] = fieldINTCODPOS = new CharacterField(message,
				HEADERSIZE + 328, 8, "INTCODPOS");
		fields[19] = fieldINTDELEGA = new CharacterField(message,
				HEADERSIZE + 336, 30, "INTDELEGA");
		fields[20] = fieldINTESTADO = new CharacterField(message,
				HEADERSIZE + 366, 30, "INTESTADO");
		fields[21] = fieldINTCVETIPO = new CharacterField(message,
				HEADERSIZE + 396, 5, "INTCVETIPO");
		fields[22] = fieldINTTIPO = new CharacterField(message,
				HEADERSIZE + 401, 30, "INTTIPO");
		fields[23] = fieldINPERIODO = new CharacterField(message,
				HEADERSIZE + 431, 20, "INPERIODO");
		fields[24] = fieldINTRFC = new CharacterField(message,
				HEADERSIZE + 451, 18, "INTRFC");
		fields[25] = fieldINTPLACA = new CharacterField(message,
				HEADERSIZE + 469, 10, "INTPLACA");
		fields[26] = fieldINTMODELO = new DecimalField(message,
				HEADERSIZE + 479, 5, 0, "INTMODELO");
		fields[27] = fieldINCVEMARCA = new DecimalField(message,
				HEADERSIZE + 484, 6, 0, "INCVEMARCA");
		fields[28] = fieldINTMARCA = new CharacterField(message,
				HEADERSIZE + 490, 30, "INTMARCA");
		fields[29] = fieldINTFOLIO = new DecimalField(message,
				HEADERSIZE + 520, 9, 0, "INTFOLIO");
		fields[30] = fieldINTANOINF = new DecimalField(message,
				HEADERSIZE + 529, 5, 0, "INTANOINF");
		fields[31] = fieldINTCVEVER = new DecimalField(message,
				HEADERSIZE + 534, 5, 0, "INTCVEVER");
		fields[32] = fieldINTCVEHOLO = new CharacterField(message,
				HEADERSIZE + 539, 5, "INTCVEHOLO");
		fields[33] = fieldINTHOLOGR = new CharacterField(message,
				HEADERSIZE + 544, 50, "INTHOLOGR");
		fields[34] = fieldINTCANT = new DecimalField(message, HEADERSIZE + 594,
				9, 0, "INTCANT");
		fields[35] = fieldINTFOLHOL = new DecimalField(message,
				HEADERSIZE + 603, 5, 0, "INTFOLHOL");
		fields[36] = fieldINTFOLREG = new DecimalField(message,
				HEADERSIZE + 608, 9, 0, "INTFOLREG");
		fields[37] = fieldINTPREUNI = new DecimalField(message,
				HEADERSIZE + 617, 11, 2, "INTPREUNI");
		fields[38] = fieldINTFOLFACT = new DecimalField(message,
				HEADERSIZE + 628, 9, 0, "INTFOLFACT");
		fields[39] = fieldINTCUENTA = new CharacterField(message,
				HEADERSIZE + 637, 20, "INTCUENTA");
		fields[40] = fieldINTEJERC = new DecimalField(message,
				HEADERSIZE + 657, 5, 0, "INTEJERC");
		fields[41] = fieldINTBIM = new CharacterField(message,
				HEADERSIZE + 662, 30, "INTBIM");
		fields[42] = fieldINTEJEFIS = new DecimalField(message,
				HEADERSIZE + 692, 5, 0, "INTEJEFIS");
		fields[43] = fieldINSUBMARCA = new CharacterField(message,
				HEADERSIZE + 697, 25, "INSUBMARCA");
		fields[44] = fieldINTVALFACT = new DecimalField(message,
				HEADERSIZE + 722, 17, 2, "INTVALFACT");
		fields[45] = fieldINTNCILIND = new DecimalField(message,
				HEADERSIZE + 739, 5, 0, "INTNCILIND");
		fields[46] = fieldINTEJEIMP = new DecimalField(message,
				HEADERSIZE + 744, 5, 0, "INTEJEIMP");
		fields[47] = fieldINTMESIMP = new CharacterField(message,
				HEADERSIZE + 749, 30, "INTMESIMP");
		fields[48] = fieldINTIPODECL = new DecimalField(message,
				HEADERSIZE + 779, 2, 0, "INTIPODECL");
		fields[49] = fieldINTRENUM = new DecimalField(message,
				HEADERSIZE + 781, 17, 2, "INTRENUM");
		fields[50] = fieldINTNUMTRAB = new DecimalField(message,
				HEADERSIZE + 798, 8, 0, "INTNUMTRAB");
		fields[51] = fieldINTFECEVEN = new CharacterField(message,
				HEADERSIZE + 806, 16, "INTFECEVEN");
		fields[52] = fieldINCVEOPER = new CharacterField(message,
				HEADERSIZE + 822, 5, "INCVEOPER");
		fields[53] = fieldINTIPOPER = new CharacterField(message,
				HEADERSIZE + 827, 15, "INTIPOPER");
		fields[54] = fieldINTFECESC = new DecimalField(message,
				HEADERSIZE + 842, 9, 0, "INTFECESC");
		fields[55] = fieldINTFOLPROP = new DecimalField(message,
				HEADERSIZE + 851, 9, 0, "INTFOLPROP");
		fields[56] = fieldINCVETRAM = new CharacterField(message,
				HEADERSIZE + 860, 5, "INCVETRAM");
		fields[57] = fieldINTRAMITE = new CharacterField(message,
				HEADERSIZE + 865, 125, "INTRAMITE");
		fields[58] = fieldINTNUMESC = new CharacterField(message,
				HEADERSIZE + 990, 20, "INTNUMESC");
		fields[59] = fieldINVIGENCIA = new DecimalField(message,
				HEADERSIZE + 1010, 2, 0, "INVIGENCIA");
		fields[60] = fieldINTNOTARIO = new CharacterField(message,
				HEADERSIZE + 1012, 20, "INTNOTARIO");
		fields[61] = fieldINTCERTIF = new CharacterField(message,
				HEADERSIZE + 1032, 22, "INTCERTIF");
		fields[62] = fieldINTTIF = new DecimalField(message, HEADERSIZE + 1054,
				7, 0, "INTTIF");
		fields[63] = fieldINTSTS = new CharacterField(message,
				HEADERSIZE + 1061, 1, "INTSTS");
		fields[64] = fieldINTORIGEN = new CharacterField(message,
				HEADERSIZE + 1062, 2, "INTORIGEN");
		fields[65] = fieldINTSUBCPTO = new CharacterField(message,
				HEADERSIZE + 1064, 1, "INTSUBCPTO");
		fields[66] = fieldINTREFPAGO = new CharacterField(message,
				HEADERSIZE + 1065, 6, "INTREFPAGO");
		fields[67] = fieldINTCVEADTR = new CharacterField(message,
				HEADERSIZE + 1071, 2, "INTCVEADTR");

		synchronized (tlookup) {
			if (tlookup.isEmpty()) {
				for (int i = 0; i < tnames.length; i++)
					tlookup.put(tnames[i], new Integer(i));
			}
		}

		taglookup = tlookup;
	}

	/**
	 * Set field INCOPE using a String value.
	 */
	public void setINCOPE(String newvalue) {
		fieldINCOPE.setString(newvalue);
	}

	/**
	 * Get value of field INCOPE as a String.
	 */
	public String getINCOPE() {
		return fieldINCOPE.getString();
	}

	/**
	 * Set field INTUSR using a String value.
	 */
	public void setINTUSR(String newvalue) {
		fieldINTUSR.setString(newvalue);
	}

	/**
	 * Get value of field INTUSR as a String.
	 */
	public String getINTUSR() {
		return fieldINTUSR.getString();
	}

	/**
	 * Set field INTREF using a String value.
	 */
	public void setINTREF(String newvalue) {
		fieldINTREF.setString(newvalue);
	}

	/**
	 * Get value of field INTREF as a String.
	 */
	public String getINTREF() {
		return fieldINTREF.getString();
	}

	/**
	 * Set field INTXPMTV using a String value.
	 */
	public void setINTXPMTV(String newvalue) {
		fieldINTXPMTV.setString(newvalue);
	}

	/**
	 * Get value of field INTXPMTV as a String.
	 */
	public String getINTXPMTV() {
		return fieldINTXPMTV.getString();
	}

	/**
	 * Set field INTFECHA using a String value.
	 */
	public void setINTFECHA(String newvalue) {
		fieldINTFECHA.setString(newvalue);
	}

	/**
	 * Get value of field INTFECHA as a String.
	 */
	public String getINTFECHA() {
		return fieldINTFECHA.getString();
	}

	/**
	 * Set numeric field INTFECHA using a BigDecimal value.
	 */
	public void setINTFECHA(BigDecimal newvalue) {
		fieldINTFECHA.setBigDecimal(newvalue);
	}

	/**
	 * Return value of numeric field INTFECHA as a BigDecimal.
	 */
	public BigDecimal getBigDecimalINTFECHA() {
		return fieldINTFECHA.getBigDecimal();
	}

	/**
	 * Set field INTHORA using a String value.
	 */
	public void setINTHORA(String newvalue) {
		fieldINTHORA.setString(newvalue);
	}

	/**
	 * Get value of field INTHORA as a String.
	 */
	public String getINTHORA() {
		return fieldINTHORA.getString();
	}

	/**
	 * Set numeric field INTHORA using a BigDecimal value.
	 */
	public void setINTHORA(BigDecimal newvalue) {
		fieldINTHORA.setBigDecimal(newvalue);
	}

	/**
	 * Return value of numeric field INTHORA as a BigDecimal.
	 */
	public BigDecimal getBigDecimalINTHORA() {
		return fieldINTHORA.getBigDecimal();
	}

	/**
	 * Set field INTGRUPO using a String value.
	 */
	public void setINTGRUPO(String newvalue) {
		fieldINTGRUPO.setString(newvalue);
	}

	/**
	 * Get value of field INTGRUPO as a String.
	 */
	public String getINTGRUPO() {
		return fieldINTGRUPO.getString();
	}

	/**
	 * Set numeric field INTGRUPO using a BigDecimal value.
	 */
	public void setINTGRUPO(BigDecimal newvalue) {
		fieldINTGRUPO.setBigDecimal(newvalue);
	}

	/**
	 * Return value of numeric field INTGRUPO as a BigDecimal.
	 */
	public BigDecimal getBigDecimalINTGRUPO() {
		return fieldINTGRUPO.getBigDecimal();
	}

	/**
	 * Set field INTCLAVE using a String value.
	 */
	public void setINTCLAVE(String newvalue) {
		fieldINTCLAVE.setString(newvalue);
	}

	/**
	 * Get value of field INTCLAVE as a String.
	 */
	public String getINTCLAVE() {
		return fieldINTCLAVE.getString();
	}

	/**
	 * Set numeric field INTCLAVE using a BigDecimal value.
	 */
	public void setINTCLAVE(BigDecimal newvalue) {
		fieldINTCLAVE.setBigDecimal(newvalue);
	}

	/**
	 * Return value of numeric field INTCLAVE as a BigDecimal.
	 */
	public BigDecimal getBigDecimalINTCLAVE() {
		return fieldINTCLAVE.getBigDecimal();
	}

	/**
	 * Set field INTBANCO using a String value.
	 */
	public void setINTBANCO(String newvalue) {
		fieldINTBANCO.setString(newvalue);
	}

	/**
	 * Get value of field INTBANCO as a String.
	 */
	public String getINTBANCO() {
		return fieldINTBANCO.getString();
	}

	/**
	 * Set numeric field INTBANCO using a BigDecimal value.
	 */
	public void setINTBANCO(BigDecimal newvalue) {
		fieldINTBANCO.setBigDecimal(newvalue);
	}

	/**
	 * Return value of numeric field INTBANCO as a BigDecimal.
	 */
	public BigDecimal getBigDecimalINTBANCO() {
		return fieldINTBANCO.getBigDecimal();
	}

	/**
	 * Set field INTCTACGO using a String value.
	 */
	public void setINTCTACGO(String newvalue) {
		fieldINTCTACGO.setString(newvalue);
	}

	/**
	 * Get value of field INTCTACGO as a String.
	 */
	public String getINTCTACGO() {
		return fieldINTCTACGO.getString();
	}

	/**
	 * Set numeric field INTCTACGO using a BigDecimal value.
	 */
	public void setINTCTACGO(BigDecimal newvalue) {
		fieldINTCTACGO.setBigDecimal(newvalue);
	}

	/**
	 * Return value of numeric field INTCTACGO as a BigDecimal.
	 */
	public BigDecimal getBigDecimalINTCTACGO() {
		return fieldINTCTACGO.getBigDecimal();
	}

	/**
	 * Set field INTAUTOR using a String value.
	 */
	public void setINTAUTOR(String newvalue) {
		fieldINTAUTOR.setString(newvalue);
	}

	/**
	 * Get value of field INTAUTOR as a String.
	 */
	public String getINTAUTOR() {
		return fieldINTAUTOR.getString();
	}

	/**
	 * Set numeric field INTAUTOR using a BigDecimal value.
	 */
	public void setINTAUTOR(BigDecimal newvalue) {
		fieldINTAUTOR.setBigDecimal(newvalue);
	}

	/**
	 * Return value of numeric field INTAUTOR as a BigDecimal.
	 */
	public BigDecimal getBigDecimalINTAUTOR() {
		return fieldINTAUTOR.getBigDecimal();
	}

	/**
	 * Set field INTFECPAGO using a String value.
	 */
	public void setINTFECPAGO(String newvalue) {
		fieldINTFECPAGO.setString(newvalue);
	}

	/**
	 * Get value of field INTFECPAGO as a String.
	 */
	public String getINTFECPAGO() {
		return fieldINTFECPAGO.getString();
	}

	/**
	 * Set numeric field INTFECPAGO using a BigDecimal value.
	 */
	public void setINTFECPAGO(BigDecimal newvalue) {
		fieldINTFECPAGO.setBigDecimal(newvalue);
	}

	/**
	 * Return value of numeric field INTFECPAGO as a BigDecimal.
	 */
	public BigDecimal getBigDecimalINTFECPAGO() {
		return fieldINTFECPAGO.getBigDecimal();
	}

	/**
	 * Set field INTLCAPT using a String value.
	 */
	public void setINTLCAPT(String newvalue) {
		fieldINTLCAPT.setString(newvalue);
	}

	/**
	 * Get value of field INTLCAPT as a String.
	 */
	public String getINTLCAPT() {
		return fieldINTLCAPT.getString();
	}

	/**
	 * Set field INTMONEDA using a String value.
	 */
	public void setINTMONEDA(String newvalue) {
		fieldINTMONEDA.setString(newvalue);
	}

	/**
	 * Get value of field INTMONEDA as a String.
	 */
	public String getINTMONEDA() {
		return fieldINTMONEDA.getString();
	}

	/**
	 * Set field INTIMPORTE using a String value.
	 */
	public void setINTIMPORTE(String newvalue) {
		fieldINTIMPORTE.setString(newvalue);
	}

	/**
	 * Get value of field INTIMPORTE as a String.
	 */
	public String getINTIMPORTE() {
		return fieldINTIMPORTE.getString();
	}

	/**
	 * Set numeric field INTIMPORTE using a BigDecimal value.
	 */
	public void setINTIMPORTE(BigDecimal newvalue) {
		fieldINTIMPORTE.setBigDecimal(newvalue);
	}

	/**
	 * Return value of numeric field INTIMPORTE as a BigDecimal.
	 */
	public BigDecimal getBigDecimalINTIMPORTE() {
		return fieldINTIMPORTE.getBigDecimal();
	}

	/**
	 * Set field INTNOMBRE using a String value.
	 */
	public void setINTNOMBRE(String newvalue) {
		fieldINTNOMBRE.setString(newvalue);
	}

	/**
	 * Get value of field INTNOMBRE as a String.
	 */
	public String getINTNOMBRE() {
		return fieldINTNOMBRE.getString();
	}

	/**
	 * Set field INTDIREC using a String value.
	 */
	public void setINTDIREC(String newvalue) {
		fieldINTDIREC.setString(newvalue);
	}

	/**
	 * Get value of field INTDIREC as a String.
	 */
	public String getINTDIREC() {
		return fieldINTDIREC.getString();
	}

	/**
	 * Set field INTCOLONIA using a String value.
	 */
	public void setINTCOLONIA(String newvalue) {
		fieldINTCOLONIA.setString(newvalue);
	}

	/**
	 * Get value of field INTCOLONIA as a String.
	 */
	public String getINTCOLONIA() {
		return fieldINTCOLONIA.getString();
	}

	/**
	 * Set field INTCODPOS using a String value.
	 */
	public void setINTCODPOS(String newvalue) {
		fieldINTCODPOS.setString(newvalue);
	}

	/**
	 * Get value of field INTCODPOS as a String.
	 */
	public String getINTCODPOS() {
		return fieldINTCODPOS.getString();
	}

	/**
	 * Set field INTDELEGA using a String value.
	 */
	public void setINTDELEGA(String newvalue) {
		fieldINTDELEGA.setString(newvalue);
	}

	/**
	 * Get value of field INTDELEGA as a String.
	 */
	public String getINTDELEGA() {
		return fieldINTDELEGA.getString();
	}

	/**
	 * Set field INTESTADO using a String value.
	 */
	public void setINTESTADO(String newvalue) {
		fieldINTESTADO.setString(newvalue);
	}

	/**
	 * Get value of field INTESTADO as a String.
	 */
	public String getINTESTADO() {
		return fieldINTESTADO.getString();
	}

	/**
	 * Set field INTCVETIPO using a String value.
	 */
	public void setINTCVETIPO(String newvalue) {
		fieldINTCVETIPO.setString(newvalue);
	}

	/**
	 * Get value of field INTCVETIPO as a String.
	 */
	public String getINTCVETIPO() {
		return fieldINTCVETIPO.getString();
	}

	/**
	 * Set field INTTIPO using a String value.
	 */
	public void setINTTIPO(String newvalue) {
		fieldINTTIPO.setString(newvalue);
	}

	/**
	 * Get value of field INTTIPO as a String.
	 */
	public String getINTTIPO() {
		return fieldINTTIPO.getString();
	}

	/**
	 * Set field INPERIODO using a String value.
	 */
	public void setINPERIODO(String newvalue) {
		fieldINPERIODO.setString(newvalue);
	}

	/**
	 * Get value of field INPERIODO as a String.
	 */
	public String getINPERIODO() {
		return fieldINPERIODO.getString();
	}

	/**
	 * Set field INTRFC using a String value.
	 */
	public void setINTRFC(String newvalue) {
		fieldINTRFC.setString(newvalue);
	}

	/**
	 * Get value of field INTRFC as a String.
	 */
	public String getINTRFC() {
		return fieldINTRFC.getString();
	}

	/**
	 * Set field INTPLACA using a String value.
	 */
	public void setINTPLACA(String newvalue) {
		fieldINTPLACA.setString(newvalue);
	}

	/**
	 * Get value of field INTPLACA as a String.
	 */
	public String getINTPLACA() {
		return fieldINTPLACA.getString();
	}

	/**
	 * Set field INTMODELO using a String value.
	 */
	public void setINTMODELO(String newvalue) {
		fieldINTMODELO.setString(newvalue);
	}

	/**
	 * Get value of field INTMODELO as a String.
	 */
	public String getINTMODELO() {
		return fieldINTMODELO.getString();
	}

	/**
	 * Set numeric field INTMODELO using a BigDecimal value.
	 */
	public void setINTMODELO(BigDecimal newvalue) {
		fieldINTMODELO.setBigDecimal(newvalue);
	}

	/**
	 * Return value of numeric field INTMODELO as a BigDecimal.
	 */
	public BigDecimal getBigDecimalINTMODELO() {
		return fieldINTMODELO.getBigDecimal();
	}

	/**
	 * Set field INCVEMARCA using a String value.
	 */
	public void setINCVEMARCA(String newvalue) {
		fieldINCVEMARCA.setString(newvalue);
	}

	/**
	 * Get value of field INCVEMARCA as a String.
	 */
	public String getINCVEMARCA() {
		return fieldINCVEMARCA.getString();
	}

	/**
	 * Set numeric field INCVEMARCA using a BigDecimal value.
	 */
	public void setINCVEMARCA(BigDecimal newvalue) {
		fieldINCVEMARCA.setBigDecimal(newvalue);
	}

	/**
	 * Return value of numeric field INCVEMARCA as a BigDecimal.
	 */
	public BigDecimal getBigDecimalINCVEMARCA() {
		return fieldINCVEMARCA.getBigDecimal();
	}

	/**
	 * Set field INTMARCA using a String value.
	 */
	public void setINTMARCA(String newvalue) {
		fieldINTMARCA.setString(newvalue);
	}

	/**
	 * Get value of field INTMARCA as a String.
	 */
	public String getINTMARCA() {
		return fieldINTMARCA.getString();
	}

	/**
	 * Set field INTFOLIO using a String value.
	 */
	public void setINTFOLIO(String newvalue) {
		fieldINTFOLIO.setString(newvalue);
	}

	/**
	 * Get value of field INTFOLIO as a String.
	 */
	public String getINTFOLIO() {
		return fieldINTFOLIO.getString();
	}

	/**
	 * Set numeric field INTFOLIO using a BigDecimal value.
	 */
	public void setINTFOLIO(BigDecimal newvalue) {
		fieldINTFOLIO.setBigDecimal(newvalue);
	}

	/**
	 * Return value of numeric field INTFOLIO as a BigDecimal.
	 */
	public BigDecimal getBigDecimalINTFOLIO() {
		return fieldINTFOLIO.getBigDecimal();
	}

	/**
	 * Set field INTANOINF using a String value.
	 */
	public void setINTANOINF(String newvalue) {
		fieldINTANOINF.setString(newvalue);
	}

	/**
	 * Get value of field INTANOINF as a String.
	 */
	public String getINTANOINF() {
		return fieldINTANOINF.getString();
	}

	/**
	 * Set numeric field INTANOINF using a BigDecimal value.
	 */
	public void setINTANOINF(BigDecimal newvalue) {
		fieldINTANOINF.setBigDecimal(newvalue);
	}

	/**
	 * Return value of numeric field INTANOINF as a BigDecimal.
	 */
	public BigDecimal getBigDecimalINTANOINF() {
		return fieldINTANOINF.getBigDecimal();
	}

	/**
	 * Set field INTCVEVER using a String value.
	 */
	public void setINTCVEVER(String newvalue) {
		fieldINTCVEVER.setString(newvalue);
	}

	/**
	 * Get value of field INTCVEVER as a String.
	 */
	public String getINTCVEVER() {
		return fieldINTCVEVER.getString();
	}

	/**
	 * Set numeric field INTCVEVER using a BigDecimal value.
	 */
	public void setINTCVEVER(BigDecimal newvalue) {
		fieldINTCVEVER.setBigDecimal(newvalue);
	}

	/**
	 * Return value of numeric field INTCVEVER as a BigDecimal.
	 */
	public BigDecimal getBigDecimalINTCVEVER() {
		return fieldINTCVEVER.getBigDecimal();
	}

	/**
	 * Set field INTCVEHOLO using a String value.
	 */
	public void setINTCVEHOLO(String newvalue) {
		fieldINTCVEHOLO.setString(newvalue);
	}

	/**
	 * Get value of field INTCVEHOLO as a String.
	 */
	public String getINTCVEHOLO() {
		return fieldINTCVEHOLO.getString();
	}

	/**
	 * Set field INTHOLOGR using a String value.
	 */
	public void setINTHOLOGR(String newvalue) {
		fieldINTHOLOGR.setString(newvalue);
	}

	/**
	 * Get value of field INTHOLOGR as a String.
	 */
	public String getINTHOLOGR() {
		return fieldINTHOLOGR.getString();
	}

	/**
	 * Set field INTCANT using a String value.
	 */
	public void setINTCANT(String newvalue) {
		fieldINTCANT.setString(newvalue);
	}

	/**
	 * Get value of field INTCANT as a String.
	 */
	public String getINTCANT() {
		return fieldINTCANT.getString();
	}

	/**
	 * Set numeric field INTCANT using a BigDecimal value.
	 */
	public void setINTCANT(BigDecimal newvalue) {
		fieldINTCANT.setBigDecimal(newvalue);
	}

	/**
	 * Return value of numeric field INTCANT as a BigDecimal.
	 */
	public BigDecimal getBigDecimalINTCANT() {
		return fieldINTCANT.getBigDecimal();
	}

	/**
	 * Set field INTFOLHOL using a String value.
	 */
	public void setINTFOLHOL(String newvalue) {
		fieldINTFOLHOL.setString(newvalue);
	}

	/**
	 * Get value of field INTFOLHOL as a String.
	 */
	public String getINTFOLHOL() {
		return fieldINTFOLHOL.getString();
	}

	/**
	 * Set numeric field INTFOLHOL using a BigDecimal value.
	 */
	public void setINTFOLHOL(BigDecimal newvalue) {
		fieldINTFOLHOL.setBigDecimal(newvalue);
	}

	/**
	 * Return value of numeric field INTFOLHOL as a BigDecimal.
	 */
	public BigDecimal getBigDecimalINTFOLHOL() {
		return fieldINTFOLHOL.getBigDecimal();
	}

	/**
	 * Set field INTFOLREG using a String value.
	 */
	public void setINTFOLREG(String newvalue) {
		fieldINTFOLREG.setString(newvalue);
	}

	/**
	 * Get value of field INTFOLREG as a String.
	 */
	public String getINTFOLREG() {
		return fieldINTFOLREG.getString();
	}

	/**
	 * Set numeric field INTFOLREG using a BigDecimal value.
	 */
	public void setINTFOLREG(BigDecimal newvalue) {
		fieldINTFOLREG.setBigDecimal(newvalue);
	}

	/**
	 * Return value of numeric field INTFOLREG as a BigDecimal.
	 */
	public BigDecimal getBigDecimalINTFOLREG() {
		return fieldINTFOLREG.getBigDecimal();
	}

	/**
	 * Set field INTPREUNI using a String value.
	 */
	public void setINTPREUNI(String newvalue) {
		fieldINTPREUNI.setString(newvalue);
	}

	/**
	 * Get value of field INTPREUNI as a String.
	 */
	public String getINTPREUNI() {
		return fieldINTPREUNI.getString();
	}

	/**
	 * Set numeric field INTPREUNI using a BigDecimal value.
	 */
	public void setINTPREUNI(BigDecimal newvalue) {
		fieldINTPREUNI.setBigDecimal(newvalue);
	}

	/**
	 * Return value of numeric field INTPREUNI as a BigDecimal.
	 */
	public BigDecimal getBigDecimalINTPREUNI() {
		return fieldINTPREUNI.getBigDecimal();
	}

	/**
	 * Set field INTFOLFACT using a String value.
	 */
	public void setINTFOLFACT(String newvalue) {
		fieldINTFOLFACT.setString(newvalue);
	}

	/**
	 * Get value of field INTFOLFACT as a String.
	 */
	public String getINTFOLFACT() {
		return fieldINTFOLFACT.getString();
	}

	/**
	 * Set numeric field INTFOLFACT using a BigDecimal value.
	 */
	public void setINTFOLFACT(BigDecimal newvalue) {
		fieldINTFOLFACT.setBigDecimal(newvalue);
	}

	/**
	 * Return value of numeric field INTFOLFACT as a BigDecimal.
	 */
	public BigDecimal getBigDecimalINTFOLFACT() {
		return fieldINTFOLFACT.getBigDecimal();
	}

	/**
	 * Set field INTCUENTA using a String value.
	 */
	public void setINTCUENTA(String newvalue) {
		fieldINTCUENTA.setString(newvalue);
	}

	/**
	 * Get value of field INTCUENTA as a String.
	 */
	public String getINTCUENTA() {
		return fieldINTCUENTA.getString();
	}

	/**
	 * Set field INTEJERC using a String value.
	 */
	public void setINTEJERC(String newvalue) {
		fieldINTEJERC.setString(newvalue);
	}

	/**
	 * Get value of field INTEJERC as a String.
	 */
	public String getINTEJERC() {
		return fieldINTEJERC.getString();
	}

	/**
	 * Set numeric field INTEJERC using a BigDecimal value.
	 */
	public void setINTEJERC(BigDecimal newvalue) {
		fieldINTEJERC.setBigDecimal(newvalue);
	}

	/**
	 * Return value of numeric field INTEJERC as a BigDecimal.
	 */
	public BigDecimal getBigDecimalINTEJERC() {
		return fieldINTEJERC.getBigDecimal();
	}

	/**
	 * Set field INTBIM using a String value.
	 */
	public void setINTBIM(String newvalue) {
		fieldINTBIM.setString(newvalue);
	}

	/**
	 * Get value of field INTBIM as a String.
	 */
	public String getINTBIM() {
		return fieldINTBIM.getString();
	}

	/**
	 * Set field INTEJEFIS using a String value.
	 */
	public void setINTEJEFIS(String newvalue) {
		fieldINTEJEFIS.setString(newvalue);
	}

	/**
	 * Get value of field INTEJEFIS as a String.
	 */
	public String getINTEJEFIS() {
		return fieldINTEJEFIS.getString();
	}

	/**
	 * Set numeric field INTEJEFIS using a BigDecimal value.
	 */
	public void setINTEJEFIS(BigDecimal newvalue) {
		fieldINTEJEFIS.setBigDecimal(newvalue);
	}

	/**
	 * Return value of numeric field INTEJEFIS as a BigDecimal.
	 */
	public BigDecimal getBigDecimalINTEJEFIS() {
		return fieldINTEJEFIS.getBigDecimal();
	}

	/**
	 * Set field INSUBMARCA using a String value.
	 */
	public void setINSUBMARCA(String newvalue) {
		fieldINSUBMARCA.setString(newvalue);
	}

	/**
	 * Get value of field INSUBMARCA as a String.
	 */
	public String getINSUBMARCA() {
		return fieldINSUBMARCA.getString();
	}

	/**
	 * Set field INTVALFACT using a String value.
	 */
	public void setINTVALFACT(String newvalue) {
		fieldINTVALFACT.setString(newvalue);
	}

	/**
	 * Get value of field INTVALFACT as a String.
	 */
	public String getINTVALFACT() {
		return fieldINTVALFACT.getString();
	}

	/**
	 * Set numeric field INTVALFACT using a BigDecimal value.
	 */
	public void setINTVALFACT(BigDecimal newvalue) {
		fieldINTVALFACT.setBigDecimal(newvalue);
	}

	/**
	 * Return value of numeric field INTVALFACT as a BigDecimal.
	 */
	public BigDecimal getBigDecimalINTVALFACT() {
		return fieldINTVALFACT.getBigDecimal();
	}

	/**
	 * Set field INTNCILIND using a String value.
	 */
	public void setINTNCILIND(String newvalue) {
		fieldINTNCILIND.setString(newvalue);
	}

	/**
	 * Get value of field INTNCILIND as a String.
	 */
	public String getINTNCILIND() {
		return fieldINTNCILIND.getString();
	}

	/**
	 * Set numeric field INTNCILIND using a BigDecimal value.
	 */
	public void setINTNCILIND(BigDecimal newvalue) {
		fieldINTNCILIND.setBigDecimal(newvalue);
	}

	/**
	 * Return value of numeric field INTNCILIND as a BigDecimal.
	 */
	public BigDecimal getBigDecimalINTNCILIND() {
		return fieldINTNCILIND.getBigDecimal();
	}

	/**
	 * Set field INTEJEIMP using a String value.
	 */
	public void setINTEJEIMP(String newvalue) {
		fieldINTEJEIMP.setString(newvalue);
	}

	/**
	 * Get value of field INTEJEIMP as a String.
	 */
	public String getINTEJEIMP() {
		return fieldINTEJEIMP.getString();
	}

	/**
	 * Set numeric field INTEJEIMP using a BigDecimal value.
	 */
	public void setINTEJEIMP(BigDecimal newvalue) {
		fieldINTEJEIMP.setBigDecimal(newvalue);
	}

	/**
	 * Return value of numeric field INTEJEIMP as a BigDecimal.
	 */
	public BigDecimal getBigDecimalINTEJEIMP() {
		return fieldINTEJEIMP.getBigDecimal();
	}

	/**
	 * Set field INTMESIMP using a String value.
	 */
	public void setINTMESIMP(String newvalue) {
		fieldINTMESIMP.setString(newvalue);
	}

	/**
	 * Get value of field INTMESIMP as a String.
	 */
	public String getINTMESIMP() {
		return fieldINTMESIMP.getString();
	}

	/**
	 * Set field INTIPODECL using a String value.
	 */
	public void setINTIPODECL(String newvalue) {
		fieldINTIPODECL.setString(newvalue);
	}

	/**
	 * Get value of field INTIPODECL as a String.
	 */
	public String getINTIPODECL() {
		return fieldINTIPODECL.getString();
	}

	/**
	 * Set numeric field INTIPODECL using a BigDecimal value.
	 */
	public void setINTIPODECL(BigDecimal newvalue) {
		fieldINTIPODECL.setBigDecimal(newvalue);
	}

	/**
	 * Return value of numeric field INTIPODECL as a BigDecimal.
	 */
	public BigDecimal getBigDecimalINTIPODECL() {
		return fieldINTIPODECL.getBigDecimal();
	}

	/**
	 * Set field INTRENUM using a String value.
	 */
	public void setINTRENUM(String newvalue) {
		fieldINTRENUM.setString(newvalue);
	}

	/**
	 * Get value of field INTRENUM as a String.
	 */
	public String getINTRENUM() {
		return fieldINTRENUM.getString();
	}

	/**
	 * Set numeric field INTRENUM using a BigDecimal value.
	 */
	public void setINTRENUM(BigDecimal newvalue) {
		fieldINTRENUM.setBigDecimal(newvalue);
	}

	/**
	 * Return value of numeric field INTRENUM as a BigDecimal.
	 */
	public BigDecimal getBigDecimalINTRENUM() {
		return fieldINTRENUM.getBigDecimal();
	}

	/**
	 * Set field INTNUMTRAB using a String value.
	 */
	public void setINTNUMTRAB(String newvalue) {
		fieldINTNUMTRAB.setString(newvalue);
	}

	/**
	 * Get value of field INTNUMTRAB as a String.
	 */
	public String getINTNUMTRAB() {
		return fieldINTNUMTRAB.getString();
	}

	/**
	 * Set numeric field INTNUMTRAB using a BigDecimal value.
	 */
	public void setINTNUMTRAB(BigDecimal newvalue) {
		fieldINTNUMTRAB.setBigDecimal(newvalue);
	}

	/**
	 * Return value of numeric field INTNUMTRAB as a BigDecimal.
	 */
	public BigDecimal getBigDecimalINTNUMTRAB() {
		return fieldINTNUMTRAB.getBigDecimal();
	}

	/**
	 * Set field INTFECEVEN using a String value.
	 */
	public void setINTFECEVEN(String newvalue) {
		fieldINTFECEVEN.setString(newvalue);
	}

	/**
	 * Get value of field INTFECEVEN as a String.
	 */
	public String getINTFECEVEN() {
		return fieldINTFECEVEN.getString();
	}

	/**
	 * Set field INCVEOPER using a String value.
	 */
	public void setINCVEOPER(String newvalue) {
		fieldINCVEOPER.setString(newvalue);
	}

	/**
	 * Get value of field INCVEOPER as a String.
	 */
	public String getINCVEOPER() {
		return fieldINCVEOPER.getString();
	}

	/**
	 * Set field INTIPOPER using a String value.
	 */
	public void setINTIPOPER(String newvalue) {
		fieldINTIPOPER.setString(newvalue);
	}

	/**
	 * Get value of field INTIPOPER as a String.
	 */
	public String getINTIPOPER() {
		return fieldINTIPOPER.getString();
	}

	/**
	 * Set field INTFECESC using a String value.
	 */
	public void setINTFECESC(String newvalue) {
		fieldINTFECESC.setString(newvalue);
	}

	/**
	 * Get value of field INTFECESC as a String.
	 */
	public String getINTFECESC() {
		return fieldINTFECESC.getString();
	}

	/**
	 * Set numeric field INTFECESC using a BigDecimal value.
	 */
	public void setINTFECESC(BigDecimal newvalue) {
		fieldINTFECESC.setBigDecimal(newvalue);
	}

	/**
	 * Return value of numeric field INTFECESC as a BigDecimal.
	 */
	public BigDecimal getBigDecimalINTFECESC() {
		return fieldINTFECESC.getBigDecimal();
	}

	/**
	 * Set field INTFOLPROP using a String value.
	 */
	public void setINTFOLPROP(String newvalue) {
		fieldINTFOLPROP.setString(newvalue);
	}

	/**
	 * Get value of field INTFOLPROP as a String.
	 */
	public String getINTFOLPROP() {
		return fieldINTFOLPROP.getString();
	}

	/**
	 * Set numeric field INTFOLPROP using a BigDecimal value.
	 */
	public void setINTFOLPROP(BigDecimal newvalue) {
		fieldINTFOLPROP.setBigDecimal(newvalue);
	}

	/**
	 * Return value of numeric field INTFOLPROP as a BigDecimal.
	 */
	public BigDecimal getBigDecimalINTFOLPROP() {
		return fieldINTFOLPROP.getBigDecimal();
	}

	/**
	 * Set field INCVETRAM using a String value.
	 */
	public void setINCVETRAM(String newvalue) {
		fieldINCVETRAM.setString(newvalue);
	}

	/**
	 * Get value of field INCVETRAM as a String.
	 */
	public String getINCVETRAM() {
		return fieldINCVETRAM.getString();
	}

	/**
	 * Set field INTRAMITE using a String value.
	 */
	public void setINTRAMITE(String newvalue) {
		fieldINTRAMITE.setString(newvalue);
	}

	/**
	 * Get value of field INTRAMITE as a String.
	 */
	public String getINTRAMITE() {
		return fieldINTRAMITE.getString();
	}

	/**
	 * Set field INTNUMESC using a String value.
	 */
	public void setINTNUMESC(String newvalue) {
		fieldINTNUMESC.setString(newvalue);
	}

	/**
	 * Get value of field INTNUMESC as a String.
	 */
	public String getINTNUMESC() {
		return fieldINTNUMESC.getString();
	}

	/**
	 * Set field INVIGENCIA using a String value.
	 */
	public void setINVIGENCIA(String newvalue) {
		fieldINVIGENCIA.setString(newvalue);
	}

	/**
	 * Get value of field INVIGENCIA as a String.
	 */
	public String getINVIGENCIA() {
		return fieldINVIGENCIA.getString();
	}

	/**
	 * Set numeric field INVIGENCIA using a BigDecimal value.
	 */
	public void setINVIGENCIA(BigDecimal newvalue) {
		fieldINVIGENCIA.setBigDecimal(newvalue);
	}

	/**
	 * Return value of numeric field INVIGENCIA as a BigDecimal.
	 */
	public BigDecimal getBigDecimalINVIGENCIA() {
		return fieldINVIGENCIA.getBigDecimal();
	}

	/**
	 * Set field INTNOTARIO using a String value.
	 */
	public void setINTNOTARIO(String newvalue) {
		fieldINTNOTARIO.setString(newvalue);
	}

	/**
	 * Get value of field INTNOTARIO as a String.
	 */
	public String getINTNOTARIO() {
		return fieldINTNOTARIO.getString();
	}

	/**
	 * Set field INTCERTIF using a String value.
	 */
	public void setINTCERTIF(String newvalue) {
		fieldINTCERTIF.setString(newvalue);
	}

	/**
	 * Get value of field INTCERTIF as a String.
	 */
	public String getINTCERTIF() {
		return fieldINTCERTIF.getString();
	}

	/**
	 * Set field INTTIF using a String value.
	 */
	public void setINTTIF(String newvalue) {
		fieldINTTIF.setString(newvalue);
	}

	/**
	 * Get value of field INTTIF as a String.
	 */
	public String getINTTIF() {
		return fieldINTTIF.getString();
	}

	/**
	 * Set numeric field INTTIF using a BigDecimal value.
	 */
	public void setINTTIF(BigDecimal newvalue) {
		fieldINTTIF.setBigDecimal(newvalue);
	}

	/**
	 * Return value of numeric field INTTIF as a BigDecimal.
	 */
	public BigDecimal getBigDecimalINTTIF() {
		return fieldINTTIF.getBigDecimal();
	}

	/**
	 * Set field INTSTS using a String value.
	 */
	public void setINTSTS(String newvalue) {
		fieldINTSTS.setString(newvalue);
	}

	/**
	 * Get value of field INTSTS as a String.
	 */
	public String getINTSTS() {
		return fieldINTSTS.getString();
	}

	/**
	 * Set field INTORIGEN using a String value.
	 */
	public void setINTORIGEN(String newvalue) {
		fieldINTORIGEN.setString(newvalue);
	}

	/**
	 * Get value of field INTORIGEN as a String.
	 */
	public String getINTORIGEN() {
		return fieldINTORIGEN.getString();
	}

	/**
	 * Set field INTSUBCPTO using a String value.
	 */
	public void setINTSUBCPTO(String newvalue) {
		fieldINTSUBCPTO.setString(newvalue);
	}

	/**
	 * Get value of field INTSUBCPTO as a String.
	 */
	public String getINTSUBCPTO() {
		return fieldINTSUBCPTO.getString();
	}

	/**
	 * Set field INTREFPAGO using a String value.
	 */
	public void setINTREFPAGO(String newvalue) {
		fieldINTREFPAGO.setString(newvalue);
	}

	/**
	 * Get value of field INTREFPAGO as a String.
	 */
	public String getINTREFPAGO() {
		return fieldINTREFPAGO.getString();
	}

	/**
	 * Set field INTCVEADTR using a String value.
	 */
	public void setINTCVEADTR(String newvalue) {
		fieldINTCVEADTR.setString(newvalue);
	}

	/**
	 * Get value of field INTCVEADTR as a String.
	 */
	public String getINTCVEADTR() {
		return fieldINTCVEADTR.getString();
	}

}
