package com.afirme.afirmenet.ibs.messages;

import java.math.BigDecimal;

import com.datapro.sockets.CharacterField;
import com.datapro.sockets.DecimalField;
import com.datapro.sockets.MessageField;
import com.datapro.sockets.MessageRecord;

/**
 * Class generated by AS/400 CRTCLASS command from LNSDSJV physical file
 * definition.
 * 
 * File level identifier is 1000802211859. Record format level identifier is
 * 41A00A6F26743.
 */

public class LNSDSJVMessage extends MessageRecord {
	final int FIELDCOUNT = 26;
	private CharacterField fieldLNSUSR = null;
	private DecimalField fieldLNSACC = null;
	private CharacterField fieldLNSCCY = null;
	private DecimalField fieldLNSPRI = null;
	private DecimalField fieldLNSINT = null;
	private DecimalField fieldLNSLCH = null;
	private DecimalField fieldLNSSCR = null;
	private DecimalField fieldLNSPOF = null;
	private DecimalField fieldLNSPMT = null;
	private DecimalField fieldLNSNOP1 = null;
	private DecimalField fieldLNSNOP2 = null;
	private DecimalField fieldLNSNOP3 = null;
	private DecimalField fieldLNSNXP1 = null;
	private DecimalField fieldLNSNXP2 = null;
	private DecimalField fieldLNSNXP3 = null;
	private DecimalField fieldLNSMAT1 = null;
	private DecimalField fieldLNSMAT2 = null;
	private DecimalField fieldLNSMAT3 = null;
	private DecimalField fieldLNSRTE = null;
	private DecimalField fieldLNSCLI = null;
	private DecimalField fieldLNSIPY = null;
	private DecimalField fieldLNSPPY = null;
	private DecimalField fieldLNSLST1 = null;
	private DecimalField fieldLNSLST2 = null;
	private DecimalField fieldLNSLST3 = null;
	private DecimalField fieldLNSAVB = null;

	/**
	 * Constructor for LNSDSJVMessage.
	 */
	public LNSDSJVMessage() {
		createFields();
		initialize();
	}

	/**
	 * Create fields for this message. This method implements the abstract
	 * method in the MessageRecord superclass.
	 */
	protected void createFields() {
		recordsize = 225;
		fileid = "1000802211859";
		recordid = "41A00A6F26743";
		message = new byte[getByteLength()];
		formatname = "LNSDSJV";
		fieldnames = new String[FIELDCOUNT];
		tagnames = new String[FIELDCOUNT];
		fields = new MessageField[FIELDCOUNT];

		fieldnames[0] = "LNSUSR";
		tagnames[0] = "LNSUSR";
		fields[0] = fieldLNSUSR = new CharacterField(message, HEADERSIZE + 0,
				10, "LNSUSR");
		fieldnames[1] = "LNSACC";
		tagnames[1] = "LNSACC";
		fields[1] = fieldLNSACC = new DecimalField(message, HEADERSIZE + 10,
				13, 0, "LNSACC");
		fieldnames[2] = "LNSCCY";
		tagnames[2] = "LNSCCY";
		fields[2] = fieldLNSCCY = new CharacterField(message, HEADERSIZE + 23,
				3, "LNSCCY");
		fieldnames[3] = "LNSPRI";
		tagnames[3] = "LNSPRI";
		fields[3] = fieldLNSPRI = new DecimalField(message, HEADERSIZE + 26,
				15, 2, "LNSPRI");
		fieldnames[4] = "LNSINT";
		tagnames[4] = "LNSINT";
		fields[4] = fieldLNSINT = new DecimalField(message, HEADERSIZE + 41,
				15, 2, "LNSINT");
		fieldnames[5] = "LNSLCH";
		tagnames[5] = "LNSLCH";
		fields[5] = fieldLNSLCH = new DecimalField(message, HEADERSIZE + 56,
				15, 2, "LNSLCH");
		fieldnames[6] = "LNSSCR";
		tagnames[6] = "LNSSCR";
		fields[6] = fieldLNSSCR = new DecimalField(message, HEADERSIZE + 71,
				15, 2, "LNSSCR");
		fieldnames[7] = "LNSPOF";
		tagnames[7] = "LNSPOF";
		fields[7] = fieldLNSPOF = new DecimalField(message, HEADERSIZE + 86,
				15, 2, "LNSPOF");
		fieldnames[8] = "LNSPMT";
		tagnames[8] = "LNSPMT";
		fields[8] = fieldLNSPMT = new DecimalField(message, HEADERSIZE + 101,
				15, 2, "LNSPMT");
		fieldnames[9] = "LNSNOP1";
		tagnames[9] = "LNSNOP1";
		fields[9] = fieldLNSNOP1 = new DecimalField(message, HEADERSIZE + 116,
				3, 0, "LNSNOP1");
		fieldnames[10] = "LNSNOP2";
		tagnames[10] = "LNSNOP2";
		fields[10] = fieldLNSNOP2 = new DecimalField(message, HEADERSIZE + 119,
				3, 0, "LNSNOP2");
		fieldnames[11] = "LNSNOP3";
		tagnames[11] = "LNSNOP3";
		fields[11] = fieldLNSNOP3 = new DecimalField(message, HEADERSIZE + 122,
				3, 0, "LNSNOP3");
		fieldnames[12] = "LNSNXP1";
		tagnames[12] = "LNSNXP1";
		fields[12] = fieldLNSNXP1 = new DecimalField(message, HEADERSIZE + 125,
				3, 0, "LNSNXP1");
		fieldnames[13] = "LNSNXP2";
		tagnames[13] = "LNSNXP2";
		fields[13] = fieldLNSNXP2 = new DecimalField(message, HEADERSIZE + 128,
				3, 0, "LNSNXP2");
		fieldnames[14] = "LNSNXP3";
		tagnames[14] = "LNSNXP3";
		fields[14] = fieldLNSNXP3 = new DecimalField(message, HEADERSIZE + 131,
				3, 0, "LNSNXP3");
		fieldnames[15] = "LNSMAT1";
		tagnames[15] = "LNSMAT1";
		fields[15] = fieldLNSMAT1 = new DecimalField(message, HEADERSIZE + 134,
				3, 0, "LNSMAT1");
		fieldnames[16] = "LNSMAT2";
		tagnames[16] = "LNSMAT2";
		fields[16] = fieldLNSMAT2 = new DecimalField(message, HEADERSIZE + 137,
				3, 0, "LNSMAT2");
		fieldnames[17] = "LNSMAT3";
		tagnames[17] = "LNSMAT3";
		fields[17] = fieldLNSMAT3 = new DecimalField(message, HEADERSIZE + 140,
				3, 0, "LNSMAT3");
		fieldnames[18] = "LNSRTE";
		tagnames[18] = "LNSRTE";
		fields[18] = fieldLNSRTE = new DecimalField(message, HEADERSIZE + 143,
				11, 6, "LNSRTE");
		fieldnames[19] = "LNSCLI";
		tagnames[19] = "LNSCLI";
		fields[19] = fieldLNSCLI = new DecimalField(message, HEADERSIZE + 154,
				15, 2, "LNSCLI");
		fieldnames[20] = "LNSIPY";
		tagnames[20] = "LNSIPY";
		fields[20] = fieldLNSIPY = new DecimalField(message, HEADERSIZE + 169,
				15, 2, "LNSIPY");
		fieldnames[21] = "LNSPPY";
		tagnames[21] = "LNSPPY";
		fields[21] = fieldLNSPPY = new DecimalField(message, HEADERSIZE + 184,
				15, 2, "LNSPPY");
		fieldnames[22] = "LNSLST1";
		tagnames[22] = "LNSLST1";
		fields[22] = fieldLNSLST1 = new DecimalField(message, HEADERSIZE + 199,
				3, 0, "LNSLST1");
		fieldnames[23] = "LNSLST2";
		tagnames[23] = "LNSLST2";
		fields[23] = fieldLNSLST2 = new DecimalField(message, HEADERSIZE + 202,
				3, 0, "LNSLST2");
		fieldnames[24] = "LNSLST3";
		tagnames[24] = "LNSLST3";
		fields[24] = fieldLNSLST3 = new DecimalField(message, HEADERSIZE + 205,
				3, 0, "LNSLST3");
		fieldnames[25] = "LNSAVB";
		tagnames[25] = "LNSAVB";
		fields[25] = fieldLNSAVB = new DecimalField(message, HEADERSIZE + 208,
				17, 2, "LNSAVB");
	}

	/**
	 * Return value of numeric field LNSACC as a BigDecimal.
	 */
	public BigDecimal getBigDecimalLNSACC() {
		return fieldLNSACC.getBigDecimal();
	}

	/**
	 * Return value of numeric field LNSAVB as a BigDecimal.
	 */
	public BigDecimal getBigDecimalLNSAVB() {
		return fieldLNSAVB.getBigDecimal();
	}

	/**
	 * Return value of numeric field LNSCLI as a BigDecimal.
	 */
	public BigDecimal getBigDecimalLNSCLI() {
		return fieldLNSCLI.getBigDecimal();
	}

	/**
	 * Return value of numeric field LNSINT as a BigDecimal.
	 */
	public BigDecimal getBigDecimalLNSINT() {
		return fieldLNSINT.getBigDecimal();
	}

	/**
	 * Return value of numeric field LNSIPY as a BigDecimal.
	 */
	public BigDecimal getBigDecimalLNSIPY() {
		return fieldLNSIPY.getBigDecimal();
	}

	/**
	 * Return value of numeric field LNSLCH as a BigDecimal.
	 */
	public BigDecimal getBigDecimalLNSLCH() {
		return fieldLNSLCH.getBigDecimal();
	}

	/**
	 * Return value of numeric field LNSLST1 as a BigDecimal.
	 */
	public BigDecimal getBigDecimalLNSLST1() {
		return fieldLNSLST1.getBigDecimal();
	}

	/**
	 * Return value of numeric field LNSLST2 as a BigDecimal.
	 */
	public BigDecimal getBigDecimalLNSLST2() {
		return fieldLNSLST2.getBigDecimal();
	}

	/**
	 * Return value of numeric field LNSLST3 as a BigDecimal.
	 */
	public BigDecimal getBigDecimalLNSLST3() {
		return fieldLNSLST3.getBigDecimal();
	}

	/**
	 * Return value of numeric field LNSMAT1 as a BigDecimal.
	 */
	public BigDecimal getBigDecimalLNSMAT1() {
		return fieldLNSMAT1.getBigDecimal();
	}

	/**
	 * Return value of numeric field LNSMAT2 as a BigDecimal.
	 */
	public BigDecimal getBigDecimalLNSMAT2() {
		return fieldLNSMAT2.getBigDecimal();
	}

	/**
	 * Return value of numeric field LNSMAT3 as a BigDecimal.
	 */
	public BigDecimal getBigDecimalLNSMAT3() {
		return fieldLNSMAT3.getBigDecimal();
	}

	/**
	 * Return value of numeric field LNSNOP1 as a BigDecimal.
	 */
	public BigDecimal getBigDecimalLNSNOP1() {
		return fieldLNSNOP1.getBigDecimal();
	}

	/**
	 * Return value of numeric field LNSNOP2 as a BigDecimal.
	 */
	public BigDecimal getBigDecimalLNSNOP2() {
		return fieldLNSNOP2.getBigDecimal();
	}

	/**
	 * Return value of numeric field LNSNOP3 as a BigDecimal.
	 */
	public BigDecimal getBigDecimalLNSNOP3() {
		return fieldLNSNOP3.getBigDecimal();
	}

	/**
	 * Return value of numeric field LNSNXP1 as a BigDecimal.
	 */
	public BigDecimal getBigDecimalLNSNXP1() {
		return fieldLNSNXP1.getBigDecimal();
	}

	/**
	 * Return value of numeric field LNSNXP2 as a BigDecimal.
	 */
	public BigDecimal getBigDecimalLNSNXP2() {
		return fieldLNSNXP2.getBigDecimal();
	}

	/**
	 * Return value of numeric field LNSNXP3 as a BigDecimal.
	 */
	public BigDecimal getBigDecimalLNSNXP3() {
		return fieldLNSNXP3.getBigDecimal();
	}

	/**
	 * Return value of numeric field LNSPMT as a BigDecimal.
	 */
	public BigDecimal getBigDecimalLNSPMT() {
		return fieldLNSPMT.getBigDecimal();
	}

	/**
	 * Return value of numeric field LNSPOF as a BigDecimal.
	 */
	public BigDecimal getBigDecimalLNSPOF() {
		return fieldLNSPOF.getBigDecimal();
	}

	/**
	 * Return value of numeric field LNSPPY as a BigDecimal.
	 */
	public BigDecimal getBigDecimalLNSPPY() {
		return fieldLNSPPY.getBigDecimal();
	}

	/**
	 * Return value of numeric field LNSPRI as a BigDecimal.
	 */
	public BigDecimal getBigDecimalLNSPRI() {
		return fieldLNSPRI.getBigDecimal();
	}

	/**
	 * Return value of numeric field LNSRTE as a BigDecimal.
	 */
	public BigDecimal getBigDecimalLNSRTE() {
		return fieldLNSRTE.getBigDecimal();
	}

	/**
	 * Return value of numeric field LNSSCR as a BigDecimal.
	 */
	public BigDecimal getBigDecimalLNSSCR() {
		return fieldLNSSCR.getBigDecimal();
	}

	/**
	 * Get value of field LNSACC as a String.
	 */
	public String getLNSACC() {
		return fieldLNSACC.getString();
	}

	/**
	 * Get value of field LNSAVB as a String.
	 */
	public String getLNSAVB() {
		return fieldLNSAVB.getString();
	}

	/**
	 * Get value of field LNSCCY as a String.
	 */
	public String getLNSCCY() {
		return fieldLNSCCY.getString();
	}

	/**
	 * Get value of field LNSCLI as a String.
	 */
	public String getLNSCLI() {
		return fieldLNSCLI.getString();
	}

	/**
	 * Get value of field LNSINT as a String.
	 */
	public String getLNSINT() {
		return fieldLNSINT.getString();
	}

	/**
	 * Get value of field LNSIPY as a String.
	 */
	public String getLNSIPY() {
		return fieldLNSIPY.getString();
	}

	/**
	 * Get value of field LNSLCH as a String.
	 */
	public String getLNSLCH() {
		return fieldLNSLCH.getString();
	}

	/**
	 * Get value of field LNSLST1 as a String.
	 */
	public String getLNSLST1() {
		return fieldLNSLST1.getString();
	}

	/**
	 * Get value of field LNSLST2 as a String.
	 */
	public String getLNSLST2() {
		return fieldLNSLST2.getString();
	}

	/**
	 * Get value of field LNSLST3 as a String.
	 */
	public String getLNSLST3() {
		return fieldLNSLST3.getString();
	}

	/**
	 * Get value of field LNSMAT1 as a String.
	 */
	public String getLNSMAT1() {
		return fieldLNSMAT1.getString();
	}

	/**
	 * Get value of field LNSMAT2 as a String.
	 */
	public String getLNSMAT2() {
		return fieldLNSMAT2.getString();
	}

	/**
	 * Get value of field LNSMAT3 as a String.
	 */
	public String getLNSMAT3() {
		return fieldLNSMAT3.getString();
	}

	/**
	 * Get value of field LNSNOP1 as a String.
	 */
	public String getLNSNOP1() {
		return fieldLNSNOP1.getString();
	}

	/**
	 * Get value of field LNSNOP2 as a String.
	 */
	public String getLNSNOP2() {
		return fieldLNSNOP2.getString();
	}

	/**
	 * Get value of field LNSNOP3 as a String.
	 */
	public String getLNSNOP3() {
		return fieldLNSNOP3.getString();
	}

	/**
	 * Get value of field LNSNXP1 as a String.
	 */
	public String getLNSNXP1() {
		return fieldLNSNXP1.getString();
	}

	/**
	 * Get value of field LNSNXP2 as a String.
	 */
	public String getLNSNXP2() {
		return fieldLNSNXP2.getString();
	}

	/**
	 * Get value of field LNSNXP3 as a String.
	 */
	public String getLNSNXP3() {
		return fieldLNSNXP3.getString();
	}

	/**
	 * Get value of field LNSPMT as a String.
	 */
	public String getLNSPMT() {
		return fieldLNSPMT.getString();
	}

	/**
	 * Get value of field LNSPOF as a String.
	 */
	public String getLNSPOF() {
		return fieldLNSPOF.getString();
	}

	/**
	 * Get value of field LNSPPY as a String.
	 */
	public String getLNSPPY() {
		return fieldLNSPPY.getString();
	}

	/**
	 * Get value of field LNSPRI as a String.
	 */
	public String getLNSPRI() {
		return fieldLNSPRI.getString();
	}

	/**
	 * Get value of field LNSRTE as a String.
	 */
	public String getLNSRTE() {
		return fieldLNSRTE.getString();
	}

	/**
	 * Get value of field LNSSCR as a String.
	 */
	public String getLNSSCR() {
		return fieldLNSSCR.getString();
	}

	/**
	 * Get value of field LNSUSR as a String.
	 */
	public String getLNSUSR() {
		return fieldLNSUSR.getString();
	}

	/**
	 * Set field LNSACC using a String value.
	 */
	public void setLNSACC(String newvalue) {
		fieldLNSACC.setString(newvalue);
	}

	/**
	 * Set numeric field LNSACC using a BigDecimal value.
	 */
	public void setLNSACC(BigDecimal newvalue) {
		fieldLNSACC.setBigDecimal(newvalue);
	}

	/**
	 * Set field LNSAVB using a String value.
	 */
	public void setLNSAVB(String newvalue) {
		fieldLNSAVB.setString(newvalue);
	}

	/**
	 * Set numeric field LNSAVB using a BigDecimal value.
	 */
	public void setLNSAVB(BigDecimal newvalue) {
		fieldLNSAVB.setBigDecimal(newvalue);
	}

	/**
	 * Set field LNSCCY using a String value.
	 */
	public void setLNSCCY(String newvalue) {
		fieldLNSCCY.setString(newvalue);
	}

	/**
	 * Set field LNSCLI using a String value.
	 */
	public void setLNSCLI(String newvalue) {
		fieldLNSCLI.setString(newvalue);
	}

	/**
	 * Set numeric field LNSCLI using a BigDecimal value.
	 */
	public void setLNSCLI(BigDecimal newvalue) {
		fieldLNSCLI.setBigDecimal(newvalue);
	}

	/**
	 * Set field LNSINT using a String value.
	 */
	public void setLNSINT(String newvalue) {
		fieldLNSINT.setString(newvalue);
	}

	/**
	 * Set numeric field LNSINT using a BigDecimal value.
	 */
	public void setLNSINT(BigDecimal newvalue) {
		fieldLNSINT.setBigDecimal(newvalue);
	}

	/**
	 * Set field LNSIPY using a String value.
	 */
	public void setLNSIPY(String newvalue) {
		fieldLNSIPY.setString(newvalue);
	}

	/**
	 * Set numeric field LNSIPY using a BigDecimal value.
	 */
	public void setLNSIPY(BigDecimal newvalue) {
		fieldLNSIPY.setBigDecimal(newvalue);
	}

	/**
	 * Set field LNSLCH using a String value.
	 */
	public void setLNSLCH(String newvalue) {
		fieldLNSLCH.setString(newvalue);
	}

	/**
	 * Set numeric field LNSLCH using a BigDecimal value.
	 */
	public void setLNSLCH(BigDecimal newvalue) {
		fieldLNSLCH.setBigDecimal(newvalue);
	}

	/**
	 * Set field LNSLST1 using a String value.
	 */
	public void setLNSLST1(String newvalue) {
		fieldLNSLST1.setString(newvalue);
	}

	/**
	 * Set numeric field LNSLST1 using a BigDecimal value.
	 */
	public void setLNSLST1(BigDecimal newvalue) {
		fieldLNSLST1.setBigDecimal(newvalue);
	}

	/**
	 * Set field LNSLST2 using a String value.
	 */
	public void setLNSLST2(String newvalue) {
		fieldLNSLST2.setString(newvalue);
	}

	/**
	 * Set numeric field LNSLST2 using a BigDecimal value.
	 */
	public void setLNSLST2(BigDecimal newvalue) {
		fieldLNSLST2.setBigDecimal(newvalue);
	}

	/**
	 * Set field LNSLST3 using a String value.
	 */
	public void setLNSLST3(String newvalue) {
		fieldLNSLST3.setString(newvalue);
	}

	/**
	 * Set numeric field LNSLST3 using a BigDecimal value.
	 */
	public void setLNSLST3(BigDecimal newvalue) {
		fieldLNSLST3.setBigDecimal(newvalue);
	}

	/**
	 * Set field LNSMAT1 using a String value.
	 */
	public void setLNSMAT1(String newvalue) {
		fieldLNSMAT1.setString(newvalue);
	}

	/**
	 * Set numeric field LNSMAT1 using a BigDecimal value.
	 */
	public void setLNSMAT1(BigDecimal newvalue) {
		fieldLNSMAT1.setBigDecimal(newvalue);
	}

	/**
	 * Set field LNSMAT2 using a String value.
	 */
	public void setLNSMAT2(String newvalue) {
		fieldLNSMAT2.setString(newvalue);
	}

	/**
	 * Set numeric field LNSMAT2 using a BigDecimal value.
	 */
	public void setLNSMAT2(BigDecimal newvalue) {
		fieldLNSMAT2.setBigDecimal(newvalue);
	}

	/**
	 * Set field LNSMAT3 using a String value.
	 */
	public void setLNSMAT3(String newvalue) {
		fieldLNSMAT3.setString(newvalue);
	}

	/**
	 * Set numeric field LNSMAT3 using a BigDecimal value.
	 */
	public void setLNSMAT3(BigDecimal newvalue) {
		fieldLNSMAT3.setBigDecimal(newvalue);
	}

	/**
	 * Set field LNSNOP1 using a String value.
	 */
	public void setLNSNOP1(String newvalue) {
		fieldLNSNOP1.setString(newvalue);
	}

	/**
	 * Set numeric field LNSNOP1 using a BigDecimal value.
	 */
	public void setLNSNOP1(BigDecimal newvalue) {
		fieldLNSNOP1.setBigDecimal(newvalue);
	}

	/**
	 * Set field LNSNOP2 using a String value.
	 */
	public void setLNSNOP2(String newvalue) {
		fieldLNSNOP2.setString(newvalue);
	}

	/**
	 * Set numeric field LNSNOP2 using a BigDecimal value.
	 */
	public void setLNSNOP2(BigDecimal newvalue) {
		fieldLNSNOP2.setBigDecimal(newvalue);
	}

	/**
	 * Set field LNSNOP3 using a String value.
	 */
	public void setLNSNOP3(String newvalue) {
		fieldLNSNOP3.setString(newvalue);
	}

	/**
	 * Set numeric field LNSNOP3 using a BigDecimal value.
	 */
	public void setLNSNOP3(BigDecimal newvalue) {
		fieldLNSNOP3.setBigDecimal(newvalue);
	}

	/**
	 * Set field LNSNXP1 using a String value.
	 */
	public void setLNSNXP1(String newvalue) {
		fieldLNSNXP1.setString(newvalue);
	}

	/**
	 * Set numeric field LNSNXP1 using a BigDecimal value.
	 */
	public void setLNSNXP1(BigDecimal newvalue) {
		fieldLNSNXP1.setBigDecimal(newvalue);
	}

	/**
	 * Set field LNSNXP2 using a String value.
	 */
	public void setLNSNXP2(String newvalue) {
		fieldLNSNXP2.setString(newvalue);
	}

	/**
	 * Set numeric field LNSNXP2 using a BigDecimal value.
	 */
	public void setLNSNXP2(BigDecimal newvalue) {
		fieldLNSNXP2.setBigDecimal(newvalue);
	}

	/**
	 * Set field LNSNXP3 using a String value.
	 */
	public void setLNSNXP3(String newvalue) {
		fieldLNSNXP3.setString(newvalue);
	}

	/**
	 * Set numeric field LNSNXP3 using a BigDecimal value.
	 */
	public void setLNSNXP3(BigDecimal newvalue) {
		fieldLNSNXP3.setBigDecimal(newvalue);
	}

	/**
	 * Set field LNSPMT using a String value.
	 */
	public void setLNSPMT(String newvalue) {
		fieldLNSPMT.setString(newvalue);
	}

	/**
	 * Set numeric field LNSPMT using a BigDecimal value.
	 */
	public void setLNSPMT(BigDecimal newvalue) {
		fieldLNSPMT.setBigDecimal(newvalue);
	}

	/**
	 * Set field LNSPOF using a String value.
	 */
	public void setLNSPOF(String newvalue) {
		fieldLNSPOF.setString(newvalue);
	}

	/**
	 * Set numeric field LNSPOF using a BigDecimal value.
	 */
	public void setLNSPOF(BigDecimal newvalue) {
		fieldLNSPOF.setBigDecimal(newvalue);
	}

	/**
	 * Set field LNSPPY using a String value.
	 */
	public void setLNSPPY(String newvalue) {
		fieldLNSPPY.setString(newvalue);
	}

	/**
	 * Set numeric field LNSPPY using a BigDecimal value.
	 */
	public void setLNSPPY(BigDecimal newvalue) {
		fieldLNSPPY.setBigDecimal(newvalue);
	}

	/**
	 * Set field LNSPRI using a String value.
	 */
	public void setLNSPRI(String newvalue) {
		fieldLNSPRI.setString(newvalue);
	}

	/**
	 * Set numeric field LNSPRI using a BigDecimal value.
	 */
	public void setLNSPRI(BigDecimal newvalue) {
		fieldLNSPRI.setBigDecimal(newvalue);
	}

	/**
	 * Set field LNSRTE using a String value.
	 */
	public void setLNSRTE(String newvalue) {
		fieldLNSRTE.setString(newvalue);
	}

	/**
	 * Set numeric field LNSRTE using a BigDecimal value.
	 */
	public void setLNSRTE(BigDecimal newvalue) {
		fieldLNSRTE.setBigDecimal(newvalue);
	}

	/**
	 * Set field LNSSCR using a String value.
	 */
	public void setLNSSCR(String newvalue) {
		fieldLNSSCR.setString(newvalue);
	}

	/**
	 * Set numeric field LNSSCR using a BigDecimal value.
	 */
	public void setLNSSCR(BigDecimal newvalue) {
		fieldLNSSCR.setBigDecimal(newvalue);
	}

	/**
	 * Set field LNSUSR using a String value.
	 */
	public void setLNSUSR(String newvalue) {
		fieldLNSUSR.setString(newvalue);
	}
}