package com.afirme.afirmenet.ibs.messages;

import java.math.BigDecimal;
import java.util.Hashtable;

import com.datapro.sockets.CharacterField;
import com.datapro.sockets.DecimalField;
import com.datapro.sockets.MessageField;
import com.datapro.sockets.MessageRecord;

/**
 * Class generated by AS/400 CRTCLASS command from TRPTARJPF physical file
 * definition.
 * 
 * File level identifier is 1120117112021. Record format level identifier is
 * 3AD43E4E4B65D.
 */

@SuppressWarnings("rawtypes")
public class TRPTARJPFMessage extends MessageRecord {
	final static String fldnames[] = { "TAROPE", "TARUSR", "TARREF",
			"TARXPMTV", "TARFECHA", "TARHORA", "TARCTEREL", "TARNOMBRE",
			"TARAPEPAT", "TARAPEMAT", "TARNOMDEB", "TARCALLE", "TARCOLONIA",
			"TARPOB", "TARESTADO", "TARESTDSC", "TARRFC", "TARCURP",
			"TARTELPART", "TARTELOFI", "TARPOSTAL", "TARCLIENTE", "TARCUENTA",
			"TARTARJA", "TARTARJ", "TARIMAGEN", "TARPROD", "TARSUC",
			"TARDIRSUC", "TARCOLSUC", "TARCIUSUC", "TAREDOSUC", "TARTELSUC",
			"TARREFNOM", "TARTIN", "TARTIF", "TARUSER1", "TARUSER2",
			"TARUSER3", "TARSTS", "TARFRC", "TARREC", "TARFREG", "TARHREG",
			"TARUSUREG", "TARFPROC", "TARFAPLI", "TARHAPLI", "TARUSUAPLI",
			"TARFAPRB", "TARHAPRB", "TARUSUAPRB", "TARFCANC", "TARHCANC",
			"TARUSUCANC", "TARCORREO", "TARCOM", "TARIVC" };
	final static String tnames[] = { "TAROPE", "TARUSR", "TARREF", "TARXPMTV",
			"TARFECHA", "TARHORA", "TARCTEREL", "TARNOMBRE", "TARAPEPAT",
			"TARAPEMAT", "TARNOMDEB", "TARCALLE", "TARCOLONIA", "TARPOB",
			"TARESTADO", "TARESTDSC", "TARRFC", "TARCURP", "TARTELPART",
			"TARTELOFI", "TARPOSTAL", "TARCLIENTE", "TARCUENTA", "TARTARJA",
			"TARTARJ", "TARIMAGEN", "TARPROD", "TARSUC", "TARDIRSUC",
			"TARCOLSUC", "TARCIUSUC", "TAREDOSUC", "TARTELSUC", "TARREFNOM",
			"TARTIN", "TARTIF", "TARUSER1", "TARUSER2", "TARUSER3", "TARSTS",
			"TARFRC", "TARREC", "TARFREG", "TARHREG", "TARUSUREG", "TARFPROC",
			"TARFAPLI", "TARHAPLI", "TARUSUAPLI", "TARFAPRB", "TARHAPRB",
			"TARUSUAPRB", "TARFCANC", "TARHCANC", "TARUSUCANC", "TARCORREO",
			"TARCOM", "TARIVC" };
	final static String fid = "1120117112021";
	final static String rid = "3AD43E4E4B65D";
	final static String fmtname = "TRPTARJPF";
	final int FIELDCOUNT = 58;
	private static Hashtable tlookup = new Hashtable();
	private CharacterField fieldTAROPE = null;
	private CharacterField fieldTARUSR = null;
	private CharacterField fieldTARREF = null;
	private CharacterField fieldTARXPMTV = null;
	private DecimalField fieldTARFECHA = null;
	private DecimalField fieldTARHORA = null;
	private DecimalField fieldTARCTEREL = null;
	private CharacterField fieldTARNOMBRE = null;
	private CharacterField fieldTARAPEPAT = null;
	private CharacterField fieldTARAPEMAT = null;
	private CharacterField fieldTARNOMDEB = null;
	private CharacterField fieldTARCALLE = null;
	private CharacterField fieldTARCOLONIA = null;
	private CharacterField fieldTARPOB = null;
	private CharacterField fieldTARESTADO = null;
	private CharacterField fieldTARESTDSC = null;
	private CharacterField fieldTARRFC = null;
	private CharacterField fieldTARCURP = null;
	private DecimalField fieldTARTELPART = null;
	private DecimalField fieldTARTELOFI = null;
	private CharacterField fieldTARPOSTAL = null;
	private DecimalField fieldTARCLIENTE = null;
	private DecimalField fieldTARCUENTA = null;
	private DecimalField fieldTARTARJA = null;
	private DecimalField fieldTARTARJ = null;
	private DecimalField fieldTARIMAGEN = null;
	private DecimalField fieldTARPROD = null;
	private DecimalField fieldTARSUC = null;
	private CharacterField fieldTARDIRSUC = null;
	private CharacterField fieldTARCOLSUC = null;
	private CharacterField fieldTARCIUSUC = null;
	private CharacterField fieldTAREDOSUC = null;
	private DecimalField fieldTARTELSUC = null;
	private CharacterField fieldTARREFNOM = null;
	private DecimalField fieldTARTIN = null;
	private DecimalField fieldTARTIF = null;
	private CharacterField fieldTARUSER1 = null;
	private CharacterField fieldTARUSER2 = null;
	private CharacterField fieldTARUSER3 = null;
	private CharacterField fieldTARSTS = null;
	private DecimalField fieldTARFRC = null;
	private DecimalField fieldTARREC = null;
	private DecimalField fieldTARFREG = null;
	private DecimalField fieldTARHREG = null;
	private CharacterField fieldTARUSUREG = null;
	private DecimalField fieldTARFPROC = null;
	private DecimalField fieldTARFAPLI = null;
	private DecimalField fieldTARHAPLI = null;
	private CharacterField fieldTARUSUAPLI = null;
	private DecimalField fieldTARFAPRB = null;
	private DecimalField fieldTARHAPRB = null;
	private CharacterField fieldTARUSUAPRB = null;
	private DecimalField fieldTARFCANC = null;
	private DecimalField fieldTARHCANC = null;
	private CharacterField fieldTARUSUCANC = null;
	private CharacterField fieldTARCORREO = null;
	private DecimalField fieldTARCOM = null;
	private DecimalField fieldTARIVC = null;

	/**
	 * Constructor for TRPTARJPFMessage.
	 */
	public TRPTARJPFMessage() {
		createFields();
		initialize();
	}

	/**
	 * Create fields for this message. This method implements the abstract
	 * method in the MessageRecord superclass.
	 */
	@SuppressWarnings("unchecked")
	protected void createFields() {
		recordsize = 904;
		fileid = fid;
		recordid = rid;
		message = new byte[getByteLength()];
		formatname = fmtname;
		fieldnames = fldnames;
		tagnames = tnames;
		fields = new MessageField[FIELDCOUNT];

		fields[0] = fieldTAROPE = new CharacterField(message, HEADERSIZE + 0,
				1, "TAROPE");
		fields[1] = fieldTARUSR = new CharacterField(message, HEADERSIZE + 1,
				10, "TARUSR");
		fields[2] = fieldTARREF = new CharacterField(message, HEADERSIZE + 11,
				12, "TARREF");
		fields[3] = fieldTARXPMTV = new CharacterField(message,
				HEADERSIZE + 23, 2, "TARXPMTV");
		fields[4] = fieldTARFECHA = new DecimalField(message, HEADERSIZE + 25,
				9, 0, "TARFECHA");
		fields[5] = fieldTARHORA = new DecimalField(message, HEADERSIZE + 34,
				7, 0, "TARHORA");
		fields[6] = fieldTARCTEREL = new DecimalField(message, HEADERSIZE + 41,
				10, 0, "TARCTEREL");
		fields[7] = fieldTARNOMBRE = new CharacterField(message,
				HEADERSIZE + 51, 30, "TARNOMBRE");
		fields[8] = fieldTARAPEPAT = new CharacterField(message,
				HEADERSIZE + 81, 30, "TARAPEPAT");
		fields[9] = fieldTARAPEMAT = new CharacterField(message,
				HEADERSIZE + 111, 30, "TARAPEMAT");
		fields[10] = fieldTARNOMDEB = new CharacterField(message,
				HEADERSIZE + 141, 40, "TARNOMDEB");
		fields[11] = fieldTARCALLE = new CharacterField(message,
				HEADERSIZE + 181, 35, "TARCALLE");
		fields[12] = fieldTARCOLONIA = new CharacterField(message,
				HEADERSIZE + 216, 35, "TARCOLONIA");
		fields[13] = fieldTARPOB = new CharacterField(message,
				HEADERSIZE + 251, 30, "TARPOB");
		fields[14] = fieldTARESTADO = new CharacterField(message,
				HEADERSIZE + 281, 4, "TARESTADO");
		fields[15] = fieldTARESTDSC = new CharacterField(message,
				HEADERSIZE + 285, 30, "TARESTDSC");
		fields[16] = fieldTARRFC = new CharacterField(message,
				HEADERSIZE + 315, 15, "TARRFC");
		fields[17] = fieldTARCURP = new CharacterField(message,
				HEADERSIZE + 330, 18, "TARCURP");
		fields[18] = fieldTARTELPART = new DecimalField(message,
				HEADERSIZE + 348, 12, 0, "TARTELPART");
		fields[19] = fieldTARTELOFI = new DecimalField(message,
				HEADERSIZE + 360, 12, 0, "TARTELOFI");
		fields[20] = fieldTARPOSTAL = new CharacterField(message,
				HEADERSIZE + 372, 15, "TARPOSTAL");
		fields[21] = fieldTARCLIENTE = new DecimalField(message,
				HEADERSIZE + 387, 10, 0, "TARCLIENTE");
		fields[22] = fieldTARCUENTA = new DecimalField(message,
				HEADERSIZE + 397, 13, 0, "TARCUENTA");
		fields[23] = fieldTARTARJA = new DecimalField(message,
				HEADERSIZE + 410, 17, 0, "TARTARJA");
		fields[24] = fieldTARTARJ = new DecimalField(message, HEADERSIZE + 427,
				17, 0, "TARTARJ");
		fields[25] = fieldTARIMAGEN = new DecimalField(message,
				HEADERSIZE + 444, 3, 0, "TARIMAGEN");
		fields[26] = fieldTARPROD = new DecimalField(message, HEADERSIZE + 447,
				3, 0, "TARPROD");
		fields[27] = fieldTARSUC = new DecimalField(message, HEADERSIZE + 450,
				4, 0, "TARSUC");
		fields[28] = fieldTARDIRSUC = new CharacterField(message,
				HEADERSIZE + 454, 50, "TARDIRSUC");
		fields[29] = fieldTARCOLSUC = new CharacterField(message,
				HEADERSIZE + 504, 50, "TARCOLSUC");
		fields[30] = fieldTARCIUSUC = new CharacterField(message,
				HEADERSIZE + 554, 40, "TARCIUSUC");
		fields[31] = fieldTAREDOSUC = new CharacterField(message,
				HEADERSIZE + 594, 30, "TAREDOSUC");
		fields[32] = fieldTARTELSUC = new DecimalField(message,
				HEADERSIZE + 624, 12, 0, "TARTELSUC");
		fields[33] = fieldTARREFNOM = new CharacterField(message,
				HEADERSIZE + 636, 9, "TARREFNOM");
		fields[34] = fieldTARTIN = new DecimalField(message, HEADERSIZE + 645,
				7, 0, "TARTIN");
		fields[35] = fieldTARTIF = new DecimalField(message, HEADERSIZE + 652,
				7, 0, "TARTIF");
		fields[36] = fieldTARUSER1 = new CharacterField(message,
				HEADERSIZE + 659, 10, "TARUSER1");
		fields[37] = fieldTARUSER2 = new CharacterField(message,
				HEADERSIZE + 669, 10, "TARUSER2");
		fields[38] = fieldTARUSER3 = new CharacterField(message,
				HEADERSIZE + 679, 10, "TARUSER3");
		fields[39] = fieldTARSTS = new CharacterField(message,
				HEADERSIZE + 689, 1, "TARSTS");
		fields[40] = fieldTARFRC = new DecimalField(message, HEADERSIZE + 690,
				8, 0, "TARFRC");
		fields[41] = fieldTARREC = new DecimalField(message, HEADERSIZE + 698,
				8, 0, "TARREC");
		fields[42] = fieldTARFREG = new DecimalField(message, HEADERSIZE + 706,
				9, 0, "TARFREG");
		fields[43] = fieldTARHREG = new DecimalField(message, HEADERSIZE + 715,
				7, 0, "TARHREG");
		fields[44] = fieldTARUSUREG = new CharacterField(message,
				HEADERSIZE + 722, 10, "TARUSUREG");
		fields[45] = fieldTARFPROC = new DecimalField(message,
				HEADERSIZE + 732, 9, 0, "TARFPROC");
		fields[46] = fieldTARFAPLI = new DecimalField(message,
				HEADERSIZE + 741, 9, 0, "TARFAPLI");
		fields[47] = fieldTARHAPLI = new DecimalField(message,
				HEADERSIZE + 750, 7, 0, "TARHAPLI");
		fields[48] = fieldTARUSUAPLI = new CharacterField(message,
				HEADERSIZE + 757, 10, "TARUSUAPLI");
		fields[49] = fieldTARFAPRB = new DecimalField(message,
				HEADERSIZE + 767, 9, 0, "TARFAPRB");
		fields[50] = fieldTARHAPRB = new DecimalField(message,
				HEADERSIZE + 776, 7, 0, "TARHAPRB");
		fields[51] = fieldTARUSUAPRB = new CharacterField(message,
				HEADERSIZE + 783, 10, "TARUSUAPRB");
		fields[52] = fieldTARFCANC = new DecimalField(message,
				HEADERSIZE + 793, 9, 0, "TARFCANC");
		fields[53] = fieldTARHCANC = new DecimalField(message,
				HEADERSIZE + 802, 7, 0, "TARHCANC");
		fields[54] = fieldTARUSUCANC = new CharacterField(message,
				HEADERSIZE + 809, 10, "TARUSUCANC");
		fields[55] = fieldTARCORREO = new CharacterField(message,
				HEADERSIZE + 819, 55, "TARCORREO");
		fields[56] = fieldTARCOM = new DecimalField(message, HEADERSIZE + 874,
				15, 2, "TARCOM");
		fields[57] = fieldTARIVC = new DecimalField(message, HEADERSIZE + 889,
				15, 2, "TARIVC");

		synchronized (tlookup) {
			if (tlookup.isEmpty()) {
				for (int i = 0; i < tnames.length; i++)
					tlookup.put(tnames[i], new Integer(i));
			}
		}

		taglookup = tlookup;
	}

	/**
	 * Set field TAROPE using a String value.
	 */
	public void setTAROPE(String newvalue) {
		fieldTAROPE.setString(newvalue);
	}

	/**
	 * Get value of field TAROPE as a String.
	 */
	public String getTAROPE() {
		return fieldTAROPE.getString();
	}

	/**
	 * Set field TARUSR using a String value.
	 */
	public void setTARUSR(String newvalue) {
		fieldTARUSR.setString(newvalue);
	}

	/**
	 * Get value of field TARUSR as a String.
	 */
	public String getTARUSR() {
		return fieldTARUSR.getString();
	}

	/**
	 * Set field TARREF using a String value.
	 */
	public void setTARREF(String newvalue) {
		fieldTARREF.setString(newvalue);
	}

	/**
	 * Get value of field TARREF as a String.
	 */
	public String getTARREF() {
		return fieldTARREF.getString();
	}

	/**
	 * Set field TARXPMTV using a String value.
	 */
	public void setTARXPMTV(String newvalue) {
		fieldTARXPMTV.setString(newvalue);
	}

	/**
	 * Get value of field TARXPMTV as a String.
	 */
	public String getTARXPMTV() {
		return fieldTARXPMTV.getString();
	}

	/**
	 * Set field TARFECHA using a String value.
	 */
	public void setTARFECHA(String newvalue) {
		fieldTARFECHA.setString(newvalue);
	}

	/**
	 * Get value of field TARFECHA as a String.
	 */
	public String getTARFECHA() {
		return fieldTARFECHA.getString();
	}

	/**
	 * Set numeric field TARFECHA using a BigDecimal value.
	 */
	public void setTARFECHA(BigDecimal newvalue) {
		fieldTARFECHA.setBigDecimal(newvalue);
	}

	/**
	 * Return value of numeric field TARFECHA as a BigDecimal.
	 */
	public BigDecimal getBigDecimalTARFECHA() {
		return fieldTARFECHA.getBigDecimal();
	}

	/**
	 * Set field TARHORA using a String value.
	 */
	public void setTARHORA(String newvalue) {
		fieldTARHORA.setString(newvalue);
	}

	/**
	 * Get value of field TARHORA as a String.
	 */
	public String getTARHORA() {
		return fieldTARHORA.getString();
	}

	/**
	 * Set numeric field TARHORA using a BigDecimal value.
	 */
	public void setTARHORA(BigDecimal newvalue) {
		fieldTARHORA.setBigDecimal(newvalue);
	}

	/**
	 * Return value of numeric field TARHORA as a BigDecimal.
	 */
	public BigDecimal getBigDecimalTARHORA() {
		return fieldTARHORA.getBigDecimal();
	}

	/**
	 * Set field TARCTEREL using a String value.
	 */
	public void setTARCTEREL(String newvalue) {
		fieldTARCTEREL.setString(newvalue);
	}

	/**
	 * Get value of field TARCTEREL as a String.
	 */
	public String getTARCTEREL() {
		return fieldTARCTEREL.getString();
	}

	/**
	 * Set numeric field TARCTEREL using a BigDecimal value.
	 */
	public void setTARCTEREL(BigDecimal newvalue) {
		fieldTARCTEREL.setBigDecimal(newvalue);
	}

	/**
	 * Return value of numeric field TARCTEREL as a BigDecimal.
	 */
	public BigDecimal getBigDecimalTARCTEREL() {
		return fieldTARCTEREL.getBigDecimal();
	}

	/**
	 * Set field TARNOMBRE using a String value.
	 */
	public void setTARNOMBRE(String newvalue) {
		fieldTARNOMBRE.setString(newvalue);
	}

	/**
	 * Get value of field TARNOMBRE as a String.
	 */
	public String getTARNOMBRE() {
		return fieldTARNOMBRE.getString();
	}

	/**
	 * Set field TARAPEPAT using a String value.
	 */
	public void setTARAPEPAT(String newvalue) {
		fieldTARAPEPAT.setString(newvalue);
	}

	/**
	 * Get value of field TARAPEPAT as a String.
	 */
	public String getTARAPEPAT() {
		return fieldTARAPEPAT.getString();
	}

	/**
	 * Set field TARAPEMAT using a String value.
	 */
	public void setTARAPEMAT(String newvalue) {
		fieldTARAPEMAT.setString(newvalue);
	}

	/**
	 * Get value of field TARAPEMAT as a String.
	 */
	public String getTARAPEMAT() {
		return fieldTARAPEMAT.getString();
	}

	/**
	 * Set field TARNOMDEB using a String value.
	 */
	public void setTARNOMDEB(String newvalue) {
		fieldTARNOMDEB.setString(newvalue);
	}

	/**
	 * Get value of field TARNOMDEB as a String.
	 */
	public String getTARNOMDEB() {
		return fieldTARNOMDEB.getString();
	}

	/**
	 * Set field TARCALLE using a String value.
	 */
	public void setTARCALLE(String newvalue) {
		fieldTARCALLE.setString(newvalue);
	}

	/**
	 * Get value of field TARCALLE as a String.
	 */
	public String getTARCALLE() {
		return fieldTARCALLE.getString();
	}

	/**
	 * Set field TARCOLONIA using a String value.
	 */
	public void setTARCOLONIA(String newvalue) {
		fieldTARCOLONIA.setString(newvalue);
	}

	/**
	 * Get value of field TARCOLONIA as a String.
	 */
	public String getTARCOLONIA() {
		return fieldTARCOLONIA.getString();
	}

	/**
	 * Set field TARPOB using a String value.
	 */
	public void setTARPOB(String newvalue) {
		fieldTARPOB.setString(newvalue);
	}

	/**
	 * Get value of field TARPOB as a String.
	 */
	public String getTARPOB() {
		return fieldTARPOB.getString();
	}

	/**
	 * Set field TARESTADO using a String value.
	 */
	public void setTARESTADO(String newvalue) {
		fieldTARESTADO.setString(newvalue);
	}

	/**
	 * Get value of field TARESTADO as a String.
	 */
	public String getTARESTADO() {
		return fieldTARESTADO.getString();
	}

	/**
	 * Set field TARESTDSC using a String value.
	 */
	public void setTARESTDSC(String newvalue) {
		fieldTARESTDSC.setString(newvalue);
	}

	/**
	 * Get value of field TARESTDSC as a String.
	 */
	public String getTARESTDSC() {
		return fieldTARESTDSC.getString();
	}

	/**
	 * Set field TARRFC using a String value.
	 */
	public void setTARRFC(String newvalue) {
		fieldTARRFC.setString(newvalue);
	}

	/**
	 * Get value of field TARRFC as a String.
	 */
	public String getTARRFC() {
		return fieldTARRFC.getString();
	}

	/**
	 * Set field TARCURP using a String value.
	 */
	public void setTARCURP(String newvalue) {
		fieldTARCURP.setString(newvalue);
	}

	/**
	 * Get value of field TARCURP as a String.
	 */
	public String getTARCURP() {
		return fieldTARCURP.getString();
	}

	/**
	 * Set field TARTELPART using a String value.
	 */
	public void setTARTELPART(String newvalue) {
		fieldTARTELPART.setString(newvalue);
	}

	/**
	 * Get value of field TARTELPART as a String.
	 */
	public String getTARTELPART() {
		return fieldTARTELPART.getString();
	}

	/**
	 * Set numeric field TARTELPART using a BigDecimal value.
	 */
	public void setTARTELPART(BigDecimal newvalue) {
		fieldTARTELPART.setBigDecimal(newvalue);
	}

	/**
	 * Return value of numeric field TARTELPART as a BigDecimal.
	 */
	public BigDecimal getBigDecimalTARTELPART() {
		return fieldTARTELPART.getBigDecimal();
	}

	/**
	 * Set field TARTELOFI using a String value.
	 */
	public void setTARTELOFI(String newvalue) {
		fieldTARTELOFI.setString(newvalue);
	}

	/**
	 * Get value of field TARTELOFI as a String.
	 */
	public String getTARTELOFI() {
		return fieldTARTELOFI.getString();
	}

	/**
	 * Set numeric field TARTELOFI using a BigDecimal value.
	 */
	public void setTARTELOFI(BigDecimal newvalue) {
		fieldTARTELOFI.setBigDecimal(newvalue);
	}

	/**
	 * Return value of numeric field TARTELOFI as a BigDecimal.
	 */
	public BigDecimal getBigDecimalTARTELOFI() {
		return fieldTARTELOFI.getBigDecimal();
	}

	/**
	 * Set field TARPOSTAL using a String value.
	 */
	public void setTARPOSTAL(String newvalue) {
		fieldTARPOSTAL.setString(newvalue);
	}

	/**
	 * Get value of field TARPOSTAL as a String.
	 */
	public String getTARPOSTAL() {
		return fieldTARPOSTAL.getString();
	}

	/**
	 * Set field TARCLIENTE using a String value.
	 */
	public void setTARCLIENTE(String newvalue) {
		fieldTARCLIENTE.setString(newvalue);
	}

	/**
	 * Get value of field TARCLIENTE as a String.
	 */
	public String getTARCLIENTE() {
		return fieldTARCLIENTE.getString();
	}

	/**
	 * Set numeric field TARCLIENTE using a BigDecimal value.
	 */
	public void setTARCLIENTE(BigDecimal newvalue) {
		fieldTARCLIENTE.setBigDecimal(newvalue);
	}

	/**
	 * Return value of numeric field TARCLIENTE as a BigDecimal.
	 */
	public BigDecimal getBigDecimalTARCLIENTE() {
		return fieldTARCLIENTE.getBigDecimal();
	}

	/**
	 * Set field TARCUENTA using a String value.
	 */
	public void setTARCUENTA(String newvalue) {
		fieldTARCUENTA.setString(newvalue);
	}

	/**
	 * Get value of field TARCUENTA as a String.
	 */
	public String getTARCUENTA() {
		return fieldTARCUENTA.getString();
	}

	/**
	 * Set numeric field TARCUENTA using a BigDecimal value.
	 */
	public void setTARCUENTA(BigDecimal newvalue) {
		fieldTARCUENTA.setBigDecimal(newvalue);
	}

	/**
	 * Return value of numeric field TARCUENTA as a BigDecimal.
	 */
	public BigDecimal getBigDecimalTARCUENTA() {
		return fieldTARCUENTA.getBigDecimal();
	}

	/**
	 * Set field TARTARJA using a String value.
	 */
	public void setTARTARJA(String newvalue) {
		fieldTARTARJA.setString(newvalue);
	}

	/**
	 * Get value of field TARTARJA as a String.
	 */
	public String getTARTARJA() {
		return fieldTARTARJA.getString();
	}

	/**
	 * Set numeric field TARTARJA using a BigDecimal value.
	 */
	public void setTARTARJA(BigDecimal newvalue) {
		fieldTARTARJA.setBigDecimal(newvalue);
	}

	/**
	 * Return value of numeric field TARTARJA as a BigDecimal.
	 */
	public BigDecimal getBigDecimalTARTARJA() {
		return fieldTARTARJA.getBigDecimal();
	}

	/**
	 * Set field TARTARJ using a String value.
	 */
	public void setTARTARJ(String newvalue) {
		fieldTARTARJ.setString(newvalue);
	}

	/**
	 * Get value of field TARTARJ as a String.
	 */
	public String getTARTARJ() {
		return fieldTARTARJ.getString();
	}

	/**
	 * Set numeric field TARTARJ using a BigDecimal value.
	 */
	public void setTARTARJ(BigDecimal newvalue) {
		fieldTARTARJ.setBigDecimal(newvalue);
	}

	/**
	 * Return value of numeric field TARTARJ as a BigDecimal.
	 */
	public BigDecimal getBigDecimalTARTARJ() {
		return fieldTARTARJ.getBigDecimal();
	}

	/**
	 * Set field TARIMAGEN using a String value.
	 */
	public void setTARIMAGEN(String newvalue) {
		fieldTARIMAGEN.setString(newvalue);
	}

	/**
	 * Get value of field TARIMAGEN as a String.
	 */
	public String getTARIMAGEN() {
		return fieldTARIMAGEN.getString();
	}

	/**
	 * Set numeric field TARIMAGEN using a BigDecimal value.
	 */
	public void setTARIMAGEN(BigDecimal newvalue) {
		fieldTARIMAGEN.setBigDecimal(newvalue);
	}

	/**
	 * Return value of numeric field TARIMAGEN as a BigDecimal.
	 */
	public BigDecimal getBigDecimalTARIMAGEN() {
		return fieldTARIMAGEN.getBigDecimal();
	}

	/**
	 * Set field TARPROD using a String value.
	 */
	public void setTARPROD(String newvalue) {
		fieldTARPROD.setString(newvalue);
	}

	/**
	 * Get value of field TARPROD as a String.
	 */
	public String getTARPROD() {
		return fieldTARPROD.getString();
	}

	/**
	 * Set numeric field TARPROD using a BigDecimal value.
	 */
	public void setTARPROD(BigDecimal newvalue) {
		fieldTARPROD.setBigDecimal(newvalue);
	}

	/**
	 * Return value of numeric field TARPROD as a BigDecimal.
	 */
	public BigDecimal getBigDecimalTARPROD() {
		return fieldTARPROD.getBigDecimal();
	}

	/**
	 * Set field TARSUC using a String value.
	 */
	public void setTARSUC(String newvalue) {
		fieldTARSUC.setString(newvalue);
	}

	/**
	 * Get value of field TARSUC as a String.
	 */
	public String getTARSUC() {
		return fieldTARSUC.getString();
	}

	/**
	 * Set numeric field TARSUC using a BigDecimal value.
	 */
	public void setTARSUC(BigDecimal newvalue) {
		fieldTARSUC.setBigDecimal(newvalue);
	}

	/**
	 * Return value of numeric field TARSUC as a BigDecimal.
	 */
	public BigDecimal getBigDecimalTARSUC() {
		return fieldTARSUC.getBigDecimal();
	}

	/**
	 * Set field TARDIRSUC using a String value.
	 */
	public void setTARDIRSUC(String newvalue) {
		fieldTARDIRSUC.setString(newvalue);
	}

	/**
	 * Get value of field TARDIRSUC as a String.
	 */
	public String getTARDIRSUC() {
		return fieldTARDIRSUC.getString();
	}

	/**
	 * Set field TARCOLSUC using a String value.
	 */
	public void setTARCOLSUC(String newvalue) {
		fieldTARCOLSUC.setString(newvalue);
	}

	/**
	 * Get value of field TARCOLSUC as a String.
	 */
	public String getTARCOLSUC() {
		return fieldTARCOLSUC.getString();
	}

	/**
	 * Set field TARCIUSUC using a String value.
	 */
	public void setTARCIUSUC(String newvalue) {
		fieldTARCIUSUC.setString(newvalue);
	}

	/**
	 * Get value of field TARCIUSUC as a String.
	 */
	public String getTARCIUSUC() {
		return fieldTARCIUSUC.getString();
	}

	/**
	 * Set field TAREDOSUC using a String value.
	 */
	public void setTAREDOSUC(String newvalue) {
		fieldTAREDOSUC.setString(newvalue);
	}

	/**
	 * Get value of field TAREDOSUC as a String.
	 */
	public String getTAREDOSUC() {
		return fieldTAREDOSUC.getString();
	}

	/**
	 * Set field TARTELSUC using a String value.
	 */
	public void setTARTELSUC(String newvalue) {
		fieldTARTELSUC.setString(newvalue);
	}

	/**
	 * Get value of field TARTELSUC as a String.
	 */
	public String getTARTELSUC() {
		return fieldTARTELSUC.getString();
	}

	/**
	 * Set numeric field TARTELSUC using a BigDecimal value.
	 */
	public void setTARTELSUC(BigDecimal newvalue) {
		fieldTARTELSUC.setBigDecimal(newvalue);
	}

	/**
	 * Return value of numeric field TARTELSUC as a BigDecimal.
	 */
	public BigDecimal getBigDecimalTARTELSUC() {
		return fieldTARTELSUC.getBigDecimal();
	}

	/**
	 * Set field TARREFNOM using a String value.
	 */
	public void setTARREFNOM(String newvalue) {
		fieldTARREFNOM.setString(newvalue);
	}

	/**
	 * Get value of field TARREFNOM as a String.
	 */
	public String getTARREFNOM() {
		return fieldTARREFNOM.getString();
	}

	/**
	 * Set field TARTIN using a String value.
	 */
	public void setTARTIN(String newvalue) {
		fieldTARTIN.setString(newvalue);
	}

	/**
	 * Get value of field TARTIN as a String.
	 */
	public String getTARTIN() {
		return fieldTARTIN.getString();
	}

	/**
	 * Set numeric field TARTIN using a BigDecimal value.
	 */
	public void setTARTIN(BigDecimal newvalue) {
		fieldTARTIN.setBigDecimal(newvalue);
	}

	/**
	 * Return value of numeric field TARTIN as a BigDecimal.
	 */
	public BigDecimal getBigDecimalTARTIN() {
		return fieldTARTIN.getBigDecimal();
	}

	/**
	 * Set field TARTIF using a String value.
	 */
	public void setTARTIF(String newvalue) {
		fieldTARTIF.setString(newvalue);
	}

	/**
	 * Get value of field TARTIF as a String.
	 */
	public String getTARTIF() {
		return fieldTARTIF.getString();
	}

	/**
	 * Set numeric field TARTIF using a BigDecimal value.
	 */
	public void setTARTIF(BigDecimal newvalue) {
		fieldTARTIF.setBigDecimal(newvalue);
	}

	/**
	 * Return value of numeric field TARTIF as a BigDecimal.
	 */
	public BigDecimal getBigDecimalTARTIF() {
		return fieldTARTIF.getBigDecimal();
	}

	/**
	 * Set field TARUSER1 using a String value.
	 */
	public void setTARUSER1(String newvalue) {
		fieldTARUSER1.setString(newvalue);
	}

	/**
	 * Get value of field TARUSER1 as a String.
	 */
	public String getTARUSER1() {
		return fieldTARUSER1.getString();
	}

	/**
	 * Set field TARUSER2 using a String value.
	 */
	public void setTARUSER2(String newvalue) {
		fieldTARUSER2.setString(newvalue);
	}

	/**
	 * Get value of field TARUSER2 as a String.
	 */
	public String getTARUSER2() {
		return fieldTARUSER2.getString();
	}

	/**
	 * Set field TARUSER3 using a String value.
	 */
	public void setTARUSER3(String newvalue) {
		fieldTARUSER3.setString(newvalue);
	}

	/**
	 * Get value of field TARUSER3 as a String.
	 */
	public String getTARUSER3() {
		return fieldTARUSER3.getString();
	}

	/**
	 * Set field TARSTS using a String value.
	 */
	public void setTARSTS(String newvalue) {
		fieldTARSTS.setString(newvalue);
	}

	/**
	 * Get value of field TARSTS as a String.
	 */
	public String getTARSTS() {
		return fieldTARSTS.getString();
	}

	/**
	 * Set field TARFRC using a String value.
	 */
	public void setTARFRC(String newvalue) {
		fieldTARFRC.setString(newvalue);
	}

	/**
	 * Get value of field TARFRC as a String.
	 */
	public String getTARFRC() {
		return fieldTARFRC.getString();
	}

	/**
	 * Set numeric field TARFRC using a BigDecimal value.
	 */
	public void setTARFRC(BigDecimal newvalue) {
		fieldTARFRC.setBigDecimal(newvalue);
	}

	/**
	 * Return value of numeric field TARFRC as a BigDecimal.
	 */
	public BigDecimal getBigDecimalTARFRC() {
		return fieldTARFRC.getBigDecimal();
	}

	/**
	 * Set field TARREC using a String value.
	 */
	public void setTARREC(String newvalue) {
		fieldTARREC.setString(newvalue);
	}

	/**
	 * Get value of field TARREC as a String.
	 */
	public String getTARREC() {
		return fieldTARREC.getString();
	}

	/**
	 * Set numeric field TARREC using a BigDecimal value.
	 */
	public void setTARREC(BigDecimal newvalue) {
		fieldTARREC.setBigDecimal(newvalue);
	}

	/**
	 * Return value of numeric field TARREC as a BigDecimal.
	 */
	public BigDecimal getBigDecimalTARREC() {
		return fieldTARREC.getBigDecimal();
	}

	/**
	 * Set field TARFREG using a String value.
	 */
	public void setTARFREG(String newvalue) {
		fieldTARFREG.setString(newvalue);
	}

	/**
	 * Get value of field TARFREG as a String.
	 */
	public String getTARFREG() {
		return fieldTARFREG.getString();
	}

	/**
	 * Set numeric field TARFREG using a BigDecimal value.
	 */
	public void setTARFREG(BigDecimal newvalue) {
		fieldTARFREG.setBigDecimal(newvalue);
	}

	/**
	 * Return value of numeric field TARFREG as a BigDecimal.
	 */
	public BigDecimal getBigDecimalTARFREG() {
		return fieldTARFREG.getBigDecimal();
	}

	/**
	 * Set field TARHREG using a String value.
	 */
	public void setTARHREG(String newvalue) {
		fieldTARHREG.setString(newvalue);
	}

	/**
	 * Get value of field TARHREG as a String.
	 */
	public String getTARHREG() {
		return fieldTARHREG.getString();
	}

	/**
	 * Set numeric field TARHREG using a BigDecimal value.
	 */
	public void setTARHREG(BigDecimal newvalue) {
		fieldTARHREG.setBigDecimal(newvalue);
	}

	/**
	 * Return value of numeric field TARHREG as a BigDecimal.
	 */
	public BigDecimal getBigDecimalTARHREG() {
		return fieldTARHREG.getBigDecimal();
	}

	/**
	 * Set field TARUSUREG using a String value.
	 */
	public void setTARUSUREG(String newvalue) {
		fieldTARUSUREG.setString(newvalue);
	}

	/**
	 * Get value of field TARUSUREG as a String.
	 */
	public String getTARUSUREG() {
		return fieldTARUSUREG.getString();
	}

	/**
	 * Set field TARFPROC using a String value.
	 */
	public void setTARFPROC(String newvalue) {
		fieldTARFPROC.setString(newvalue);
	}

	/**
	 * Get value of field TARFPROC as a String.
	 */
	public String getTARFPROC() {
		return fieldTARFPROC.getString();
	}

	/**
	 * Set numeric field TARFPROC using a BigDecimal value.
	 */
	public void setTARFPROC(BigDecimal newvalue) {
		fieldTARFPROC.setBigDecimal(newvalue);
	}

	/**
	 * Return value of numeric field TARFPROC as a BigDecimal.
	 */
	public BigDecimal getBigDecimalTARFPROC() {
		return fieldTARFPROC.getBigDecimal();
	}

	/**
	 * Set field TARFAPLI using a String value.
	 */
	public void setTARFAPLI(String newvalue) {
		fieldTARFAPLI.setString(newvalue);
	}

	/**
	 * Get value of field TARFAPLI as a String.
	 */
	public String getTARFAPLI() {
		return fieldTARFAPLI.getString();
	}

	/**
	 * Set numeric field TARFAPLI using a BigDecimal value.
	 */
	public void setTARFAPLI(BigDecimal newvalue) {
		fieldTARFAPLI.setBigDecimal(newvalue);
	}

	/**
	 * Return value of numeric field TARFAPLI as a BigDecimal.
	 */
	public BigDecimal getBigDecimalTARFAPLI() {
		return fieldTARFAPLI.getBigDecimal();
	}

	/**
	 * Set field TARHAPLI using a String value.
	 */
	public void setTARHAPLI(String newvalue) {
		fieldTARHAPLI.setString(newvalue);
	}

	/**
	 * Get value of field TARHAPLI as a String.
	 */
	public String getTARHAPLI() {
		return fieldTARHAPLI.getString();
	}

	/**
	 * Set numeric field TARHAPLI using a BigDecimal value.
	 */
	public void setTARHAPLI(BigDecimal newvalue) {
		fieldTARHAPLI.setBigDecimal(newvalue);
	}

	/**
	 * Return value of numeric field TARHAPLI as a BigDecimal.
	 */
	public BigDecimal getBigDecimalTARHAPLI() {
		return fieldTARHAPLI.getBigDecimal();
	}

	/**
	 * Set field TARUSUAPLI using a String value.
	 */
	public void setTARUSUAPLI(String newvalue) {
		fieldTARUSUAPLI.setString(newvalue);
	}

	/**
	 * Get value of field TARUSUAPLI as a String.
	 */
	public String getTARUSUAPLI() {
		return fieldTARUSUAPLI.getString();
	}

	/**
	 * Set field TARFAPRB using a String value.
	 */
	public void setTARFAPRB(String newvalue) {
		fieldTARFAPRB.setString(newvalue);
	}

	/**
	 * Get value of field TARFAPRB as a String.
	 */
	public String getTARFAPRB() {
		return fieldTARFAPRB.getString();
	}

	/**
	 * Set numeric field TARFAPRB using a BigDecimal value.
	 */
	public void setTARFAPRB(BigDecimal newvalue) {
		fieldTARFAPRB.setBigDecimal(newvalue);
	}

	/**
	 * Return value of numeric field TARFAPRB as a BigDecimal.
	 */
	public BigDecimal getBigDecimalTARFAPRB() {
		return fieldTARFAPRB.getBigDecimal();
	}

	/**
	 * Set field TARHAPRB using a String value.
	 */
	public void setTARHAPRB(String newvalue) {
		fieldTARHAPRB.setString(newvalue);
	}

	/**
	 * Get value of field TARHAPRB as a String.
	 */
	public String getTARHAPRB() {
		return fieldTARHAPRB.getString();
	}

	/**
	 * Set numeric field TARHAPRB using a BigDecimal value.
	 */
	public void setTARHAPRB(BigDecimal newvalue) {
		fieldTARHAPRB.setBigDecimal(newvalue);
	}

	/**
	 * Return value of numeric field TARHAPRB as a BigDecimal.
	 */
	public BigDecimal getBigDecimalTARHAPRB() {
		return fieldTARHAPRB.getBigDecimal();
	}

	/**
	 * Set field TARUSUAPRB using a String value.
	 */
	public void setTARUSUAPRB(String newvalue) {
		fieldTARUSUAPRB.setString(newvalue);
	}

	/**
	 * Get value of field TARUSUAPRB as a String.
	 */
	public String getTARUSUAPRB() {
		return fieldTARUSUAPRB.getString();
	}

	/**
	 * Set field TARFCANC using a String value.
	 */
	public void setTARFCANC(String newvalue) {
		fieldTARFCANC.setString(newvalue);
	}

	/**
	 * Get value of field TARFCANC as a String.
	 */
	public String getTARFCANC() {
		return fieldTARFCANC.getString();
	}

	/**
	 * Set numeric field TARFCANC using a BigDecimal value.
	 */
	public void setTARFCANC(BigDecimal newvalue) {
		fieldTARFCANC.setBigDecimal(newvalue);
	}

	/**
	 * Return value of numeric field TARFCANC as a BigDecimal.
	 */
	public BigDecimal getBigDecimalTARFCANC() {
		return fieldTARFCANC.getBigDecimal();
	}

	/**
	 * Set field TARHCANC using a String value.
	 */
	public void setTARHCANC(String newvalue) {
		fieldTARHCANC.setString(newvalue);
	}

	/**
	 * Get value of field TARHCANC as a String.
	 */
	public String getTARHCANC() {
		return fieldTARHCANC.getString();
	}

	/**
	 * Set numeric field TARHCANC using a BigDecimal value.
	 */
	public void setTARHCANC(BigDecimal newvalue) {
		fieldTARHCANC.setBigDecimal(newvalue);
	}

	/**
	 * Return value of numeric field TARHCANC as a BigDecimal.
	 */
	public BigDecimal getBigDecimalTARHCANC() {
		return fieldTARHCANC.getBigDecimal();
	}

	/**
	 * Set field TARUSUCANC using a String value.
	 */
	public void setTARUSUCANC(String newvalue) {
		fieldTARUSUCANC.setString(newvalue);
	}

	/**
	 * Get value of field TARUSUCANC as a String.
	 */
	public String getTARUSUCANC() {
		return fieldTARUSUCANC.getString();
	}

	/**
	 * Set field TARCORREO using a String value.
	 */
	public void setTARCORREO(String newvalue) {
		fieldTARCORREO.setString(newvalue);
	}

	/**
	 * Get value of field TARCORREO as a String.
	 */
	public String getTARCORREO() {
		return fieldTARCORREO.getString();
	}

	/**
	 * Set field TARCOM using a String value.
	 */
	public void setTARCOM(String newvalue) {
		fieldTARCOM.setString(newvalue);
	}

	/**
	 * Get value of field TARCOM as a String.
	 */
	public String getTARCOM() {
		return fieldTARCOM.getString();
	}

	/**
	 * Set numeric field TARCOM using a BigDecimal value.
	 */
	public void setTARCOM(BigDecimal newvalue) {
		fieldTARCOM.setBigDecimal(newvalue);
	}

	/**
	 * Return value of numeric field TARCOM as a BigDecimal.
	 */
	public BigDecimal getBigDecimalTARCOM() {
		return fieldTARCOM.getBigDecimal();
	}

	/**
	 * Set field TARIVC using a String value.
	 */
	public void setTARIVC(String newvalue) {
		fieldTARIVC.setString(newvalue);
	}

	/**
	 * Get value of field TARIVC as a String.
	 */
	public String getTARIVC() {
		return fieldTARIVC.getString();
	}

	/**
	 * Set numeric field TARIVC using a BigDecimal value.
	 */
	public void setTARIVC(BigDecimal newvalue) {
		fieldTARIVC.setBigDecimal(newvalue);
	}

	/**
	 * Return value of numeric field TARIVC as a BigDecimal.
	 */
	public BigDecimal getBigDecimalTARIVC() {
		return fieldTARIVC.getBigDecimal();
	}

}
