package com.afirme.afirmenet.enums;

public enum HorarioServicio {
	TRASPASO_PROPIAS("02"), TRASPASO_TERCEROS("03"), TRANSFERENCIAS_INTERNACIONALES_DOLARES(
			"04"), TRANSFERENCIA_SPEI("05"), DOMICILIACION("06"), NÓMINA("07"), PAGO_INTERBANCARIO(
			"09"), PAGO_IMPUESTOS("12"), APERTURA_CARTAS_CREDITO("17"), ENMIENDA_CARTAS_CREDITO(
			"18"), PAGO_SERVICIOS("28"), TARJETAS_DEBITO("31"), INVERSION_DIARIA(
			"36"), DOMINGO_ELECTRONICO("37"), CHEQUES_EXTRAVIADOS("40"), CREDITO_REVOLVENTES(
			"43"), COMPRA_VALORES("44"), VENTA_VALORES("45"), AHORRO_VOLUNTARIO_AFORE(
			"46"), PAGO_REFERENCIADO("47"), PAGO_PEMEX("48"), PAGO_TESORERIA_GOB_DF(
			"49"), TRASPASO_TERCEROS_MASIVO("50"), TRANSFERENCIAS_INT_MULTI(
			"51"), PROGRAMACION_PAGO_AUT_TDC("52"), PAGO_IDE("53"), DEPOSITO_DIGITAL(
			"54"), PAGO_IMSS_SIPARE("56"), RECARGA_TA_TELCEL("57"), PAGO_NOMINA_IMSS(
			"58"), DISPOSICION_CREDITO_EDUCATIVO("59"), EMISION_EDO_CUENTA("60"), TERMINAL_PUNTO_VENTA(
			"61"), PAGO_SUA_ELECTRONICO("62"), INVERSION_PERFECTA("65"), PAGO_IMPUESTOS_DEPOSITO_REF(
			"66"), ACTIVACION_SERVICIOS("67"), PAGARE_AHORRAFIRME("68"), AFIRME_MOVIL(
			"69"), ANTICIPO_NOMINA("70"), CREDITO_NOMINA("72"), REPOSICION_TARJETAS(
			"74"), TRASPASO_PROPIAS_MASIVO("75"), APORTACION_AFORE_POST("76"), RECARGA_TA_MOVISTAR(
			"78"), LINEA_CAPTURA_TESOFE("79"), ORDENES_PAGO_ENVIO_DINERO("80"), TRASPASO_PUNTOS_BONUS(
			"81"), DOMICILIACION_SERVICIOS_BASICOS("82"), DISPOSICION_TDC_PYME(
			"83"), AVISO_VIAJE("86"), MIS_CREDITOS_AFIRME("87"), PAGARE_GRADUAL(
			"88"), PAGARE_MULTIPLE("89"), VENTA_SEGUROS_ANTIFRAUDE("90"), ALERTAS_AFIRME(
			"91"), FACTURACION_ELECTRONICA("92"), ASOCIACION_CTA_NUMERO_MOVIL(
			"94"), ACTIVACIÓN_TDC("96"), CAMBIO_LIMITES_TDC_ADICIONAL("97"), BLOQUEO_DESBLOQUEO_TDC(
			"98");
	HorarioServicio(String value) {
		this.value = value;
	}

	private String value;

	/**
	 * @return the value
	 */
	public String getValue() {
		return value;
	}

	/**
	 * @param value
	 *            the value to set
	 */
	public void setValue(String value) {
		this.value = value;
	}

	public static HorarioServicio findByValue(String value) {

		for (HorarioServicio excepcion : values()) {
			if (excepcion.getValue().equals(value)) {
				return excepcion;
			}
		}
		return null;
	}

}
