package com.afirme.afirmenet.ibs.databeans;

import java.math.BigDecimal;

import com.afirme.afirmenet.ibs.generics.Util;

/**
 * Jdbc Bean Class<br>
 * <br>
 * Autogenerated on 02/04/2004 10:40:11<br>
 * &nbsp;&nbsp;&nbsp; table = "DC_CONVENIOAS400Bean"
*
* @author Generator
*/
public class DC_CONVENIOAS400 implements java.io.Serializable
{

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private String numTelefono = "";

	private String cveLada = "";
	
	private String propietario = "";
	
	//jochoa
	private BigDecimal recargos = new BigDecimal("0");
	   
	private int diasG = 0; 


	/**
	 * The ENTITYID attribute.
	*/
	protected java.lang.String ENTITYID = "";

	/**
	 * Gets the ENTITYID value.
	*/
	public java.lang.String getENTITYID()
	{
		return ENTITYID.toUpperCase().trim();
	}

	/**
	 * Sets the ENTITYID value.
	*/
	public void setENTITYID(java.lang.String ENTITYID)
	{
		this.ENTITYID = ENTITYID;
	}
	/**
	 * The DEBACC attribute.
	*/
	protected java.lang.String DEBACC = "";

	/**
	 * Gets the DEBACC value.
	*/
	public java.lang.String getDEBACC()
	{
		return DEBACC.toUpperCase().trim();
	}

	/**
	 * Sets the DEBACC value.
	*/
	public void setDEBACC(java.lang.String DEBACC)
	{
		this.DEBACC = DEBACC;
	}
	/**
	 * The AMOUNT attribute.
	*/
	protected java.math.BigDecimal AMOUNT = new BigDecimal("0");

	/**
	 * Gets the AMOUNT value.
	*/
	public java.math.BigDecimal getAMOUNT()
	{
		return AMOUNT;
	}

	/**
	 * Sets the AMOUNT value.
	*/
	public void setAMOUNT(java.math.BigDecimal AMOUNT)
	{
		this.AMOUNT = AMOUNT;
	}
	/**
	 * The CCY attribute.
	*/
	protected java.lang.String CCY = "";

	/**
	 * Gets the CCY value.
	*/
	public java.lang.String getCCY()
	{
		return CCY.toUpperCase().trim();
	}

	/**
	 * Sets the CCY value.
	*/
	public void setCCY(java.lang.String CCY)
	{
		this.CCY = CCY;
	}
	/**
	 * The PDD attribute.
	*/
	protected java.lang.String PDD = "";

	/**
	 * Gets the PDD value.
	*/
	public java.lang.String getPDD()
	{
		return PDD.toUpperCase().trim();
	}

	/**
	 * Sets the PDD value.
	*/
	public void setPDD(java.lang.String PDD)
	{
		this.PDD = PDD;
	}
	/**
	 * The PMM attribute.
	*/
	protected java.lang.String PMM = "";

	/**
	 * Gets the PMM value.
	*/
	public java.lang.String getPMM()
	{
		return PMM.toUpperCase().trim();
	}

	/**
	 * Sets the PMM value.
	*/
	public void setPMM(java.lang.String PMM)
	{
		this.PMM = PMM;
	}
	/**
	 * The PYY attribute.
	*/
	protected java.lang.String PYY = "";

	/**
	 * Gets the PYY value.
	*/
	public java.lang.String getPYY()
	{
		return PYY.toUpperCase().trim();
	}

	/**
	 * Sets the PYY value.
	*/
	public void setPYY(java.lang.String PYY)
	{
		this.PYY = PYY;
	}
	/**
	 * The VDD attribute.
	*/
	protected java.lang.String VDD = "";

	/**
	 * Gets the VDD value.
	*/
	public java.lang.String getVDD()
	{
		return VDD.toUpperCase().trim();
	}

	/**
	 * Sets the VDD value.
	*/
	public void setVDD(java.lang.String VDD)
	{
		this.VDD = VDD;
	}
	/**
	 * The VMM attribute.
	*/
	protected java.lang.String VMM = "";

	/**
	 * Gets the VMM value.
	*/
	public java.lang.String getVMM()
	{
		return VMM.toUpperCase().trim();
	}

	/**
	 * Sets the VMM value.
	*/
	public void setVMM(java.lang.String VMM)
	{
		this.VMM = VMM;
	}
	/**
	 * The VYY attribute.
	*/
	protected java.lang.String VYY = "";

	/**
	 * Gets the VYY value.
	*/
	public java.lang.String getVYY()
	{
		return VYY.toUpperCase().trim();
	}

	/**
	 * Sets the VYY value.
	*/
	public void setVYY(java.lang.String VYY)
	{
		this.VYY = VYY;
	}
	/**
	 * The VHH attribute.
	*/
	protected java.lang.String VHH = "";

	/**
	 * Gets the VHH value.
	*/
	public java.lang.String getVHH()
	{
		return VHH.toUpperCase().trim();
	}

	/**
	 * Sets the VHH value.
	*/
	public void setVHH(java.lang.String VHH)
	{
		this.VHH = VHH;
	}
	/**
	 * The VSS attribute.
	*/
	protected java.lang.String VSS = "";

	/**
	 * Gets the VSS value.
	*/
	public java.lang.String getVSS()
	{
		return VSS.toUpperCase().trim();
	}

	/**
	 * Sets the VSS value.
	*/
	public void setVSS(java.lang.String VSS)
	{
		this.VSS = VSS;
	}
	/**
	 * The DCIBS_REF attribute.
	*/
	protected java.lang.String DCIBS_REF = "";

	/**
	 * Gets the DCIBS_REF value.
	*/
	public java.lang.String getDCIBS_REF()
	{
		return DCIBS_REF.toUpperCase().trim();
	}

	/**
	 * Sets the DCIBS_REF value.
	*/
	public void setDCIBS_REF(java.lang.String DCIBS_REF)
	{
		this.DCIBS_REF = DCIBS_REF;
	}
	/**
	 * The SERTYP attribute.
	*/
	protected int SERTYP = 0;

	/**
	 * Gets the SERTYP value.
	*/
	public int getSERTYP()
	{
		return SERTYP;
	}

	/**
	 * Sets the SERTYP value.
	*/
	public void setSERTYP(int SERTYP)
	{
		this.SERTYP = SERTYP;
	}
	/**
	 * The SERACC attribute.
	*/
	protected java.lang.String SERACC = "";

	/**
	 * Gets the SERACC value.
	*/
	public java.lang.String getSERACC()
	{
		return SERACC.toUpperCase().trim();
	}

	/**
	 * Sets the SERACC value.
	*/
	public void setSERACC(java.lang.String SERACC)
	{
		this.SERACC = SERACC;
	}
	/**
	 * The SERCOM attribute.
	*/
	protected int SERCOM = 0;

	/**
	 * Gets the SERCOM value.
	*/
	public int getSERCOM()
	{
		return SERCOM;
	}

	/**
	 * Sets the SERCOM value.
	*/
	public void setSERCOM(int SERCOM)
	{
		this.SERCOM = SERCOM;
	}
	/**
	 * The SERNOM attribute.
	*/
	protected java.lang.String SERNOM = "";

	/**
	 * Gets the SERNOM value.
	*/
	public java.lang.String getSERNOM()
	{
		return SERNOM.toUpperCase().trim();
	}

	/**
	 * Sets the SERNOM value.
	*/
	public void setSERNOM(java.lang.String SERNOM)
	{
		this.SERNOM = SERNOM;
	}
	/**
	 * The SERNAM attribute.
	*/
	protected java.lang.String SERNAM = "";

	/**
	 * Gets the SERNAM value.
	*/
	public java.lang.String getSERNAM()
	{
		return SERNAM.toUpperCase().trim();
	}

	/**
	 * Sets the SERNAM value.
	*/
	public void setSERNAM(java.lang.String SERNAM)
	{
		this.SERNAM = SERNAM;
	}
	/**
	 * The SERDS1 attribute.
	*/
	protected java.lang.String SERDS1 = "";

	/**
	 * Gets the SERDS1 value.
	*/
	public java.lang.String getSERDS1()
	{
		return SERDS1.toUpperCase().trim();
	}

	/**
	 * Sets the SERDS1 value.
	*/
	public void setSERDS1(java.lang.String SERDS1)
	{
		this.SERDS1 = SERDS1;
	}
	/**
	 * The SERDS2 attribute.
	*/
	protected java.lang.String SERDS2 = "";

	/**
	 * Gets the SERDS2 value.
	*/
	public java.lang.String getSERDS2()
	{
		return SERDS2.toUpperCase().trim();
	}

	/**
	 * Sets the SERDS2 value.
	*/
	public void setSERDS2(java.lang.String SERDS2)
	{
		this.SERDS2 = SERDS2;
	}
	/**
	 * The SERRTY attribute.
	*/
	protected java.lang.String SERRTY = "";

	/**
	 * Gets the SERRTY value.
	*/
	public java.lang.String getSERRTY()
	{
		return SERRTY.toUpperCase().trim();
	}

	/**
	 * Sets the SERRTY value.
	*/
	public void setSERRTY(java.lang.String SERRTY)
	{
		this.SERRTY = SERRTY;
	}
	/**
	 * The SERMIN attribute.
	*/
	protected int SERMIN = 0;

	/**
	 * Gets the SERMIN value.
	*/
	public int getSERMIN()
	{
		return SERMIN;
	}

	/**
	 * Sets the SERMIN value.
	*/
	public void setSERMIN(int SERMIN)
	{
		this.SERMIN = SERMIN;
	}
	/**
	 * The SERMAX attribute.
	*/
	protected int SERMAX = 0;

	/**
	 * Gets the SERMAX value.
	*/
	public int getSERMAX()
	{
		return SERMAX;
	}

	/**
	 * Sets the SERMAX value.
	*/
	public void setSERMAX(int SERMAX)
	{
		this.SERMAX = SERMAX;
	}
	/**
	 * The SERFLG attribute.
	*/
	protected java.lang.String SERFLG = "";

	/**
	 * Gets the SERFLG value.
	*/
	public java.lang.String getSERFLG()
	{
		return SERFLG.toUpperCase().trim();
	}

	/**
	 * Sets the SERFLG value.
	*/
	public void setSERFLG(java.lang.String SERFLG)
	{
		this.SERFLG = SERFLG;
	}
	/**
	 * The SERTAX attribute.
	*/
	protected java.lang.String SERTAX = "";

	/**
	 * Gets the SERTAX value.
	*/
	public java.lang.String getSERTAX()
	{
		return SERTAX.toUpperCase().trim();
	}

	/**
	 * Sets the SERTAX value.
	*/
	public void setSERTAX(java.lang.String SERTAX)
	{
		this.SERTAX = SERTAX;
	}
	/**
	 * The SERDTR attribute.
	*/
	protected int SERDTR = 0;

	/**
	 * Gets the SERDTR value.
	*/
	public int getSERDTR()
	{
		return SERDTR;
	}

	/**
	 * Sets the SERDTR value.
	*/
	public void setSERDTR(int SERDTR)
	{
		this.SERDTR = SERDTR;
	}
	/**
	 * The SERHLP attribute.
	*/
	protected java.lang.String SERHLP = "";

	/**
	 * Gets the SERHLP value.
	*/
	public java.lang.String getSERHLP()
	{
		return SERHLP.toUpperCase().trim();
	}

	/**
	 * Sets the SERHLP value.
	*/
	public void setSERHLP(java.lang.String SERHLP)
	{
		this.SERHLP = SERHLP;
	}
	/**
	 * The CONVNUM attribute.
	*/
	protected java.math.BigDecimal CONVNUM = new BigDecimal("0");

	/**
	 * Gets the CONVNUM value.
	*/
	public java.math.BigDecimal getCONVNUM()
	{
		return CONVNUM;
	}

	/**
	 * Sets the CONVNUM value.
	*/
	public void setCONVNUM(java.math.BigDecimal CONVNUM)
	{
		this.CONVNUM = CONVNUM;
	}
	/**
	 * The OUSER attribute.
	*/
	protected java.lang.String OUSER = "";

	/**
	 * Gets the OUSER value.
	*/
	public java.lang.String getOUSER()
	{
		return OUSER.toUpperCase().trim();
	}

	/**
	 * Sets the OUSER value.
	*/
	public void setOUSER(java.lang.String OUSER)
	{
		this.OUSER = OUSER;
	}
	/**
	 * The VUSER attribute.
	*/
	protected java.lang.String VUSER = "";

	/**
	 * Gets the VUSER value.
	*/
	public java.lang.String getVUSER()
	{
		return VUSER.toUpperCase().trim();
	}

	/**
	 * Sets the VUSER value.
	*/
	public void setVUSER(java.lang.String VUSER)
	{
		this.VUSER = VUSER;
	}
	/**
	 * The AUSER attribute.
	*/
	protected java.lang.String AUSER = "";

	/**
	 * Gets the AUSER value.
	*/
	public java.lang.String getAUSER()
	{
		return AUSER.toUpperCase().trim();
	}

	/**
	 * Sets the AUSER value.
	*/
	public void setAUSER(java.lang.String AUSER)
	{
		this.AUSER = AUSER;
	}
	/**
	 * The ODATE attribute.
	*/
	protected java.lang.String ODATE = "";

	/**
	 * Gets the ODATE value.
	*/
	public java.lang.String getODATE()
	{
		return ODATE.toUpperCase().trim();
	}

	/**
	 * Sets the ODATE value.
	*/
	public void setODATE(java.lang.String ODATE)
	{
		this.ODATE = ODATE;
	}
	/**
	 * The VDATE attribute.
	*/
	protected java.lang.String VDATE = "";

	/**
	 * Gets the VDATE value.
	*/
	public java.lang.String getVDATE()
	{
		return VDATE.toUpperCase().trim();
	}

	/**
	 * Sets the VDATE value.
	*/
	public void setVDATE(java.lang.String VDATE)
	{
		this.VDATE = VDATE;
	}
	/**
	 * The ADATE attribute.
	*/
	protected java.lang.String ADATE = "";

	/**
	 * Gets the ADATE value.
	*/
	public java.lang.String getADATE()
	{
		return ADATE.toUpperCase().trim();
	}

	/**
	 * Sets the ADATE value.
	*/
	public void setADATE(java.lang.String ADATE)
	{
		this.ADATE = ADATE;
	}
	/**
	 * The STS attribute.
	*/
	protected java.lang.String STS = "";

	/**
	 * Gets the STS value.
	*/
	public java.lang.String getSTS()
	{
		return STS.toUpperCase().trim();
	}

	/**
	 * Sets the STS value.
	*/
	public void setSTS(java.lang.String STS)
	{
		this.STS = STS;
	}
	/**
	 * The NUMAPR attribute.
	*/
	protected int NUMAPR = 0;

	/**
	 * Gets the NUMAPR value.
	*/
	public int getNUMAPR()
	{
		return NUMAPR;
	}

	/**
	 * Sets the NUMAPR value.
	*/
	public void setNUMAPR(int NUMAPR)
	{
		this.NUMAPR = NUMAPR;
	}
	/**
	 * The DESCRIP attribute.
	*/
	protected java.lang.String DESCRIP = "";

	/**
	 * Gets the DESCRIP value.
	*/
	public java.lang.String getDESCRIP()
	{
		return DESCRIP.toUpperCase().trim();
	}

	/**
	 * Sets the DESCRIP value.
	*/
	public void setDESCRIP(java.lang.String DESCRIP)
	{
		this.DESCRIP = DESCRIP;
	}
	/**
	 * The FLG attribute.
	*/
	protected java.lang.String FLG = "";

	/**
	 * Gets the FLG value.
	*/
	public java.lang.String getFLG()
	{
		return FLG.toUpperCase().trim();
	}

	/**
	 * Sets the FLG value.
	*/
	public void setFLG(java.lang.String FLG)
	{
		this.FLG = FLG;
	}
	/**
	 * The CONFNUM attribute.
	*/
	protected java.lang.String CONFNUM = "";

	/**
	 * Gets the CONFNUM value.
	*/
	public java.lang.String getCONFNUM()
	{
		return CONFNUM.toUpperCase().trim();
	}

	/**
	 * Sets the CONFNUM value.
	*/
	public void setCONFNUM(java.lang.String CONFNUM)
	{
		this.CONFNUM = CONFNUM;
	}
	/**
	 * The DIGITALSIGNATURE attribute.
	*/
	protected java.lang.String DIGITALSIGNATURE = "";

	/**
	 * Gets the DIGITALSIGNATURE value.
	*/
	public java.lang.String getDIGITALSIGNATURE()
	{
		return DIGITALSIGNATURE.toUpperCase().trim();
	}

	/**
	 * Sets the DIGITALSIGNATURE value.
	*/
	public void setDIGITALSIGNATURE(java.lang.String DIGITALSIGNATURE)
	{
		this.DIGITALSIGNATURE = DIGITALSIGNATURE;
	}

	/**
		* The FVD attribute.
	*/
	protected java.lang.String FVD = "";

	/**
		* Gets the FVD value.
	*/
	public java.lang.String getFVD()
	{
		return FVD.toUpperCase().trim();
	}

	/**
		* Sets the FVD value.
	*/
	public void setFVD(java.lang.String FVD)
	{
		this.FVD = FVD;
	}

	/**
		* The FVM attribute.
	*/
	protected java.lang.String FVM = "";

	/**
		* Gets the FVM value.
	*/
	public java.lang.String getFVM()
	{
		return FVM.toUpperCase().trim();
	}

	/**
		* Sets the FVM value.
	*/
	public void setFVM(java.lang.String FVM)
	{
		this.FVM = FVM;
	}

	/**
		* The FVY attribute.
	*/
	protected java.lang.String FVY = "";

	/**
		* Gets the FVY value.
	*/
	public java.lang.String getFVY()
	{
		return FVY.toUpperCase().trim();
	}

	/**
		* Sets the FVY value.
	*/
	public void setFVY(java.lang.String FVY)
	{
		this.FVY = FVY;
	}

	public String toString()
	{
		StringBuffer results = new StringBuffer();

		results.append(getClass().getName() + "\n");
		results.append("\tENTITYID=" + ENTITYID + "\n");
		results.append("\tDEBACC=" + DEBACC + "\n");
		results.append("\tAMOUNT=" + AMOUNT + "\n");
		results.append("\tCCY=" + CCY + "\n");
		results.append("\tPDD=" + PDD + "\n");
		results.append("\tPMM=" + PMM + "\n");
		results.append("\tPYY=" + PYY + "\n");
		results.append("\tVDD=" + VDD + "\n");
		results.append("\tVMM=" + VMM + "\n");
		results.append("\tVYY=" + VYY + "\n");
		results.append("\tVHH=" + VHH + "\n");
		results.append("\tVSS=" + VSS + "\n");
		results.append("\tDCIBS_REF=" + DCIBS_REF + "\n");
		results.append("\tSERTYP=" + SERTYP + "\n");
		results.append("\tSERACC=" + SERACC + "\n");
		results.append("\tSERCOM=" + SERCOM + "\n");
		results.append("\tSERNOM=" + SERNOM + "\n");
		results.append("\tSERNAM=" + SERNAM + "\n");
		results.append("\tSERDS1=" + SERDS1 + "\n");
		results.append("\tSERDS2=" + SERDS2 + "\n");
		results.append("\tSERRTY=" + SERRTY + "\n");
		results.append("\tSERMIN=" + SERMIN + "\n");
		results.append("\tSERMAX=" + SERMAX + "\n");
		results.append("\tSERFLG=" + SERFLG + "\n");
		results.append("\tSERTAX=" + SERTAX + "\n");
		results.append("\tSERDTR=" + SERDTR + "\n");
		results.append("\tSERHLP=" + SERHLP + "\n");
		results.append("\tCONVNUM=" + CONVNUM + "\n");
		results.append("\tOUSER=" + OUSER + "\n");
		results.append("\tVUSER=" + VUSER + "\n");
		results.append("\tAUSER=" + AUSER + "\n");
		results.append("\tODATE=" + ODATE + "\n");
		results.append("\tVDATE=" + VDATE + "\n");
		results.append("\tADATE=" + ADATE + "\n");
		results.append("\tSTS=" + STS + "\n");
		results.append("\tNUMAPR=" + NUMAPR + "\n");
		results.append("\tDESCRIP=" + DESCRIP + "\n");
		results.append("\tFLG=" + FLG + "\n");
		results.append("\tCONFNUM=" + CONFNUM + "\n");
		results.append("\tDIGITALSIGNATURE=" + DIGITALSIGNATURE + "\n");

		return results.toString();
	}
	
	/*
	 * Regresa la referencia con formato
	 */
	public String getReferencia()
	{
		String referencia ="";
		switch(SERCOM)
		{
			case 101:
			referencia = Util.formatearNumTelefono(this.cveLada,this.numTelefono);
			break;
			case 131:
			referencia = SERACC.substring(0,2)+"-"+ SERACC.substring(2,14)+"-"+ SERACC.substring(14,20)+"-"+ SERACC.substring(20,29)+"-"+ SERACC.substring(29,30);
			break;
			default:
			referencia = SERACC;
			break;
		}
		
		return referencia;
	}

	public String getCFEReference(int beginIndex, int endIndex)
	{
		if (SERACC != null && !SERACC.equals(""))
		{
			return SERACC.substring(beginIndex, endIndex);
		}
		else
		{
			return "";
		}
	}

	public String getCveLada()
	{
		return cveLada;
	}

	public String getNumTelefono()
	{
		return numTelefono;
	}

	public void setCveLada(String cveLada)
	{
		this.cveLada = cveLada;
	}

	public void setNumTelefono(String numTelefono)
	{
		this.numTelefono = numTelefono;
	}

	public String getPropietario() {
		return propietario;
	}

	public void setPropietario(String propietario) {
		this.propietario = propietario;
	}

	public BigDecimal getRecargos() {
		return recargos;
	}

	public void setRecargos(BigDecimal recargos) {
		this.recargos = recargos;
	}

	public int getDiasG() {
		return diasG;
	}

	public void setDiasG(int diasG) {
		this.diasG = diasG;
	}
	
	
}