package com.afirme.afirmenet.ibs.databeans;

import java.math.BigDecimal;

import com.afirme.afirmenet.ibs.beans.JBParent;

/**
 * Jdbc Bean Class<br>
 * <br>
 * Autogenerated on 01/28/2004 09:25:06<br>
 * &nbsp;&nbsp;&nbsp; table = "DC_NOMINA_DBean"
 * 
 * @author Generator
 */
public class DC_NOMINA_D extends JBParent {

	/**
	 * The ENTITYID attribute.
	 */
	// protected java.lang.String ENTITYID = "";

	/**
	 * Gets the ENTITYID value.
	 */
	// public java.lang.String getENTITYID() {
	// return ENTITYID.toUpperCase().trim();
	// }

	/**
	 * Sets the ENTITYID value.
	 */
	// public void setENTITYID(java.lang.String ENTITYID) {
	// this.ENTITYID = ENTITYID;
	// }
	/**
	 * The DEBACC attribute.
	 */
	// protected java.lang.String DEBACC = "";

	/**
	 * Gets the DEBACC value.
	 */
	// public java.lang.String getDEBACC() {
	// return DEBACC.toUpperCase().trim();
	// }

	/**
	 * Sets the DEBACC value.
	 */
	// public void setDEBACC(java.lang.String DEBACC) {
	// this.DEBACC = DEBACC;
	// }
	/**
	 * The CREACC attribute.
	 */
	protected java.lang.String CREACC = "";

	/**
	 * Gets the CREACC value.
	 */
	public java.lang.String getCREACC() {
		return CREACC.toUpperCase().trim();
	}

	/**
	 * Sets the CREACC value.
	 */
	public void setCREACC(java.lang.String CREACC) {
		this.CREACC = CREACC;
	}

	/**
	 * The AMOUNT attribute.
	 */
	// protected java.math.BigDecimal AMOUNT = new BigDecimal("0");

	/**
	 * Gets the AMOUNT value.
	 */
	// public java.math.BigDecimal getAMOUNT() {
	// return AMOUNT;
	// }

	/**
	 * Sets the AMOUNT value.
	 */
	// public void setAMOUNT(java.math.BigDecimal AMOUNT) {
	// this.AMOUNT = AMOUNT;
	// }
	/**
	 * The CCY attribute.
	 */
	protected java.lang.String CCY = "";

	/**
	 * Gets the CCY value.
	 */
	public java.lang.String getCCY() {
		return CCY.toUpperCase().trim();
	}

	/**
	 * Sets the CCY value.
	 */
	public void setCCY(java.lang.String CCY) {
		this.CCY = CCY;
	}

	/**
	 * The DCIBS_REF attribute.
	 */
	protected java.lang.String DCIBS_REF = "";

	/**
	 * Gets the DCIBS_REF value.
	 */
	public java.lang.String getDCIBS_REF() {
		return DCIBS_REF.toUpperCase().trim();
	}

	/**
	 * Sets the DCIBS_REF value.
	 */
	public void setDCIBS_REF(java.lang.String DCIBS_REF) {
		this.DCIBS_REF = DCIBS_REF;
	}

	/**
	 * The BNKRECPTOR attribute.
	 */
	protected java.lang.String BNKRECPTOR = "";

	/**
	 * Gets the BNKRECPTOR value.
	 */
	public java.lang.String getBNKRECPTOR() {
		return BNKRECPTOR.toUpperCase().trim();
	}

	/**
	 * Sets the BNKRECPTOR value.
	 */
	public void setBNKRECPTOR(java.lang.String BNKRECPTOR) {
		this.BNKRECPTOR = BNKRECPTOR;
	}

	/**
	 * The NAME attribute.
	 */
	protected java.lang.String NAME = "";

	/**
	 * Gets the NAME value.
	 */
	public java.lang.String getNAME() {
		return NAME.toUpperCase().trim();
	}

	/**
	 * Sets the NAME value.
	 */
	public void setNAME(java.lang.String NAME) {
		this.NAME = NAME;
	}

	/**
	 * The ACCTYPE attribute.
	 */
	protected java.lang.String ACCTYPE = "";

	/**
	 * Gets the ACCTYPE value.
	 */
	public java.lang.String getACCTYPE() {
		return ACCTYPE.toUpperCase().trim();
	}

	/**
	 * Sets the ACCTYPE value.
	 */
	public void setACCTYPE(java.lang.String ACCTYPE) {
		this.ACCTYPE = ACCTYPE;
	}

	/**
	 * The BNKNAME attribute.
	 */
	protected java.lang.String BNKNAME = "";

	/**
	 * Gets the BNKNAME value.
	 */
	public java.lang.String getBNKNAME() {
		return BNKNAME.toUpperCase().trim();
	}

	/**
	 * Sets the BNKNAME value.
	 */
	public void setBNKNAME(java.lang.String BNKNAME) {
		this.BNKNAME = BNKNAME;
	}

	/**
	 * The RECNUM attribute.
	 */
	protected java.math.BigDecimal RECNUM = new BigDecimal("0");

	/**
	 * Gets the RECNUM value.
	 */
	public java.math.BigDecimal getRECNUM() {
		return RECNUM;
	}

	/**
	 * Sets the RECNUM value.
	 */
	public void setRECNUM(java.math.BigDecimal RECNUM) {
		this.RECNUM = RECNUM;
	}

	public String toString() {
		StringBuffer results = new StringBuffer();

		results.append(getClass().getName() + "\n");
		results.append("\tENTITYID=" + ENTITYID + "\n");
		results.append("\tDEBACC=" + DEBACC + "\n");
		results.append("\tCREACC=" + CREACC + "\n");
		results.append("\tAMOUNT=" + AMOUNT + "\n");
		results.append("\tCCY=" + CCY + "\n");
		results.append("\tDCIBS_REF=" + DCIBS_REF + "\n");
		results.append("\tBNKRECPTOR=" + BNKRECPTOR + "\n");
		results.append("\tNAME=" + NAME + "\n");
		results.append("\tACCTYPE=" + ACCTYPE + "\n");
		results.append("\tBNKNAME=" + BNKNAME + "\n");
		results.append("\tRECNUM=" + RECNUM + "\n");

		return results.toString();
	}

}