package com.afirme.afirmenet.ibs.databeans;

/**
 * Jdbc Bean Class<br>
 * <br>
 * Autogenerated on 01/06/2004 11:10:28<br>
 * &nbsp;&nbsp;&nbsp; table = "DC_TAXHEADERBean"
 * 
 * @author Generator
 */
public class DC_TAXHEADER implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
	 * The CODE attribute.
	 */
	protected java.lang.String CODE = "";

	/**
	 * Gets the CODE value.
	 */
	public java.lang.String getCODE() {
		return CODE.toUpperCase().trim();
	}

	/**
	 * Sets the CODE value.
	 */
	public void setCODE(java.lang.String CODE) {
		this.CODE = CODE;
	}

	/**
	 * The DESCRIPTION attribute.
	 */
	protected java.lang.String DESCRIPTION = "";

	/**
	 * Gets the DESCRIPTION value.
	 */
	public java.lang.String getDESCRIPTION() {
		return DESCRIPTION.toUpperCase().trim();
	}

	/**
	 * Sets the DESCRIPTION value.
	 */
	public void setDESCRIPTION(java.lang.String DESCRIPTION) {
		this.DESCRIPTION = DESCRIPTION;
	}

	/**
	 * The FIELDNAME attribute.
	 */
	protected java.lang.String FIELDNAME = "";

	/**
	 * Gets the FIELDNAME value.
	 */
	public java.lang.String getFIELDNAME() {
		return FIELDNAME.toUpperCase().trim();
	}

	/**
	 * Sets the FIELDNAME value.
	 */
	public void setFIELDNAME(java.lang.String FIELDNAME) {
		this.FIELDNAME = FIELDNAME;
	}

	/**
	 * The Col003 attribute.
	 */
	protected java.lang.String Col003 = "";

	/**
	 * Gets the Col003 value.
	 */
	public java.lang.String getCol003() {
		return Col003.toUpperCase().trim();
	}

	/**
	 * Sets the Col003 value.
	 */
	public void setCol003(java.lang.String Col003) {
		this.Col003 = Col003;
	}

	/**
	 * The Col004 attribute.
	 */
	protected java.lang.String Col004 = "";

	/**
	 * Gets the Col004 value.
	 */
	public java.lang.String getCol004() {
		return Col004.toUpperCase().trim();
	}

	/**
	 * Sets the Col004 value.
	 */
	public void setCol004(java.lang.String Col004) {
		this.Col004 = Col004;
	}

	/**
	 * The Col005 attribute.
	 */
	protected java.lang.String Col005 = "";

	/**
	 * Gets the Col005 value.
	 */
	public java.lang.String getCol005() {
		return Col005.toUpperCase().trim();
	}

	/**
	 * Sets the Col005 value.
	 */
	public void setCol005(java.lang.String Col005) {
		this.Col005 = Col005;
	}

	/**
	 * The Col006 attribute.
	 */
	protected java.lang.String Col006 = "";

	/**
	 * Gets the Col006 value.
	 */
	public java.lang.String getCol006() {
		return Col006.toUpperCase().trim();
	}

	/**
	 * Sets the Col006 value.
	 */
	public void setCol006(java.lang.String Col006) {
		this.Col006 = Col006;
	}

	/**
	 * The Col007 attribute.
	 */
	protected java.lang.String Col007 = "";

	/**
	 * Gets the Col007 value.
	 */
	public java.lang.String getCol007() {
		return Col007.toUpperCase().trim();
	}

	/**
	 * Sets the Col007 value.
	 */
	public void setCol007(java.lang.String Col007) {
		this.Col007 = Col007;
	}

	/**
	 * The CONFNUM attribute.
	 */
	protected java.lang.String CONFNUM = "";

	/**
	 * Gets the CONFNUM value.
	 */
	public java.lang.String getCONFNUM() {
		return CONFNUM.toUpperCase().trim();
	}

	/**
	 * Sets the CONFNUM value.
	 */
	public void setCONFNUM(java.lang.String CONFNUM) {
		this.CONFNUM = CONFNUM;
	}

	/**
	 * The DIGITALSIGNATURE attribute.
	 */
	protected java.lang.String DIGITALSIGNATURE = "";

	/**
	 * Gets the DIGITALSIGNATURE value.
	 */
	public java.lang.String getDIGITALSIGNATURE() {
		return DIGITALSIGNATURE.toUpperCase().trim();
	}

	/**
	 * Sets the DIGITALSIGNATURE value.
	 */
	public void setDIGITALSIGNATURE(java.lang.String DIGITALSIGNATURE) {
		this.DIGITALSIGNATURE = DIGITALSIGNATURE;
	}

	public String toString() {
		StringBuffer results = new StringBuffer();

		results.append(getClass().getName() + "\n");
		results.append("\tCODE=" + CODE + "\n");
		results.append("\tDESCRIPTION=" + DESCRIPTION + "\n");
		results.append("\tFIELDNAME=" + FIELDNAME + "\n");
		results.append("\tCol003=" + Col003 + "\n");
		results.append("\tCol004=" + Col004 + "\n");
		results.append("\tCol005=" + Col005 + "\n");
		results.append("\tCol006=" + Col006 + "\n");
		results.append("\tCol007=" + Col007 + "\n");
		results.append("\tCONFNUM=" + CONFNUM + "\n");
		results.append("\tDIGITALSIGNATURE=" + DIGITALSIGNATURE + "\n");

		return results.toString();
	}

}