/*
 * Modificado por:	Christian Antonio Gómez Flores
 * Empresa:			Consiss
 * Fecha:			21-Marzo-2007
 * */
package com.afirme.afirmenet.ibs.databeans;

import java.math.BigDecimal;

/**
 * Jdbc Bean Class<br>
 * <br>
 * Autogenerated on 10/28/2003 03:44:22<br>
 * &nbsp;&nbsp;&nbsp; table = "INSERBean"
 * 
 * @author Generator
 */
public class INSER implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
	 * The SERBNK attribute.
	 */
	protected java.lang.String SERBNK = "";

	/**
	 * Gets the SERBNK value.
	 */
	public java.lang.String getSERBNK() {
		return SERBNK.toUpperCase().trim();
	}

	/**
	 * Sets the SERBNK value.
	 */
	public void setSERBNK(java.lang.String SERBNK) {
		this.SERBNK = SERBNK;
	}

	/**
	 * The SERTYP attribute.
	 */
	protected java.math.BigDecimal SERTYP = new BigDecimal("0");

	/**
	 * Gets the SERTYP value.
	 */
	public java.math.BigDecimal getSERTYP() {
		return SERTYP;
	}

	/**
	 * Sets the SERTYP value.
	 */
	public void setSERTYP(java.math.BigDecimal SERTYP) {
		this.SERTYP = SERTYP;
	}

	/**
	 * The SERCOM attribute.
	 */
	protected java.math.BigDecimal SERCOM = new BigDecimal("0");

	/**
	 * Gets the SERCOM value.
	 */
	public java.math.BigDecimal getSERCOM() {
		return SERCOM;
	}

	/**
	 * Sets the SERCOM value.
	 */
	public void setSERCOM(java.math.BigDecimal SERCOM) {
		this.SERCOM = SERCOM;
	}

	/**
	 * The SERNAM attribute.
	 */
	protected java.lang.String SERNAM = "";

	/**
	 * Gets the SERNAM value.
	 */
	public java.lang.String getSERNAM() {
		return SERNAM.toUpperCase().trim();
	}

	/**
	 * Sets the SERNAM value.
	 */
	public void setSERNAM(java.lang.String SERNAM) {
		this.SERNAM = SERNAM;
	}

	/**
	 * The SERDS1 attribute.
	 */
	protected java.lang.String SERDS1 = "";

	/**
	 * Gets the SERDS1 value.
	 */
	public java.lang.String getSERDS1() {
		return SERDS1.toUpperCase().trim();
	}

	/**
	 * Sets the SERDS1 value.
	 */
	public void setSERDS1(java.lang.String SERDS1) {
		this.SERDS1 = SERDS1;
	}

	/**
	 * The SERDS2 attribute.
	 */
	protected java.lang.String SERDS2 = "";

	/**
	 * Gets the SERDS2 value.
	 */
	public java.lang.String getSERDS2() {
		return SERDS2.toUpperCase().trim();
	}

	/**
	 * Sets the SERDS2 value.
	 */
	public void setSERDS2(java.lang.String SERDS2) {
		this.SERDS2 = SERDS2;
	}

	/**
	 * The SERREF attribute.
	 */
	protected java.math.BigDecimal SERREF = new BigDecimal("0");

	/**
	 * Gets the SERREF value.
	 */
	public java.math.BigDecimal getSERREF() {
		return SERREF;
	}

	/**
	 * Sets the SERREF value.
	 */
	public void setSERREF(java.math.BigDecimal SERREF) {
		this.SERREF = SERREF;
	}

	/**
	 * The SERACC attribute.
	 */
	protected java.lang.String SERACC = "";

	/**
	 * Gets the SERACC value.
	 */
	public java.lang.String getSERACC() {
		return SERACC.toUpperCase().trim();
	}

	/**
	 * Sets the SERACC value.
	 */
	public void setSERACC(java.lang.String SERACC) {
		this.SERACC = SERACC;
	}

	/**
	 * The SERVOU attribute.
	 */
	protected java.math.BigDecimal SERVOU = new BigDecimal("0");

	/**
	 * Gets the SERVOU value.
	 */
	public java.math.BigDecimal getSERVOU() {
		return SERVOU;
	}

	/**
	 * Sets the SERVOU value.
	 */
	public void setSERVOU(java.math.BigDecimal SERVOU) {
		this.SERVOU = SERVOU;
	}

	/**
	 * The SERRTY attribute.
	 */
	protected java.lang.String SERRTY = "";

	/**
	 * Gets the SERRTY value.
	 */
	public java.lang.String getSERRTY() {
		return SERRTY.toUpperCase().trim();
	}

	/**
	 * Sets the SERRTY value.
	 */
	public void setSERRTY(java.lang.String SERRTY) {
		this.SERRTY = SERRTY;
	}

	/**
	 * The SERMIN attribute.
	 */
	protected java.math.BigDecimal SERMIN = new BigDecimal("0");

	/**
	 * Gets the SERMIN value.
	 */
	public java.math.BigDecimal getSERMIN() {
		return SERMIN;
	}

	/**
	 * Sets the SERMIN value.
	 */
	public void setSERMIN(java.math.BigDecimal SERMIN) {
		this.SERMIN = SERMIN;
	}

	/**
	 * The SERMAX attribute.
	 */
	protected java.math.BigDecimal SERMAX = new BigDecimal("0");

	/**
	 * Gets the SERMAX value.
	 */
	public java.math.BigDecimal getSERMAX() {
		return SERMAX;
	}

	/**
	 * Sets the SERMAX value.
	 */
	public void setSERMAX(java.math.BigDecimal SERMAX) {
		this.SERMAX = SERMAX;
	}

	/**
	 * The SERHLP attribute.
	 */
	protected java.lang.String SERHLP = "";

	/**
	 * Gets the SERHLP value.
	 */
	public java.lang.String getSERHLP() {
		return SERHLP;
	}

	/**
	 * Sets the SERHLP value.
	 */
	public void setSERHLP(java.lang.String SERHLP) {
		this.SERHLP = SERHLP;
	}

	/**
	 * The SERCTY attribute.
	 */
	protected java.lang.String SERCTY = "";

	/**
	 * Gets the SERCTY value.
	 */
	public java.lang.String getSERCTY() {
		return SERCTY.toUpperCase().trim();
	}

	/**
	 * Sets the SERCTY value.
	 */
	public void setSERCTY(java.lang.String SERCTY) {
		this.SERCTY = SERCTY;
	}

	/**
	 * The SERCMI attribute.
	 */
	protected java.math.BigDecimal SERCMI = new BigDecimal("0");

	/**
	 * Gets the SERCMI value.
	 */
	public java.math.BigDecimal getSERCMI() {
		return SERCMI;
	}

	/**
	 * Sets the SERCMI value.
	 */
	public void setSERCMI(java.math.BigDecimal SERCMI) {
		this.SERCMI = SERCMI;
	}

	/**
	 * The SERCMA attribute.
	 */
	protected java.math.BigDecimal SERCMA = new BigDecimal("0");

	/**
	 * Gets the SERCMA value.
	 */
	public java.math.BigDecimal getSERCMA() {
		return SERCMA;
	}

	/**
	 * Sets the SERCMA value.
	 */
	public void setSERCMA(java.math.BigDecimal SERCMA) {
		this.SERCMA = SERCMA;
	}

	/**
	 * The SERCHL attribute.
	 */
	protected java.lang.String SERCHL = "";

	/**
	 * Gets the SERCHL value.
	 */
	public java.lang.String getSERCHL() {
		return SERCHL;
	}

	/**
	 * Sets the SERCHL value.
	 */
	public void setSERCHL(java.lang.String SERCHL) {
		this.SERCHL = SERCHL;
	}

	/**
	 * The SERTAX attribute.
	 */
	protected java.lang.String SERTAX = "";

	/**
	 * Gets the SERTAX value.
	 */
	public java.lang.String getSERTAX() {
		return SERTAX.toUpperCase().trim();
	}

	/**
	 * Sets the SERTAX value.
	 */
	public void setSERTAX(java.lang.String SERTAX) {
		this.SERTAX = SERTAX;
	}

	/**
	 * The SERUTI attribute.
	 */
	protected java.lang.String SERUTI = "";

	/**
	 * Gets the SERUTI value.
	 */
	public java.lang.String getSERUTI() {
		return SERUTI.toUpperCase().trim();
	}

	/**
	 * Sets the SERUTI value.
	 */
	public void setSERUTI(java.lang.String SERUTI) {
		this.SERUTI = SERUTI;
	}

	/**
	 * The SERACT attribute.
	 */
	protected java.lang.String SERACT = "";

	/**
	 * Gets the SERACT value.
	 */
	public java.lang.String getSERACT() {
		return SERACT.toUpperCase().trim();
	}

	/**
	 * Sets the SERACT value.
	 */
	public void setSERACT(java.lang.String SERACT) {
		this.SERACT = SERACT;
	}

	/**
	 * The SERDTR attribute.
	 */
	protected java.math.BigDecimal SERDTR = new BigDecimal("0");

	/**
	 * Gets the SERDTR value.
	 */
	public java.math.BigDecimal getSERDTR() {
		return SERDTR;
	}

	/**
	 * Sets the SERDTR value.
	 */
	public void setSERDTR(java.math.BigDecimal SERDTR) {
		this.SERDTR = SERDTR;
	}

	/**
	 * The SERFLG attribute.
	 */
	protected java.lang.String SERFLG = "";

	/**
	 * Gets the SERFLG value.
	 */
	public java.lang.String getSERFLG() {
		return SERFLG.toUpperCase().trim();
	}

	/**
	 * Sets the SERFLG value.
	 */
	public void setSERFLG(java.lang.String SERFLG) {
		this.SERFLG = SERFLG;
	}

	/**
	 * The SERNOM attribute.
	 */
	protected java.lang.String SERNOM = "";

	/**
	 * Gets the SERNOM value.
	 */
	public java.lang.String getSERNOM() {
		return SERNOM.toUpperCase().trim();
	}

	/**
	 * Sets the SERNOM value.
	 */
	public void setSERNOM(java.lang.String SERNOM) {
		this.SERNOM = SERNOM;
	}

	//
	/**
	 * The FLG attribute.
	 */
	protected java.lang.String FLG = "";

	/**
	 * Gets the FLG value.
	 */
	public java.lang.String getFLG() {
		return FLG.toUpperCase().trim();
	}

	/**
	 * Sets the FLG value.
	 */
	public void setFLG(java.lang.String FLG) {
		this.FLG = FLG;
	}

	public String toString() {
		StringBuffer results = new StringBuffer();

		results.append(getClass().getName() + "\n");
		results.append("\tSERBNK=" + SERBNK + "\n");
		results.append("\tSERTYP=" + SERTYP + "\n");
		results.append("\tSERCOM=" + SERCOM + "\n");
		results.append("\tSERNAM=" + SERNAM + "\n");
		results.append("\tSERDS1=" + SERDS1 + "\n");
		results.append("\tSERDS2=" + SERDS2 + "\n");
		results.append("\tSERREF=" + SERREF + "\n");
		results.append("\tSERACC=" + SERACC + "\n");
		results.append("\tSERVOU=" + SERVOU + "\n");
		results.append("\tSERRTY=" + SERRTY + "\n");
		results.append("\tSERMIN=" + SERMIN + "\n");
		results.append("\tSERMAX=" + SERMAX + "\n");
		results.append("\tSERHLP=" + SERHLP + "\n");
		results.append("\tSERCTY=" + SERCTY + "\n");
		results.append("\tSERCMI=" + SERCMI + "\n");
		results.append("\tSERCMA=" + SERCMA + "\n");
		results.append("\tSERCHL=" + SERCHL + "\n");
		results.append("\tSERTAX=" + SERTAX + "\n");
		results.append("\tSERUTI=" + SERUTI + "\n");
		results.append("\tSERACT=" + SERACT + "\n");
		results.append("\tSERDTR=" + SERDTR + "\n");
		results.append("\tSERFLG=" + SERFLG + "\n");

		return results.toString();
	}

	private String SERIMG;
	private String SERIMGH;
	private String SERCOLOR;

	/**
	 * @return the sERIMG
	 */
	public String getSERIMG() {
		return SERIMG;
	}

	/**
	 * @param sERIMG the sERIMG to set
	 */
	public void setSERIMG(String sERIMG) {
		SERIMG = sERIMG;
	}

	/**
	 * @return the sERIMGH
	 */
	public String getSERIMGH() {
		return SERIMGH;
	}

	/**
	 * @param sERIMGH the sERIMGH to set
	 */
	public void setSERIMGH(String sERIMGH) {
		SERIMGH = sERIMGH;
	}

	/**
	 * @return the sERCOLOR
	 */
	public String getSERCOLOR() {
		return SERCOLOR;
	}

	/**
	 * @param sERCOLOR the sERCOLOR to set
	 */
	public void setSERCOLOR(String sERCOLOR) {
		SERCOLOR = sERCOLOR;
	}

}