package com.afirme.afirmenet.ibs.databeans;

/**
 * Jdbc Bean Class<br>
 * <br>
 * Autogenerated on 10/01/2003 10:32:13<br>
 * &nbsp;&nbsp;&nbsp; table = "DC_NOMINA_PBean"
 * 
 * @author Generator
 */
public class NOMINA_P implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
	 * The ENTITYID attribute.
	 */
	protected java.lang.String ENTITYID = "";

	/**
	 * Gets the ENTITYID value.
	 */
	public java.lang.String getENTITYID() {
		return ENTITYID.toUpperCase().trim();
	}

	/**
	 * Sets the ENTITYID value.
	 */
	public void setENTITYID(java.lang.String ENTITYID) {
		this.ENTITYID = ENTITYID;
	}

	/**
	 * The NAME attribute.
	 */
	protected java.lang.String NAME = "";

	/**
	 * Gets the NAME value.
	 */
	public java.lang.String getNAME() {
		return NAME.toUpperCase().trim();
	}

	/**
	 * Sets the NAME value.
	 */
	public void setNAME(java.lang.String NAME) {
		this.NAME = NAME;
	}

	/**
	 * The BNKRECPTOR attribute.
	 */
	protected java.lang.String BNKRECPTOR = "";

	/**
	 * Gets the BNKRECPTOR value.
	 */
	public java.lang.String getBNKRECPTOR() {
		return BNKRECPTOR.toUpperCase().trim();
	}

	/**
	 * Sets the BNKRECPTOR value.
	 */
	public void setBNKRECPTOR(java.lang.String BNKRECPTOR) {
		this.BNKRECPTOR = BNKRECPTOR;
	}

	/**
	 * The ACC attribute.
	 */
	protected java.lang.String ACC = "";

	/**
	 * Gets the ACC value.
	 */
	public java.lang.String getACC() {
		return ACC.toUpperCase().trim();
	}

	/**
	 * Sets the ACC value.
	 */
	public void setACC(java.lang.String ACC) {
		this.ACC = ACC;
	}

	/**
	 * The ACCTYPE attribute.
	 */
	protected java.lang.String ACCTYPE = "";

	/**
	 * Gets the ACCTYPE value.
	 */
	public java.lang.String getACCTYPE() {
		return ACCTYPE.toUpperCase().trim();
	}

	/**
	 * Sets the ACCTYPE value.
	 */
	public void setACCTYPE(java.lang.String ACCTYPE) {
		this.ACCTYPE = ACCTYPE;
	}

	/**
	 * The CCY attribute.
	 */
	protected java.lang.String CCY = "";

	/**
	 * Gets the CCY value.
	 */
	public java.lang.String getCCY() {
		return CCY.toUpperCase().trim();
	}

	/**
	 * Sets the CCY value.
	 */
	public void setCCY(java.lang.String CCY) {
		this.CCY = CCY;
	}

	/**
	 * The REFENUM attribute.
	 */
	protected java.lang.String REFENUM = "";

	/**
	 * Gets the REFENUM value.
	 */
	public java.lang.String getREFENUM() {
		return REFENUM.toUpperCase().trim();
	}

	/**
	 * Sets the REFENUM value.
	 */
	public void setREFENUM(java.lang.String REFENUM) {
		this.REFENUM = REFENUM;
	}

	/**
	 * The FLAG attribute.
	 */
	protected java.lang.String FLAG = "";

	/**
	 * Gets the FLAG value.
	 */
	public java.lang.String getFLAG() {
		return FLAG.toUpperCase().trim();
	}

	/**
	 * Sets the FLAG value.
	 */
	public void setFLAG(java.lang.String FLAG) {
		this.FLAG = FLAG;
	}

	public String toString() {
		StringBuffer results = new StringBuffer();

		results.append(getClass().getName() + "\n");
		results.append("\tENTITYID=" + ENTITYID + "\n");
		results.append("\tNAME=" + NAME + "\n");
		results.append("\tBNKRECPTOR=" + BNKRECPTOR + "\n");
		results.append("\tACC=" + ACC + "\n");
		results.append("\tACCTYPE=" + ACCTYPE + "\n");
		results.append("\tCCY=" + CCY + "\n");
		results.append("\tREFENUM=" + REFENUM + "\n");

		return results.toString();
	}

}